### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by 40P3** [kesava-wow/kuinameplates2#101]
Hi,

Kind of constant error I receive since I've installed your nameplates a few days ago. (crazy good by the way and seems you got no issue with nameplate placement, unlike tidyplates -overlapping OR crazily stretching out when more then a handfull is visible on the screen, Kuinameplates doesn't do this).

```
24x ...ameplates_Spell_Alert\Kui_Nameplates_Spell_Alert-r20150914152059.lua:4: Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'KuiNameplates'.
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:186: in function `GetAddon'
...ameplates_Spell_Alert\Kui_Nameplates_Spell_Alert-r20150914152059.lua:4: in main chunk

Locals:
(*temporary) = "Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'KuiNameplates'."
```

Got all classes so I can test stuff if you want (this error comes up with all classes though). I use chatter and goldpaw's UI with the chat bubble mod that can break other addons thought, so let me know if this is related -just guessing, recently had some issues with that-.

Thanks for looking into this and if needed I can provide additional info.

**Comment by kesava-wow** [comment]
This is just because you have the Kui_Nameplates_Spell_Alert addon installed which isn't updated and likely won't be updated. Disable it.

**Comment by 40P3** [comment]
Ohh ok thanks I delete it then. :)
