### ISSUE TITLE
Marksman Hunter Vulnerabilty Debuff not showing on nameplate

### ISSUE THREAD

**Issue by agent7773** [kesava-wow/kuinameplates2#105]
Assuming I'm interpreting this correctly the Auras > Show own Auras option should show the debuffs I put on the target on the targets nameplate, but my Hunter Vulnerability debuff is not showing up.  

Is this a bug or am I misinterpreting what this option does?

If the addon isn't suppose to show that any chance you could add that in a future patch and/or a way I could make the addon show it?

Love the addon btw!  

Thanks!

**Comment by kesava-wow** [comment]
If you have the whitelist enabled, you can add auras using kui spelllist config from curse.

**Comment by agent7773** [comment]
Awesome!  Works for me now!  TY!
 

 

 

-----Original Message-----
