### ISSUE TITLE
Z and Y axis alignment for Auras

### ISSUE THREAD

**Issue by Rynthian** [kesava-wow/kuinameplates2#108]
Request to build an alignment option for Auras.

After updating to 2-13-2 from 2-12-beta-2-1-gc01dfaf I noticed the Auras centering and found the option to disable that. However, the after unchecking the box, I noticed the Auras floating above the health bar (and a little toward the center) rather than aligning against it as I was used to.

Attaching a link for example, new GitHub user and it doesn't seem to want to upload: http://imgur.com/a/CS0Px

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplatesextras/issues/11

Position of auras is otherwise unchanged with the centre option disabled. It depends on icon size, squareness, etc.
