### ISSUE TITLE
Option to tweak auras frame positions

### ISSUE THREAD

**Issue by d87** [kesava-wow/kuinameplates2#109]
I couldn't find a way to change that in-game.

**Comment by Rynthian** [comment]
It would be nice, yes.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/issues/108

**Comment by Rynthian** [comment]
So there will be no support to move the floating auras frame around via a position slider like there is for text elements?

**Comment by kesava-wow** [comment]
See the linked issue.

**Comment by Rynthian** [comment]
That's unfortunate. Thank you.

**Comment by kesava-wow** [comment]
As in, this: https://github.com/kesava-wow/kuinameplatesextras/issues/11

That encompasses this. I won't be putting it in the core config UI because it's not that kind of addon. I delegate simple things like this to custom.lua or extras for particularly popular things.
