### ISSUE TITLE
Option to use default UI whitelist for auras

### ISSUE THREAD

**Issue by d87** [kesava-wow/kuinameplates2#110]
Default nameplates use "HARMFUL|INCLUDE_NAME_PLATE_ONLY" filter for UnitAura to show only critical debuffs.
Like knowing about aoe stuns from other players is about the extent of what i need from nameplate auras,   so simple option to mimic default behavior would be nice.

Correction:
Actually they use

    local name, rank, icon, count, debuffType, duration, expiration, caster, _, nameplateShowPersonal, spellid, _, _, _, nameplateShowAll = UnitAura(...)

and

    local function ShouldShowBuff(name, caster, nameplateShowPersonal, nameplateShowAll, duration)
	if (not name) then
		return false;
	end
	return nameplateShowAll or
		   (nameplateShowPersonal and (caster == "player" or caster == "pet" or caster == "vehicle"));
    end

**Comment by kesava-wow** [comment]
Sorry for taking so long, I didn't realise how important this was (i.e. what the default UI showed) until ~someone~ started ranting about it in IRC.
