### ISSUE TITLE
Option to turn off NPC titles

### ISSUE THREAD

**Issue by EiniStein** [kesava-wow/kuinameplates2#111]
I would like an option to turn off NPC titles, which in practice are mostly level numbers (+elite) anyway and can take quite a lot of room when many NPCs are around.

**Comment by kesava-wow** [comment]
They shouldn't be showing levels. Do you have the colour-blind interface option enabled by any chance?

**Comment by EiniStein** [comment]
Nope, color-blind is not enabled. I mean the titles below the names where it reads something like "Supplies & Repairs" or "Flightmaster". When a NPC doesn't have any such function then it simply reads "Level 110" or "Level 110 (Elite)".

While I wrote this I had an idea and switched language from German to English. Seems that the level title only happens when the client is set to German.

I would simply fade all those non-interactive friendly NPCs to 0, but unfortunately KNP also seems to fade non-targeted enemies in combat by the very same logic, so fade to zero is no practical option atm.

**Comment by kesava-wow** [comment]
Right. The only way to get that data is to parse it out of the tooltip. What I'm doing now is discarding it if it starts with "level". Obviously I forgot about other languages.

**Comment by EiniStein** [comment]
Great, thanks. I used English language until recently, because it became too much work coordinating world quests with guild members who use German clients. Now I have to manually modify all spells and auras in my Vuhdo raid-bars, but at least everyone in the guild is using the same names for mobs and quests now. 👂

**Comment by EiniStein** [comment]
The German word for "level" is "Stufe".

**Comment by kesava-wow** [comment]
(Guessing you accidentally closed it with "close and comment")

**Comment by EiniStein** [comment]
Ah, yes, sorry. And thanks for reopening. 👍
