### ISSUE TITLE
npc title text shows levels on languages other than en-us

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#112]

**Comment by EiniStein** [comment]
I wonder: Would completely turning off NPC titles (not just the level part) lead to their names coming down a row (where the title used to take space) or would this just leave an empty space?

**Comment by kesava-wow** [comment]
It would adjust to be in the centre of the frame, yes.

**Comment by EiniStein** [comment]
Is there a specific reason why names are adjusted to the center of the frame instead of the bottom? Elvui does place them at the bottom, which still seems far enough (as in nearly too far) above the head a player/NPC.

**Comment by kesava-wow** [comment]
Just because I want the frame to be in the center of the clickable area (which addons can't move), really.

**Comment by EiniStein** [comment]
Thanks for the info.

**Comment by kesava-wow** [comment]
Needs to be tested on other languages. I suspect the translation of "level" has the potential to be different depending on what follows.

**Comment by EiniStein** [comment]
Works well with a German client. ;)

**Comment by kesava-wow** [comment]
this commit tested working on German, French, Russian, Korean, Chinese, English

**Comment by kesava-wow** [comment]
Scratch that, doesn't work with elites

**Comment by kesava-wow** [comment]
Extra overhead this time but I'm not really sure how else to deal with it. Tooltip parsing is annoying.
