### ISSUE TITLE
Threat when Tank/DPS to work as it did on TidyPlatesThreatPlates.

### ISSUE THREAD

**Issue by Freakatsu** [kesava-wow/kuinameplates2#117]
Basically the only reason i was using TDTP was that tanking plates as a tank could be set to a color, and while dpsing the same color meant safe.

So as a tank, Green=Good, Red = Bad.

As DPS Green=Good, Red=Bad.

Right now there is no option for the DPS specs for that, and the bars are just red, unless Force tank does that and i didnt realize, but the bars are still red for me.

Basically what i mean, as a tank i have agroo, GOOD, GREEN BAR.

As a DPS i dont have agroo, GOOD, GREEN BAR.

Can it be done? Or because of the Dual Spec removal the detection was removed? I dont know :D Just wondering.

**Comment by kesava-wow** [comment]
Bars are coloured when you have threat. Force makes it do that even when youre not in a tanking spec. I don't have any interest in inverting the logic for dps.
