### ISSUE TITLE
[FEATURE REQUEST] Totem Filter

### ISSUE THREAD

**Issue by Homaxz** [kesava-wow/kuinameplates2#121]
I would like to request this feature: filtering out totems. I think this was an option before Legion, and I would love to have it back. Thanks for your great work.

**Comment by kesava-wow** [comment]
It may have been an option in the default UI which was removed as a checkbox but remains as a CVar, which you can modify with AdvancedInterfaceOptions. I'm not sure if it is still there, though. If it isn't, then there is no way for addons to arbitrarily hide nameplates correctly.

https://github.com/kesava-wow/kuinameplates2/issues/58 is a related issue which could provide relevant filtering for forcing totems to be faded out.

**Comment by Homaxz** [comment]
Sorry for not being clear enough in the OP. What I meant is to filter out specific totems, so I can only show important ones. For example: only show Counterstrike Totem.
