### ISSUE TITLE
More settings for text

### ISSUE THREAD

**Issue by Daeveren** [kesava-wow/kuinameplates2#127]
Requesting having options for text alignment (level text, hp text) left/center/riught. I like to have level text to the right side and hp text in the center, but I have to modify the addon code everytime i update it.
Also, the ability to chose a different text size (or even font) for each of these 2 (and separate from the mob name) would be wonderful.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplatesextras/issues/11
