### ISSUE TITLE
Bigger frames on aggro

### ISSUE THREAD

**Issue by Daeveren** [kesava-wow/kuinameplates2#129]
The feature would scale to a custom level (say 1.5 or 2) the nameplates for the mobs that you aggro (while in a group only). For non-tanks, the mobs that you lose aggro would get one of these emphasized bars, really useful for easier clicking on the mobs and tauning (particularly useful when tanking packs of mobs and one gets loose).

**Comment by kesava-wow** [comment]
This is a note for myself: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.target-scale.lua

Scaling frames is a bit messy, and breaks pixel-perfectness, so I'm not interested in putting it in the main addon. It could be a custom script, though. (The linked one is just a test).
