### ISSUE TITLE
about execute

### ISSUE THREAD

**Issue by solor** [kesava-wow/kuinameplates2#132]
is that possible to make execute color function auto disable when player on class that doesn't has execute skill?
I mainly play warrior, so I always use execute color, but when I play DH alt, I have to disable execute color  manually :confused:

**Comment by kesava-wow** [comment]
It defaults to 20% on anything without an execute so that you can use it to spot things at low health. If you want to disable it for a character, you can use a different profile. Which might seem a bit overkill.
