### ISSUE TITLE
[FEATURE REQUEST] text on "Interrupted"

### ISSUE THREAD

**Issue by Homaxz** [kesava-wow/kuinameplates2#135]
With default Blizzard Nameplates, when a cast is successfully interrupted, the cast text is replaced with "interrupted" and the castbar color changes. 

KuiNameplates right now instantly hides the cast after interrupting, I would like to request a feature that adds functionality similar to default Nameplates. (Custom duration of the "interrupted text" shown, and custom color of the castbar are a plus, but not needed.)

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/issues/176
