### ISSUE TITLE
power par on plates?

### ISSUE THREAD

**Issue by ikuria** [kesava-wow/kuinameplates2#140]
need the option to see a mana/power bar on the plates :(

**Comment by kesava-wow** [comment]
I probably won't make this an option, but you can force the power bar to show on every frame by commenting out a part of create.lua. In Kui_Nameplates_Core\create.lua, find this:

    local function UpdatePowerBar(f,on_show)
        if  f.state.player and

And change it to this:

    local function UpdatePowerBar(f,on_show)
        if  --f.state.player and

**Comment by ikuria** [comment]
thanks, thats helped alot, but i'm sad because my old style isnt not working anymore (i think)
http://www.wowinterface.com/downloads/info22049-KuiNameplatescustom.lua.html
this was my custom file back the days - now i want to get it back - but your code is so much diffrent (better) now :D
