### ISSUE TITLE
KUI does not work at all

### ISSUE THREAD

**Issue by Sir-Hexen** [kesava-wow/kuinameplates2#142]
My wife and i recently just installed LUI but KUI works perfectly on my machine but not hers, Tried reinstalling it and all and nothing works D:

Addon is loaded
Addon allows configuration
Addon and other two sub addons are enabbled

I would like to add that we disabled ALL addons and only left KUI on and it still does not work.

**Comment by kesava-wow** [comment]
Post a screenshot of the nameplates or lack thereof, please.

**Comment by Sir-Hexen** [comment]
Here you are.
![screenshot 2016-12-09 10 15 39](https://cloud.githubusercontent.com/assets/8753906/21053746/c2684d34-bdf8-11e6-921c-e179ca580f28.png)

**Comment by kesava-wow** [comment]
There are only floating names (not nameplates) in that screenshot, which implies nameplates are disabled. Check FAQs 1, 1a and 2 in the curse description.

**Comment by Sir-Hexen** [comment]
Look i'm going to be strait with you, Your really rude, With that aside, instead of just passing us along i can tell you strait up screenshot or not, Your Name Plates come and go randomly, whether or not your close or far from a player, And the same thing happens with passive mobs as well as hostile mobs. So instead of rudely passing us by, Why not actually try and help your followers who enjoy and like your mod?

**Comment by kesava-wow** [comment]
.. I wrote the FAQs so that I don't have to type the same things over and over, I am trying to help. I don't see how that's rude. Did you check all the options I refered you to? Do they show only when you target something?

**Comment by Sir-Hexen** [comment]
Thank you, I will look into this now. I only said you were rude only because you basically brushed through without even giving any possible fix, Now Blizzard's Name Options keeps resetting itself every 10 - 30 seconds for both your own Addon and Tidyplates ( We want to use yours more than anything ) I keep having to use Shift + V to turn them back on constantly for some odd reason and i did just see the /run SetCVar("nameplateShowFriendlyNPCs",1 to use which i will try here in a moment and reply again.

**Comment by Sir-Hexen** [comment]
Alright so i went to Summers Rest with plenty of Passive and Friendly NPC's and used the script command /run SetCVar("nameplateShowFriendlyNPCs",1 and sadly it is not working, i did double check blizzards settings just in case and they are in fact turned on, so i am not too sure what might be the issue at this point.

**Comment by Sir-Hexen** [comment]
![2016-12-10_09-00-41](https://cloud.githubusercontent.com/assets/8753906/21073817/5aa105dc-beb7-11e6-8eba-0293d7308c7c.jpg)

**Comment by kesava-wow** [comment]
Do they now stay visible until you leave combat perhaps?

**Comment by Sir-Hexen** [comment]
Sadly no, everything stays the same :/

**Comment by Sir-Hexen** [comment]
Though what i show is players show name plates, but not the Green/Yellow NPC's

**Comment by kesava-wow** [comment]
When you ran this:

/run SetCVar("nameplateShowFriendlyNPCs",1)

Did you perhaps forget to include the parenthesis at the end (since that's what you've quoted above)? That's important.

Also, just in case you don't realise, having "combat action: hostile" and "combat action: friendly" set to "show" means that nameplates will be automatically shown upon entering combat, and then hidden upon leaving combat (that's explained in the tooltip for those options - I'm making it a bit clearer next update).

Other than that, and what you've already read in FAQs 1, 1a and 2, I don't know why else nameplates would be being randomly toggled. Some other addons can be set up to do this, DynamicCam, for instance. But other than the "combat action" settings, I don't change nameplate visibility.

**Comment by Sir-Hexen** [comment]
Alright so we fixed one issue which was setting those two Combat actions to Do Nothing, And i copy and pasted exactly what you typed here in the last message  and also the version from your main page of the addon, Sadly that script did nothing :/ The only issue now is still Friendly/Passive ( Green/Yellow ) NPC's/Mobs not showing your nameplates :( and i so apologize for the late reply, me and my wife were gone for most of the day.

**Comment by Sir-Hexen** [comment]
Nope Ignore that last message, I am freaking retarded, I thought the ) at the end of that script was not needed, Boy was i damn stupid, Kesava, Thank you SO very much, You have helped me and my wife put hours of testing to rest, Thank you SO much.

**Comment by kesava-wow** [comment]
:D
