### ISSUE TITLE
Threat display on nameplates

### ISSUE THREAD

**Issue by geancarlo** [kesava-wow/kuinameplates2#147]
Hello. With the recent creation of Mythic+ dungeons and, specifically, the "skittish" affix, tracking my threat to mobs became necessary even as a DPS. To do so I added a little hack to kui nameplates in the UpdateHealthText function (create.lua):

```
local _,_,threatpct,_,_ = UnitDetailedThreatSituation('player', f.unit);
if threatpct then
	disp = disp .. strformat(' [%d]', threatpct)
end
```

The result is shown [here](https://imgur.com/a/YZwv4). It would be nice if this feature could be baked into the addon in a less hacky way and with proper configurability.

**Comment by kesava-wow** [comment]
will be making this here: https://github.com/kesava-wow/kuinameplates-customs/issues/1
