### ISSUE TITLE
[Feature Request] All Debuffs/Buffs on Friendly Name Plates

### ISSUE THREAD

**Issue by dremglob** [kesava-wow/kuinameplates2#149]
Pretty simple, I noticed how useful this feature would be on Guarm Mythic being able to see if someone had a debuff from the boss on their Name-only bars. Or at least being able to add a whitelist of debuffs to show would be amazing.

**Comment by pquerner** [comment]
Kinda same with Star Augur Mythic, where players of same symbol need to run together in a specific time or they wipe the group. I have seen it in this video for example, but I dont know how to add this exactly.

https://www.twitch.tv/videos/118197574
Chill debuff at 1:16:11
or Mythic debuff at 1:42:22
