### ISSUE TITLE
Show state icons doesn't work

### ISSUE THREAD

**Issue by Crayovan** [kesava-wow/kuinameplates2#150]
Checking the box doesn't have any effect (Level Text is not enabled). 
The elite/rare icon is never shown.

**Comment by kesava-wow** [comment]
Do you have level text enabled? It needs to be disabled in order for state icons to show (as it says in the tooltip).

**Comment by Crayovan** [comment]
No, I didn't have that enabled. No matter what options i choose, they never show up. I have auto-focused and name-only disabled.

**Comment by Crayovan** [comment]
I removed all my add-ons except Blizzard_ ones, and I still can't get them to show up. 

![wowscrnshot_edit](https://cloud.githubusercontent.com/assets/13605142/21733992/2bf77f8a-d42f-11e6-839b-c4fb08c10a7e.jpg)

**Comment by Crayovan** [comment]
Please ignore this, it's not a bug.. I was looking to see the "elite" icons, but there aren't any, only for rares and bosses. 

It helps to see the elite status on the nameplates for world quests. 

I dug into the lua code, and added another classification check for 'elite' in UpdateStateIcon(), then modified one of the unused icons in state-icons.tga to include a dragon. It works perfectly.

**Comment by Crayovan** [comment]
![wowscrnshot_edited_2](https://cloud.githubusercontent.com/assets/13605142/21736129/704e7578-d43c-11e6-9121-c0056b5a95cb.jpg)
