### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by RockOnzo** [kesava-wow/kuinameplates2#151]
Hi I have installed the updated version of your addon and it throws up the following lua error have reverted back to version 77d3e0f-alpha and i dont get the error.

22x Kui_Nameplates_Core\config.lua:229: attempt to index field 'RaidIcon' (a nil value)
Kui_Nameplates_Core\config.lua:229: in function `?'
Kui_Nameplates\plugins/fading.lua:42: in function <Kui_Nameplates\plugins/fading.lua:39>
Kui_Nameplates\plugins/fading.lua:59: in function <Kui_Nameplates\plugins/fading.lua:55>
Kui_Nameplates\plugins/fading.lua:68: in function <Kui_Nameplates\plugins/fading.lua:65>

Locals:
f = KuiNamePlate1 {
 0 = <userdata>
 elements = <table> {
 }
 parent = NamePlate1 {
 }
 handler = <table> {
 }
 state = <table> {
 }
 CastBarUpdateFrame = <unnamed> {
 }
 isChatBubble = false
 unit = "nameplate1"
 cast_state = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'RaidIcon' (a nil value)"

**Comment by kesava-wow** [comment]
There is no code difference between 7929ab9 (the current head) and 77d3e0f (the one you reverted to) so this was probably just a one time thing.
