### ISSUE TITLE
Set Maximum health and current healt on health bars

### ISSUE THREAD

**Issue by Daniel-one** [kesava-wow/kuinameplates2#155]
Hello!

I'm really really really happy with Kui nameplates! It is awesome, it is what I was looking for. Thanks for the amazing work :)

I'm a programmer and I also know Lua but I never coded any WoW addon so instead of digging on the source, I wanted to ask the question here.

Could be possible to replace the level text on the health bar with current health?
Like current health ---- maximum health.

I like to do PvP and right now I use the current health but I like to check the opponent's maximum health to have a hint about his gear and so. 

So this way I could know his maximum health (which means its gear too) and his current health.

If more hands are needed for this, I could implement it with some little guidance.

Thanks!

**Comment by kesava-wow** [comment]
Can be done with a custom.lua: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.level-to-health.lua

Read the readme here: https://github.com/kesava-wow/kuinameplates-customs to use it.

**Comment by Daniel-one** [comment]
Thank you very very much!

Your work is amazing!
