### ISSUE TITLE
Random nameplates appearing

### ISSUE THREAD

**Issue by altf4-guild** [kesava-wow/kuinameplates2#16]
Notice a static nameplate appearing in the middle of my screen. When I run /framestack it's being listed as either: KuiNamePlate3, KuiNamePlate4, or KuiNamePlate5, and so forth. I'm not seeing any option or ability to remove them but wondering if it's an error / a nameplate.

Screenshot: http://i.imgur.com/jZnGeZl.jpg

**Comment by kesava-wow** [comment]
This is the player nameplate, which is a new option from blizzard. You can disable/enable it in esc > interface > names.

**Comment by Znuff** [comment]
http://i.imgur.com/4CSuJhh.png
![*sigh*](http://i.imgur.com/4CSuJhh.png)

**Comment by altf4-guild** [comment]
Welp, embarrassed -- thanks guys.
