### ISSUE TITLE
("Force tank mode") Only use offtank colour if the player is a tank

### ISSUE THREAD

**Issue by Juggerone** [kesava-wow/kuinameplates2#161]
This allows DPS to use "force tank mode" to make threat more noticable, but without just making all nameplates purple while a tank has them.

---

Hello, 

I'd like to request some improvements for tank mode, if possible.

1. When you're in tank specialization: have one additional coloring option "Lost aggro" or something like this. That would work like this in a mythic+/raid scenario, let's say.
- you have aggro > color green (tanked - existing option)
- you start losing aggro > color orange (transitioning - existing option)
- **you lost aggro or mobs were ninja pulled (tanked by any non-tank) -> different color (new option)**
- tanked by off tank when there's one > color purple (offtank - existing option)

2. When you're not in tank specialization and have "force tank mode" on, pretty much same as above with a little difference.
- you have aggro > color green
- you start getting aggro > color orange
- you don't have aggro > color red/default
- **tanked by another tank > disabled for non-tank**

I use "force tank mode" in raid to quickly notice if I get aggro, but all the time my nameplates are purple because of offtank option. Would be great to be disabled for non-tanks.

3. Color nameplates by raid marker. E.g: if target is marked by square > color blue. Would make it easy to notice a priority target when bunch of mobs are stacked.

4. I can't seem to figure out a way to disable the aggro red glow from borders. If I have like 10 mobs aggro'd all are green with red glow. Would be great to have an option to disable that if possible.
http://i.imgur.com/NrZuu6w.jpg

I hope I'm not too picky with these suggestions.
Thank you.

**Comment by kesava-wow** [comment]
1: https://github.com/kesava-wow/kuinameplates2/issues/139
3: https://github.com/kesava-wow/kuinameplatesextras/issues/14 (going to move stuff from Extras into Customs, though)
4: https://github.com/kesava-wow/kuinameplates2/issues/120

2. This is a good point, and is what I'll use this issue for (issue posts with multiple issues inside them are difficult to work with).

Thanks.

**Comment by Juggerone** [comment]
Thank you for considering this!
