### ISSUE TITLE
option to alter cvar "nameplateOverlapV"

### ISSUE THREAD

**Issue by Brackz777** [kesava-wow/kuinameplates2#163]
Hi there, 

Would it be possible to create an option where enemies have nameplates that stack above the one underneath that doesn't overshadow the dots on the  previous nameplate?
The nameplates themselves do stack but they overshadow the dots. Affliction needs to have larger dots squares to be tracked easier. 

Please help.

**Comment by kesava-wow** [comment]
Possible, yes. For right now, you can modify the CVar "nameplateOverlapV". This is 1.1 by default which means nameplates have about a 10% gap between them in stacking mode. If you set it to 2.2 for example, they'd stack twice as far apart.

You can do that by running this (it will take effect immediately):

/run SetCVar('nameplateOverlapV', 2.2)

**Comment by kesava-wow** [comment]
moved to #180
