### ISSUE TITLE
(Boss Mode) After Reload -> Friendly Nameplates on

### ISSUE THREAD

**Issue by Merathilis** [kesava-wow/kuinameplates2#167]
As the title says, if you disable the friendly nameplates (Shift+V) and reload, the friendly nameplates are turned back on.

**Comment by kesava-wow** [comment]
What situation was this in? On a boss, in dalaran, ...?

**Comment by Merathilis** [comment]
In every situation. A simple reload turned it back on.

**Comment by kesava-wow** [comment]
If you disable /knp > boss mods > "allow boss mods to control visibility..." does it still happen?

**Comment by Merathilis** [comment]
Yeah, still the same issue.

**Comment by kesava-wow** [comment]
I can't reproduce this, then. If it doesn't happen with only KNP enabled (I realise it's annoying to do this if you have a lot of addons) then another addon is doing it. Nothing in KNP controls visibility apart from that option and the two drop-downs in "general", but they won't be taking effect until combat starts or ends.

**Comment by Merathilis** [comment]
I have a script for that in my ElvUI edit, so no problemo :P I'll let you know

**Comment by Merathilis** [comment]
Ok, i found the culprit. It is AdvancedInterfaceOptions
