### ISSUE TITLE
Enhancement: OmniCC support on Auras (or something equal)

### ISSUE THREAD

**Issue by Lyzu** [kesava-wow/kuinameplates2#168]
Pretty straight forward: timers on auras should work with OmniCC or provide more flexible options like:
- Aura timer text font
- Aura timer text alignment
- Aura timer text hide
- Aura timer clock (like OmniCC)
- Aura timer clock reverse
- Aura timer clock alpha

**Comment by kesava-wow** [comment]
cooldown frames (what omnicc hooks into) have rendering issues when they can overlap as they do with nameplates. https://github.com/kesava-wow/kuinameplates2/issues/174

**Comment by kesava-wow** [comment]
moving to #152

**Comment by kesava-wow** [comment]
Added the capability to allow OmniCC to handle cooldowns to this: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.simple-aura-mods.lua.
