### ISSUE TITLE
Suggestion: Be able to show HP percentage?

### ISSUE THREAD

**Issue by itcotta** [kesava-wow/kuinameplates2#17]
It would be really useful to be able to see hp % instead of hp left, I'm not sure if this is still doable after the changes blizzard made to nameplates a few months ago though.

**Comment by kesava-wow** [comment]
Yes, I plan to add config for this much like it existed before.

**Comment by roncli** [comment]
I am converting over from Aloft... what was it like pre-Legion?

I'd like to see the ability to add Max Health and Percentage, and even change from the default short values to the full values if possible.

**Comment by kesava-wow** [comment]
Before legion, you could change between deficit, percent, current or blank health text depending on whether or not a unit is at full health. That's what I'll be adding.
