### ISSUE TITLE
(Boss mods) option to make friendly nameplates invisible (in conjuction with clickthrough) unless used by an aura

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#170]

**Comment by kesava-wow** [comment]
This could just be a core thing. Be a lot easier that way.

**Comment by Ninjouz** [comment]
Hey, I was looking into that as well. Having friendly names overcrowding your screen is not that helpful :).

Can you maybe implement a fading option like "avoid on auras" or something like that. But then, you would have to choose the correct auras if you put that on the Core ?

**Comment by kesava-wow** [comment]
Precluded
