### ISSUE TITLE
Quest exclamation/question marks on nameplates

### ISSUE THREAD

**Issue by vestrene** [kesava-wow/kuinameplates2#171]
It would be nice and very useful to be able to have the exclamation marks indicating a quest mob on the nameplates, e.g. on the right side of the nameplate. 

Would this be possible? It's something that is frustrating to be missing when doing world quests.

**Comment by behub** [comment]
https://mods.curse.com/addons/wow/questplates

This works well with KuiNameplates.

**Comment by vestrene** [comment]
Nice! Is there a way to chance how raid icons are displayed? I am not a fan of them floating next to a bar, I much prefer above the head of the target, as well as an option to color the entire health bar the color of the icon (like tidy plates Threat plates does).

**Comment by kesava-wow** [comment]
Moving raid icons delegated to here for now: https://github.com/kesava-wow/kuinameplatesextras/issues/11

**Comment by Beet4** [comment]
Any updates on this feature request? :) ElvUIs default NamePlates now got this with a skull next to quest mobs. I would love something similiar in KNP.

**Comment by Beet4** [comment]
@kesava-wow Are you planning to add this feature sometime in the future?

**Comment by Stanzilla** [comment]
@Beet4 just use https://mods.curse.com/addons/wow/questplates

**Comment by Beet4** [comment]
@Stanzilla I know but I do not like the looks of it. ElvUIs implementation is much nicer looking. Would love something similiar in kui. :)
