### ISSUE TITLE
Text -> Hide non-tracked names doesn't always work

### ISSUE THREAD

**Issue by yifanzh** [kesava-wow/kuinameplates2#172]
I have Interface - Names - NPC Names set to Quest NPCs, under this setting Blizzard's nameplate will only show name for current target (plus quest NPC). However, with Kui it seems like all names are shown as long as I am on their threat table, even if "Hide non-tracked names" is checked.

Another possibly related problem is that neutral health bar doesn't turn red when I attack it like Bliz nameplate does. I assume the "hated" color option would kick in.

**Comment by kesava-wow** [comment]
names are also shown while in combat with a unit, yes.
