### ISSUE TITLE
Combat action: friendly BUG

### ISSUE THREAD

**Issue by RoyalSertr** [kesava-wow/kuinameplates2#173]
Have Combat action: friendly set to Do Nothing, yet each time boss fights starts, the friendly nameplates shows up. Have this issue from last update or so, worked properly before.

**Comment by kesava-wow** [comment]
/knp > boss mods > allow boss mods to control visibility

**Comment by RoyalSertr** [comment]
Did that, now when there is pack of enemies and I target one, rest fades out.

**Comment by kesava-wow** [comment]
That means you have /knp > general > faded alpha set to 0.
