### ISSUE TITLE
low health/execute range

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#18]

**Comment by kesava-wow** [comment]
Death Row (Warrior Fury/Arms PvP talent) => 25% otherwise 20%; Shadow Priest "Reaper of Souls" talent => 35% instead of 20%

**Comment by Stanzilla** [comment]
* http://www.wowhead.com/spell=198490/death-row
* http://www.wowhead.com/spell=199853/reaper-of-souls

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/05191979a7d99af5a6611ebdc54d6c96c2899045
