### ISSUE TITLE
Profile menu unable to be used

### ISSUE THREAD

**Issue by Kronickhaz** [kesava-wow/kuinameplates2#182]
When I try to switch profiles the drop down menu is behind the various setting options, and clicking the various profiles I wish to change to changes which setting screen I am on instead. 
![image](https://cloud.githubusercontent.com/assets/26025072/23331462/4ed5e370-fbb2-11e6-83ec-c267a3a08bca.png)
How do I fix?

**Comment by Kronickhaz** [comment]
I disabled the addon 'Skinner' and I was able to change it, not sure if that addon was the issue, but disabling it allowed me to change the profile and then re-enable it. Thanks for the help :D

**Comment by kesava-wow** [comment]
I believe this should have been fixed by: https://github.com/kesava-wow/kuinameplates2/commit/308b62fb687ece52f7a2ccca454fbc8524d91fc1
