### ISSUE TITLE
Error after combat

### ISSUE THREAD

**Issue by RoyalClem** [kesava-wow/kuinameplates2#183]
Message: Interface\AddOns\Kui_Nameplates_BarAuras\mod.lua:114: attempt to index field 'cd' (a nil value)
Time: 02/26/17 23:51:10
Count: 35
Stack: [C]: ?
Interface\AddOns\Kui_Nameplates_BarAuras\mod.lua:114: in function `?'
Interface\AddOns\Kui_Nameplates\messages.lua:323: in function `RunCallback'
Interface\AddOns\Kui_Nameplates\elements/auras.lua:292: in function <Interface\AddOns\Kui_Nameplates\elements/auras.lua:252>
Interface\AddOns\Kui_Nameplates\elements/auras.lua:388: in function `GetButton'
Interface\AddOns\Kui_Nameplates\elements/auras.lua:413: in function `DisplayButton'
Interface\AddOns\Kui_Nameplates\elements/auras.lua:369: in function `GetAuras'
Interface\AddOns\Kui_Nameplates\elements/auras.lua:316: in function `Update'
Interface\AddOns\Kui_Nameplates\elements/auras.lua:799: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:79: in function <Interface\AddOns\Kui_Nameplates\messages.lua:44>

Locals: 

Please help! BTW love the add on!

**Comment by kesava-wow** [comment]
the module causing that error (BarAuras) isn't included in the package on curse - you need to manually update it from the repo. This was fixed in a commit 7 days ago: https://github.com/kesava-wow/kuinameplates2/blob/master/Kui_Nameplates_BarAuras/mod.lua

Thanks.
