### ISSUE TITLE
Feature Request: Custom Nameplates

### ISSUE THREAD

**Issue by danielseide** [kesava-wow/kuinameplates2#184]
First of all thanks for your great work with KNP. I really appreciate it but I miss the functionality of custom nameplates which my previously used nameplates addon Tidy Plates has.

There you can create a profile for a mob specified by name which you can customize for these mobs. I regularly used this feature to color the health bars in different ways helping me to notice add spawns or targeting a certain mob during raid encounters.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.name-and-target-colour.lua

**Comment by danielseide** [comment]
Thanks for the link. Installed it and works great so far. 
But adding new "name/color pairs" via editing the .lua and /reload is kinda uncomfortable. Could you add a gui option for esc menu->interface->addons?

**Comment by kesava-wow** [comment]
Sorry for the very late reply, I've been taking a break, delegated that here: https://github.com/kesava-wow/kuinameplates-customs/issues/5
