### ISSUE TITLE
avoid fading casting

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#185]

**Comment by jcadduono** [comment]
huh, i guess it's a good thing i searched this before opening a feature request 'issue'

if this is ever worked on, it'd be great to be able to have it set up in options like:

Don't fade casting:
[x] Interruptible
[x] Non-interruptible

with Mythic+ being so popular now, this would be a highly sought after feature

**Comment by kesava-wow** [comment]
partial https://github.com/kesava-wow/kuinameplates2/commit/57cf51dd788fa736c897fa52834cf43ce4bfb461

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/f1ed26b43e18f1f3eb4cbf2f8dbd9c3ad71fc2c7
