### ISSUE TITLE
Stacked nameplates with base  one

### ISSUE THREAD

**Issue by czapleusz** [kesava-wow/kuinameplates2#191]
![wowscrnshot_032517_004649](https://cloud.githubusercontent.com/assets/26662826/24317120/b539cab2-10f4-11e7-8c20-44474d3b786f.jpg)

Hello, so I can't find any option to disable basic blizzard nameplate... It looks like this on screen, any tips?

**Comment by kesava-wow** [comment]
that's tidyplates. disable that.
