### ISSUE TITLE
7.2 Class Power issue

### ISSUE THREAD

**Issue by arinn1204** [kesava-wow/kuinameplates2#193]
Whenever switching to brewmaster, Lua error shows up in regards to showing the stagger bar
it was retrieved using bug sack/bug grabber.

2x ...rfaceKui_Nameplates\elements/classpowers.lua:253: Usage: local maxPower = UnitPowerMax(unitToken [, powerType, unmodified])
[C]: in function `UnitPowerMax'
...rfaceKui_Nameplates\elements/classpowers.lua:253: in function <...rfaceKui_Nameplates\elements/classpowers.lua:247>
...rfaceKui_Nameplates\elements/classpowers.lua:552: in function `func'
Kui_Nameplates\messages.lua:81: in function <Kui_Nameplates\messages.lua:44>

Locals:
(*temporary) = "player"
(*temporary) = "stagger"

**Comment by kesava-wow** [comment]
Thanks!
