### ISSUE TITLE
Auras won't display on Nameplates.

### ISSUE THREAD

**Issue by EternalSoulz666** [kesava-wow/kuinameplates2#194]
Worked fine before I updated the addon, now nameplates refuse to show my auras no matter what I do in the "Auras" tab of the settings.

Downgrading addon to a previous version removes my nameplates completely no matter what I do.

**Comment by kesava-wow** [comment]
Run: /knp dump-config
and take a screenshot of the result for me (it'll print out a bunch of stuff in your chat frame).

**Comment by kesava-wow** [comment]
Also if you have Kui_Nameplates_BarAuras or Kui_Nameplates_Custom installed, disable them and try again.
