### ISSUE TITLE
No nameplates/health bars

### ISSUE THREAD

**Issue by vosy1984** [kesava-wow/kuinameplates2#195]
There are no nameplates/health bars on the Parasitic Lashers during High Botanist Tel`arn encounter in The Nighthold raid, making the adds hard to target with all the effects the fight has. They show only in 1 out of 30 times they spawn.

http://imgur.com/a/za1sA

I can provide a VOD with all the encounter fights (and wipes)

**Comment by kesava-wow** [comment]
Relatively sure this isn't related to knp but next time i get a chance to go there i can check. Do you get any lua errors?

**Comment by vosy1984** [comment]
Don't know if this is what you mean, but this is what I get every time I do spells on the targets.

http://imgur.com/a/0cMtm

**Comment by kesava-wow** [comment]
Ah, barauras. Yes. I regret telling anyone that existed. You need to redownload the _BarAuras module from the repo here - it isn't included in the curse package.
