### ISSUE TITLE
[Feature Request] Friendly PC level option in Name-only mode.

### ISSUE THREAD

**Issue by Duir-WoW** [kesava-wow/kuinameplates2#198]
The Basics:
I would like an option to show the level of friendly player characters while they're displayed in "Name-only" mode.

The Reasoning:
I know it sounds counter-intuitive to a feature called "Name-only", but I don't like having health bars on outside of combat. Especially large areas like Orgrimmar/Stormwind or popular quest hubs, it's just too much crap on the screen and isn't needed (imo) outside of raids/dungeons. I do, however, like seeing the levels of players around me and have gotten used to that with ELvUI's nameplate settings. Unfortunately, I've had to disable those in 7.2 so I can have friendly nameplates while in instances thanks Blizzard's decision to block nameplates altogether rather than just block access to features they've now decided UI authors shouldn't have access to. I've tried a few different nameplate addons and this is the best one I've found out of what's available. A lot seem to force the healthbars on you with no way to disable them (short of disabling friendly nameplates altogether) which defeats the purpose.

**Comment by Duir-WoW** [comment]
Some screenshots to better illustrate my request...

<img src="https://s26.postimg.org/iqpvbzvm1/KUI_Healthbars.png"></img>
Current way to see levels (healthbars on)

<img src="https://s26.postimg.org/4ybggd4uh/KUI_Name-only.png"></img>
How much better it looks without healthbars (Name-only mode)

<img src="https://s26.postimg.org/mlt9ekert/Elv_UI.png"></img>
How I had it setup using ElvUI Nameplates

**Comment by kesava-wow** [comment]
Sorry for the late reply, I've been taking a break.

Probably won't add this to the main setup, but it could be a custom. In fact I think someone made a pull request or something for it.. but I can't remember.

If I make one it'll be here and I'll comment again: https://github.com/kesava-wow/kuinameplates-customs

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates-customs/issues/3 might do what you want (... I can't entirely remember if name-only mode would override its' modifications)
