### ISSUE TITLE
put stagger bar below health/energy

### ISSUE THREAD

**Issue by siming85** [kesava-wow/kuinameplates2#202]
Would be great if there's an option to put the stagger bar below the Main HP/Energy bar for monks.

I'd be happy to provide the coding if you could drop a pointer on where the sorting of the bars are... tried looking and couldn't find the specific spot.

**Comment by kesava-wow** [comment]
It's in /Kui_Nameplates/elements/classpowers.lua:CreateBar. As you can gather from that this bar isn't like the power or health bars, it's a the classpowers element, so options for moving it are delegated to this: https://github.com/kesava-wow/kuinameplates2/issues/178
