### ISSUE TITLE
The Addon cannot remember

### ISSUE THREAD

**Issue by x00dis** [kesava-wow/kuinameplates2#203]
Greetings Draenei, writer of magical code, adventurer of the Broken Isles,

I am having difficulty with your magical addon.  It seems to be unable to remember the way in which I set it.  Each time I morph into a new character the addon seems to forget what I asked of it and must be reminded again.  (Basically everytime i switch toons the addon resets itself, even if I make a new profile). I pray that you see the dilemma of the malfunctioning spellwork.

Very Sincerely,

Heldort the Fabulous

**Comment by kesava-wow** [comment]
Does it remember the names you give profiles, or does it forget those too? Could you think of the following series of letters: "/knp dump-config" and describe to me the text which appears in your mind. 

((Do that twice - put in some random settings, make a profile, etc, then copy the text from that. Then reload/relog and do it again without changing any settings))

**Comment by x00dis** [comment]
I spoke the magical words that you suggested.  My mind went fuzzy and the following appeared before my eyes.

[14:46] 700471.821: { ["profile"] = "Professor" }
[14:46] 700471.821: { ["font_face"] = "MoK", ["title_text_players"] = true, ["font_size_normal"] = 16, ["font_size_small"] = 14, ["guild_text_players"] = true }

I then morphed into a undead and uttered the words again and saw.

[14:48] 700620.25: { ["profile"] = "default" }
[14:48] 700620.25: {  }

I open the Kui book and made the annotations of 

[14:46] 700471.821: { ["profile"] = "Professor" }
[14:46] 700471.821: { ["font_face"] = "MoK", ["title_text_players"] = true, ["font_size_normal"] = 16, ["font_size_small"] = 14, ["guild_text_players"] = true }

I then closed the book and took a brief name. When I awoke I uttered the words again and saw

[14:48] 700620.25: { ["profile"] = "default" }
[14:48] 700620.25: {  }

What do you advise M'Lady,

**Comment by kesava-wow** [comment]
Can't really stay in character for this: could you close wow completely, open the curse/twitch app and uninstall KuiNameplates. If it asks if you also want to delete saved variables (or something similar) say yes. Then reinstall it and try again. Also try disabling other add-on's if you haven't already. 

If none of that helps then... I'm not sure what it would be.

**Comment by kesava-wow** [comment]
Fixed today. This was a stupid bug, sorry.
