### ISSUE TITLE
[Concussive Shot] Spell id: 5116 Hunter Concussive shot not showing on nameplates

### ISSUE THREAD

**Issue by nToxik** [kesava-wow/kuinameplates2#204]
There seems to be a problem with Hunter "Concussive Shot" (spell id: 5116). The slow debuff just won't show on the target. I have turned on and off Kui SpellList Config) as well and tried to configure it there but still it won't show no matter what I do.
 
Could you check to see why Concussive Shot debuff (5116) which is a slow is not working?

**Comment by kesava-wow** [comment]
Do you have /knp > auras > "use default ui" enabled? If so try disabling that. But read the tooltip.

**Comment by nToxik** [comment]
Okay sorry for taking so long to get back to you. Yes, I have Auras turned on but unchecking 'Use default UI filter' seemed to do the trick and fix it. Not sure why turning it off would fix it but it did.

Thanks!

**Comment by kesava-wow** [comment]
I think the default doesn't include slows, and only has hard-CCs like poly. I can't remember exactly. Either way I think this should be in there, so fixing that is delegated to this: https://github.com/kesava-wow/kuinameplates2/issues/175
