### ISSUE TITLE
Add cooldownframes to simple-aura-mods

### ISSUE THREAD

**Issue by Rreba** [kesava-wow/kuinameplates2#205]
I'm super picky about my auras on the target.  I love everything about KUI Nameplates, except for the fact that i cannot change the way my auras count down above my target.  I would like to know if there is any possible way to make it so my auras fade away like a clock (exactly the way DoTs fade on blizzards default plates).  I'm aware there are options to flash/fade when the DoT is about to fall off, but I would really like to have the clock-fading style while still using KUI nameplates.

Thanks

**Comment by kesava-wow** [comment]
#152 #174

**Comment by Rreba** [comment]
I set up the custom folder in my addons folder and I implemented custom.simple-aura-mods.lua.  Followed the steps precisely.  When I look at my addons in game it says I have Kui Nameplates Custom Injector now, which sounds good.  But all that has changed is the timer of my dots has moved to the center of the icon.  I still do not see any new options menu in the settings that will allow me to configure the auras (ie. for a clock/spiral fade) besides the basic KUI aura settings.

**Comment by kesava-wow** [comment]
That script doesn't include that capability. It could do though, I suppose. It's not in the main add-on because last time I tried it was broken by the above linked issues. I'll repurpose this to remind me to put cool down frames in the custom script.

**Comment by kesava-wow** [comment]
Added "ADD_COOLDOWN_SPIRAL" variable to the custom: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.simple-aura-mods.lua
