### ISSUE TITLE
"Frame sizes -> Minus frame width" slider doesn't work properly

### ISSUE THREAD

**Issue by killarny** [kesava-wow/kuinameplates2#206]
As the title says, however the slider next to it for "Minus frame height" does function properly.

Here I set the **width to 20** and the **height to 40**. As shown on the mob to the right, the height is correct, but the width is not:

![kui-frame-width-1](https://cloud.githubusercontent.com/assets/29001/26416184/3ebfcd98-4072-11e7-95ea-4780b07fb101.png)

If I change the **width to 200** and the **height to 20**, the height did change accordingly, but again the width is being ignored:

![kui-frame-width-2](https://cloud.githubusercontent.com/assets/29001/26416413/07357b74-4073-11e7-96f2-2ee4a0df8fc3.png)

**Comment by kesava-wow** [comment]
That's not a minus frame, it's just nameless. Nameless frames use the minus height but normal width.
