### ISSUE TITLE
Class powers not updating correctly (Affliction Warlock)

### ISSUE THREAD

**Issue by Mykeh22** [kesava-wow/kuinameplates2#209]
*I know this issue has been mentioned before*

I am just making this thread to state that it's still a problem in 7.2.5. 
The issue is that the wow frame will always show the correct amount of soul shards but sometimes the KUIframes will lag behind and not show that you have any. This will happen when you are casting a spell that uses a soul shard e.g. unstable affliction or seed of corruption. When using the soul condiut tallent (has a chance to refund the shard). These refunded shards are the problem.

The frames will eventually update them self if a shard is generated from agony (DOT) and then it will shoot up to the correct amount which can sometimes be from 0 to 3 which is annoying. I'm having to find myself looking at the default wow frames as its so unreliable. If I use the default wow unit frames as well those update correctly so I'm unsure what you can do to fix the KUIframes?

Made a short clip trying to show it happening; https://www.twitch.tv/videos/153567407
you can see it happen briefly at 0:46 until my agony ticks and generated a shard,
also at 1:21 and 2:04

Thanks!

![wowscrnshot_062217_083605](https://user-images.githubusercontent.com/29622542/27422403-eec62812-5725-11e7-89c7-646d1fc24eaf.jpg)

**Comment by kesava-wow** [comment]
should be fixed in the latest beta (beta-exceptional-flying-eagle) (https://github.com/kesava-wow/kuinameplates2/commit/33686edbf544a68adcfc716d6e3a71a9a3fdaf9d)

**Comment by Mykeh22** [comment]
Thank you! Just installed the beta-exceptional-flying-eagle and **its fixed!**
