### ISSUE TITLE
localisation translate question

### ISSUE THREAD

**Issue by EKE00372** [kesava-wow/kuinameplates2#211]
hello kesava,

I'm planning do  zhTW translate, I saw you've open CurseForge's localisation system but I think pull request on github is faster, but I didnt found locale file other than l11n.lua.

so localisation actullay wont work O.O?

**Comment by kesava-wow** [comment]
It's not implemented yet. It'll probably be in the next version.

Thanks.

**Comment by kesava-wow** [comment]
just added a simple implementation here: https://github.com/kesava-wow/kuinameplates2/tree/master/Kui_Nameplates_Core_Config/locale

**Comment by EKE00372** [comment]
which format should i follow?

**Comment by kesava-wow** [comment]
the one in zhCN.

**Comment by EKE00372** [comment]
have translate some tooptil, i'll do the rest and zhCN, but i lose l11n.lua and some new config so i use CurseForge's localisation system Q_o.
