### ISSUE TITLE
Non targeted enemy NPCs nameplates showing

### ISSUE THREAD

**Issue by Cityfella** [kesava-wow/kuinameplates2#229]
HI, thanks for the great addon, just one thing that sort of dissapeared when using this one is that when i'm attacked by x amount of enemies, only the nameplate that i'm targeting shows up, The other ones dissapear, i'm posting two screenshots of when i have 1 NPC targetd and when i have 0 NPCs targeted.

https://imgur.com/a/uhSb0 <--- 1 NPC targeted 

https://imgur.com/a/EsCOS <-- None NPC targeted.

This is really an issue for me on fights like Mistress Sassz'ine with the snakes and shit...

Thanks for helping out!

**Comment by kesava-wow** [comment]
Post the output of the slash command "/knp dump-config" for me.

**Comment by Cityfella** [comment]
{ ["profile"] = "default" }

{ ["fade_alpha"] = 0, ["frame_height"] = 17, ["font_size_small"] = 11, ["auras_hide_all_other"] = true, ["font_size_normal"] = 17, ["health_text_hostile_max"] = 3, ["auras_icon_normal_size"] = 35, ["fade_speed"] = 0, ["font_face"] = "Expressway", ["ignore_uiscale"] = true, ["tank_mode"] = false, ["health_text"] = true, ["auras_icon_squareness"] = 1 }

**Comment by kesava-wow** [comment]
You have /knp > faded alpha set to 0. Faded alpha sets the alpha value which nameplates other than your target will fade out to, 0 being invisible, so that's what's happening here.

**Comment by Cityfella** [comment]
So it should be 1 ?

**Comment by kesava-wow** [comment]
1 would make them entirely opaque at all times, which can make it more difficult to find your targeted nameplate. The default is 0.5.

**Comment by Cityfella** [comment]
Thamks alot!
