### ISSUE TITLE
Couple issues

### ISSUE THREAD

**Issue by Gilgatn** [kesava-wow/kuinameplates2#230]
I have a few issues with this addon

it looks fantastic first off but a couple of things

The cast bar being unable to move it is quite annoying because you cant move the name of the mob to a convenient enough spot so it covers the cast bar every single time or if you move the name up your auras cover the name you just cant win there

The friendly npcs im talking about like a deer or a goat in the forest has a weird nameplate with nothing other then a bar unless i click on it then it expands to normal length just like the Hostile NPCS bar

I saw no option to change this so I could make it the same I want to see their name and bar the exact same as a hostile NPC as i can attack this mob

If any of these can be done please let me know how because its would make my life super easy

**Comment by kesava-wow** [comment]
The small bar is used for smaller units, classed as "minus". You can sort-of disable it by setting the "minus frame width" and "minus frame height" options under /knp > frame sizes to be the same as the standard width and height options. Then uncheck the "Hide non-tracked names" option under /knp > text if you also want the names to show.
