### ISSUE TITLE
Configurable cast bar anchor point

### ISSUE THREAD

**Issue by lakhpache** [kesava-wow/kuinameplates2#232]
(IMO) Changes at the top of the nameplate are noticed more quickly than changes at the bottom - we normally visually scan an object from top-to-bottom.

Therefore it's advantageous to be able to put the cast bar at the top of the nameplate, where it's likely to be noticed & reacted to fractionally more quickly.

I've modded my own personal version - I just swapped the anchor points in CreateCastBar and UpdateNameTextPosition in Core's create.lua & that seems functional - but it'd be nice to see an easy-to-use option built-in.

**Comment by kesava-wow** [comment]
Moving castbar is delegated to this: https://github.com/kesava-wow/kuinameplatesextras/issues/11 (or other external mods).
