### ISSUE TITLE
Change Target arrows shadow

### ISSUE THREAD

**Issue by corbakhan** [kesava-wow/kuinameplates2#235]
Hi,

i've succeded the target arrows shape but the former shadow remains. How can change that ? 

thanks

a little screenshot to help :

![wowscrnshot_111817_193824](https://user-images.githubusercontent.com/2656522/32983664-6e99a3b0-cc98-11e7-8633-4706a4b1d418.jpg)

**Comment by kesava-wow** [comment]
It looks like you've edited the image but left the alpha channel the same. How you correct the alpha channel depends on what image editor you're using. There are tutorials you can find for that.

**Comment by corbakhan** [comment]
okay thank you ! i use photoshop, i'll try that
