### ISSUE TITLE
[Request] I want to show a percent sign behind the number.

### ISSUE THREAD

**Issue by ILIKECHICKENTOOMUCH** [kesava-wow/kuinameplates2#236]
Hello, Author

When a percentage is selected, only numbers are displayed.

How can I put a percent sign behind the numbers?

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.health-text-mods.lua (instructions here: https://github.com/kesava-wow/kuinameplates-customs)

**Comment by ILIKECHICKENTOOMUCH** [comment]
@kesava-wow 

Thank you very much.
