### ISSUE TITLE
Changing Castbar Spellname size and position

### ISSUE THREAD

**Issue by K4r4zh4n** [kesava-wow/kuinameplates2#237]
Hey, 
Thank You for this addon, it's pretty great! :D
 
I would like to know if there is any way allready in the addon or coming in the near future, for me to edit the spellname-text for the castbar.
What i would lilke to do is edit the Textsize of the spellname and the position.relativ to the castbar,
so that the Spellname is inside the Castbar and not below for example.
 
Thanks for your work

**Comment by kesava-wow** [comment]
position: https://github.com/kesava-wow/kuinameplatesextras/commit/fe27a65bd07cfe7a5bb934f927309f5179837b91

**Comment by kesava-wow** [comment]
moving: https://github.com/kesava-wow/kuinameplates2/issues/207
size: can be done with a custom
