### ISSUE TITLE
Can't disable pet nameplates

### ISSUE THREAD

**Issue by Zarupta** [kesava-wow/kuinameplates2#238]
I love this addon, except for one thing - I can't disable healthbars for enemy player's pets when in combat with them. 

Usually this doesn't matter, but in a battleground it can get pretty obnoxious, especially with Army of the Dead. I've tried disabling it in the game's options, but it hasn't worked, and I couldn't find an option for it within KUI itself.

Any help is greatly appreciated.

**Comment by kesava-wow** [comment]
I believe there's a cvar for this. I don't know it off hand. You can find it using the cvar browser in the add-on "advanced interface options." It'll be something like nameplateshowenemypets. 

Related: https://github.com/kesava-wow/kuinameplates2/issues/180

**Comment by Zarupta** [comment]
0 value means it's deactivated, correct? If so, this has not resolved the issue, unfortunately. I appreciate the response, though.
