### ISSUE TITLE
Small visual oddity...

### ISSUE THREAD

**Issue by ZaephirMoth** [kesava-wow/kuinameplates2#239]
Hello there !

  Moving here the issues & requests I mentioned on Curse, for the sake of clarity. The "Show Name Text" -> "Class color friendly names" option work perfectly 9 times out of 10, even with custom class colors, but it fails to add those changes in a few cases, namely (from my experience) with demon hunters and shamans. I'll add screenshots to give you [concrete examples](https://imgur.com/a/nyWMC).
  I made several experiments with [custom class colors](https://www.curseforge.com/wow/addons/classcolors) and KUI, including on characters devoid of any other addons, but it always fails to recognize changes when it comes to shamans and demon hunters, which nameplates' keep their default blue and purple colors. Could there be a difference in the way your addon calls for the colors of those specific classes ? According to [this documentation](https://github.com/phanx-wow/ClassColors/wiki), it should be quite simple, but there are so many lua files in KUI that I don't know at all where to check ^^...
 
EDIT : Confirmed... After more tests, this small shortcoming really comes from KUI. The simpliest way to experiment it remains to unload all addons, load "Class Colors", use it to change all class colors, witness the results - no problem with the demon hunters, etc. -, and then to add "KUI Nameplates". Those two faulty classes' nameplates (mentionned above) will return to their default colors...
  Here's the dump config' anyway...
 
 { ["profile"] = "Base" }
{ ["fade_avoid_execute_friend"] = true, ["auras_on_personal"] = false, ["auras_icon_normal_size"] = 16, ["clickthrough_enemy"] = true, ["nameonly_damaged_friends"] = false, ["health_text_friend_max"] = 2, ["guild_text_players"] = true, ["castbar_unin_colour"] = { [1] = 0.8, [2] = 0, [3] = 0 }, ["ignore_uiscale"] = true, ["tankmode_force_enable"] = true, ["health_text_hostile_dmg"] = 1, ["nameonly_neutral"] = true, ["execute_colour"] = { [1] = 0, [2] = 0, [3] = 0 }, ["health_text"] = true, ["frame_width_personal"] = 200, ["font_size_small"] = 12, ["tankmode_trans_colour"] = { [1] = 0.70196078431373, [2] = 0.70196078431373, [3] = 0.098039215686274 }, ["nameonly_all_enemies"] = true, ["class_colour_enemy_names"] = true, ["castbar_height"] = 16, ["colour_player_class"] = true, ["fade_friendly_npc"] = true, ["classpowers_colour_paladin"] = { [1] = 0.74901960784314, [2] = 0.74901960784314, [3] = 0.90588235294118 }, ["tankmode_force_offtank"] = true, ["tankmode_other_colour"] = { [1] = 1, [2] = 0.4156862745098, [3] = 0 }, ["clickthrough_self"] = true, ["auras_show_all_self"] = true, ["frame_height_personal"] = 16, ["bar_texture"] = "Blizzard", ["fade_speed"] = 1, ["health_text_hostile_max"] = 2, ["clickthrough_friend"] = true, ["fade_avoid_execute_hostile"] = true, ["target_arrows_size"] = 32, ["target_arrows"] = true, ["target_glow_colour"] = { [1] = 0.3921568627451, [2] = 0.11764705882353, [3] = 0.03921568627451, [4] = 1 }, ["frame_width_minus"] = 200, ["powerbar_height"] = 12, ["frame_width"] = 200, ["classpowers_size"] = 20, ["classpowers_enable"] = false, ["title_text_players"] = true, ["fade_avoid_nameonly"] = false, ["frame_height_minus"] = 12, ["classpowers_on_target"] = false, ["fade_all"] = true, ["frame_height"] = 16, ["frame_glow_size"] = 16, ["fade_untracked"] = true, ["font_size_normal"] = 14, ["threat_brackets"] = true, ["hide_names"] = false, ["fade_neutral_enemy"] = true, ["auras_icon_minus_size"] = 12, ["level_text"] = true, ["font_face"] = "Friz Quadrata TT", ["auras_icon_squareness"] = 1, ["classpowers_colour_overflow"] = { [1] = 0.8, [2] = 0.30196078431373, [3] = 0.8 }, ["tankmode_tank_colour"] = { [1] = 1, [2] = 0, [3] = 0 }, ["castbar_colour"] = { [1] = 0.74901960784314, [2] = 0.35294117647059, [3] = 0.35294117647059 }, ["health_text_friend_dmg"] = 1 }
 
  Cheers !
  Benjamin

**Comment by kesava-wow** [comment]
Fixed recently.
