### ISSUE TITLE
opposing-faction player nameplates don't work on "normal" servers

### ISSUE THREAD

**Issue by killarny** [kesava-wow/kuinameplates2#24]
I'm using version 2-4 of the addon, with the same config profile on two different server types - one server is rp-pvp (Emerald Dream) the other is normal (Sen'jin). Enemy player nameplates work fine on the rp-pvp server, but just don't get skinned at all by kuinameplates on the normal server. Opposing-faction player names are simply shown without a nameplate at all.

Note here in this screenshot that the alliance players standing inside the building are working, but the horde player and her minion are apparently being ignored.

![untitled](https://cloud.githubusercontent.com/assets/29001/17004664/3b226a28-4e93-11e6-827d-23c363f8663b.png)

To be certain, I've checked that my names settings are configured to show "enemy" players and their minions:

![names](https://cloud.githubusercontent.com/assets/29001/17004763/d3251190-4e93-11e6-9e4f-fb6fe6c86a6e.png)

These nameplates work fine for enemy players on rp-pvp servers, so I can only assume that other-faction players are flagged differently on normal servers.

**Comment by kesava-wow** [comment]
This is a blizzard thing which can't be changed by addons.

**Comment by killarny** [comment]
Maybe you are misunderstanding my report. The nameplates work on pvp servers - and the nameplates worked on normal servers with your older versions. I think something in your recent rewrite may have been missed.

**Comment by kesava-wow** [comment]
See my edit. It's always been this way. They do "work", it's just that nameplates aren't rendered at all for unattackable players, and never have been. You'll also see it happening in sanctuaries.
