### ISSUE TITLE
Font and visual style for non-combat pets...

### ISSUE THREAD

**Issue by ZaephirMoth** [kesava-wow/kuinameplates2#240]
Hello there !

  Moving here the issues & requests I mentioned on Curse, for the sake of clarity. It concerns both the yellow (neutral - 1hp) ones and the blue (friendly) companions, but indeed, in non-combat situations. I wasn't really expecting life nameplates - for there aren't any, I forgot that and you're right -, but at least to be affected by some visual settings, like those of your 'name-only' mode (custom fonts, custom heights, etc.). Otherwise, it creates quite a [visual gap](https://imgur.com/a/v8tA4) between them and the rest of the UI affected by your addon...
  So, according to you, there isn't any way to avoid that gap ? No way at least apply the same visual (font) style to them ?
  Thanks for answer anyway...
  Benjamin

**Comment by kesava-wow** [comment]
No, they can't be modified by add-ons.
