### ISSUE TITLE
Name-only additional features ?

### ISSUE THREAD

**Issue by ZaephirMoth** [kesava-wow/kuinameplates2#241]
Hello again !

  Just a small request here... Name-only mode, for now, feels quite limited compared to all the features offered by your addon to normal nameplates. I understand that it was probably (precisely) designed this way, in order to simplify things regarding friendly NPC or non-attackable enemies, but it's still a shame, because with your "colored letters by health" and "buff & debuff" options still displayed in name-only mode, this one's almost as functionnal in combat as your 'normal' mode. And even prettier ^^ ! Which means it could be used to keep an eye on all enemies even while using some other "Unit Frame" addons (or just Blizzard's default UI) to display the desired information about the main target. It would now just require, little by little, some compatibility with your other functions regarding spell-casting and aggro display for example. 
  Also, I've noticed that the "On units in combat with you" (name-only)filter always takes precedence on any other, making "On target" a little useless : wether one ticks it or not, he won't get name-only mode on his target once engaged in combat. This means less flexibility for anyone who appreciates your addon (for displaying most enemies' nameplates), but would prefer name-only mode on his main target because he already uses other specialized addons to track it.

  Thanks for reading ! Cheers !
  Benjamin

**Comment by kesava-wow** [comment]
Name only should have threat display with a glow, same as it does on health bars. But it won't override the target glow.

The "in combat" and "on target" options aren't mutually exclusive. Your target is still in combat with you. "don't show on units in combat but do show on my target, even if it is in combat with me" is a bit too specific a need for a check box. The rules for enabling/disabling name only are at _Core/create.lua:1771 if you have any lua knowledge and want to try that yourself. 

I'm not going to add cast bars to name only in the base add-on. A little icon or something could work, I suppose. I might play with that at some point. 

Thanks.
