### ISSUE TITLE
Absolute Corruption Affliction Warlock Talent

### ISSUE THREAD

**Issue by Hopplagrill** [kesava-wow/kuinameplates2#242]
Whenever im applying Corruption with the absolute Corruption talent (so its infinite) the dot doesnt show on my nameplates. its shown up on the targetframe but thats it.

https://i.clouds.tf/0qsp/mru1.jpg

**Comment by kesava-wow** [comment]
Blizzard haven't flagged it to be displayed. You can whitelist it using KuiSpellListConfig.
