### ISSUE TITLE
Hide personal resource nameplates.

### ISSUE THREAD

**Issue by hcmendez** [kesava-wow/kuinameplates2#243]
Is there any way to hide the personal resource bar? I've made my own on weakuras and hidden the default bar with CVars, but cvars cant hide the bars generated by Kui. Help pls.

**Comment by Havocados** [comment]
To add onto this I would like to hide the glow on the end of personal resource bars such as mana or energy

**Comment by kesava-wow** [comment]
You mean the class powers? They can be disabled by unchecking /knp > class powers > show class resources. If you mean the personal nameplate, the cvars to disable the default will also disable KNP's modification of it. Since it isn't there to modify. So I'm assuming you don't mean that.
