### ISSUE TITLE
Suggestions/Questions

### ISSUE THREAD

**Issue by funi9** [kesava-wow/kuinameplates2#246]
Hi, love the addon, just a few suggestions / questions:

**Is it possible to add arena id as status text / above HP bar**?
Cast bar offset / height / scale overall, with separate options for cast icon?
Personal resource (combo points) movable or atleast center top anchor instead of current bottom center?

Keep up the good work.

**Comment by kesava-wow** [comment]
1. https://github.com/kesava-wow/kuinameplates2/issues/13 - i.e. not currently. Should definitely do that. 
2. Delegated to _Extras for now. 
3. https://github.com/kesava-wow/kuinameplates2/issues/178 - ditto. 

Thanks.
