### ISSUE TITLE
Request: Change aura icon text color and size.

### ISSUE THREAD

**Issue by xaring** [kesava-wow/kuinameplates2#250]
Hey, been using your addon for a couple of months now, and I wondered if it would be possible to add a customization feature that allowed us to change the aura's text size and remove the coloring by duration. I'd rather see it always white than white-yellow-red.

Thanks!

https://i.imgur.com/sn25Mgf.png

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.simple-aura-mods.lua
