### ISSUE TITLE
Brewmaster ox statue off-tank detection

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#251]
- ~~does that still exist in bfa?~~ 
- ~~does it actually work in a way that makes sense for this?~~

**Comment by Vorda01** [comment]
Would love to see this implemented. Black Ox still perfectly functions as an offtank.

**Comment by Asb10** [comment]
I find this to be pretty useful for monks especially in mythic+. Currently, there is not way to tell whether ox statue or a party member has aggro. Please implement this feature!

**Comment by Hemario** [comment]
+1
would also be amazing if Balance Druid Treants, Shaman's Earth Elemental, Monk's Niuzao, ... and optionally hunter and warlock pets could be treated as offtanks as well. I tend to panic when losing agro as a tank in m+ only to see that it was just a treant.

**Comment by kesava-wow** [comment]
Fixed with "compromise" - all player controlled NPCs will be treated as off-tanks. That seems to be the simplest way, since the API is terrible for this.
