### ISSUE TITLE
Enemy name plates not showing up after update

### ISSUE THREAD

**Issue by brianthedog90** [kesava-wow/kuinameplates2#252]
Did an update on 4/20/18 and after I did it I could not get enemy nameplates for other players to show up. I am alliance and no horde players have name plates. Was working earlier on 4/19/18 but now they will not pop up. I pushed V to turn them on and off and still nothing. Have done everything I can think off to get them to show up but so far nothing. hopefully this gets fixed soon.

**Comment by kesava-wow** [comment]
Nothing changed besides some config strings. The games' nameplate visibility settings are per-character - have you checked them? In general, check FAQs 1 and 2 here: https://www.curseforge.com/wow/addons/kuinameplates

(BTW you can still reply here when the issue is closed)
