### ISSUE TITLE
pixel correction and the case of the disappearing text

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#253]
As in: https://github.com/kesava-wow/kuinameplates2/commit/63110e7745c1c7785aa80ef1ba53a7d7ebee42b9

I'd rather not have to hide/show. Without hide/show the text disappears whenever a frame moves. SetPoint works better now (with the ignore ui scale option), but textures still jitter.

**Comment by kesava-wow** [comment]
during part of the legion beta the following was necessary to stop texture flashing:

/script releaseuitextures 0

something similar this time? beta only?

**Comment by kesava-wow** [comment]
stiiiiill happening on live

**Comment by InfusOnWoW** [comment]
From IRC:
"TSquare 21.09.2018
Tercioo: I think there is a "nounload" attribute for textures
I don't think it's used in our UI, so I'm not sure how well it works
a cursory scan appears that it should"

That attribute is xml only, but try asking whether they can make it available.

**Comment by kesava-wow** [comment]
No longer an issue in 8.1.
