### ISSUE TITLE
BfA initial load

### ISSUE THREAD

**Issue by jazz836062** [kesava-wow/kuinameplates2#254]
I receive the below error on the initial load of the BfA version of the addon.

Message: Interface\AddOns\Kui_Nameplates_PreLegion\create.lua:9: attempt to index local 'layout' (a nil value)
Time: Mon Apr 23 20:28:56 2018
Count: 1
Stack: Interface\AddOns\Kui_Nameplates_PreLegion\create.lua:9: attempt to index local 'layout' (a nil value)
Interface\AddOns\Kui_Nameplates_PreLegion\create.lua:9: in main chunk

Locals: folder = "Kui_Nameplates_PreLegion"
ns = <table> {
}
addon = <unnamed> {
 NAME_PLATE_UNIT_REMOVED = <function> defined @Interface\AddOns\Kui_Nameplates\addon.lua:67
 UI_SCALE_CHANGED = <function> defined @Interface\AddOns\Kui_Nameplates\addon.lua:88
 DispatchMessage = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:37
 uiscale = 0.71
 print = <function> defined @Interface\AddOns\Kui_Nameplates\addon.lua:39
 NewElement = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:415
 NewPlugin = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:378
 plugins = <table> {
 }
 GetPlugin = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:408
 NAME_PLATE_UNIT_ADDED = <function> defined @Interface\AddOns\Kui_Nameplates\addon.lua:54
 PLAYER_LEAVING_WORLD = <function> defined @Interface\AddOns\Kui_Nameplates\addon.lua:79
 debug = true
 layout = <table> {
 }
 Layout = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:423
 Frames = <function> defined @Interface\AddOns\Kui_Nameplates\addon.lua:43
 width = 140
 Nameplate = <table> {
 }
 NAME_PLATE_CREATED = <function> defined @Interface\AddOns\Kui_Nameplates\addon.lua:47
 MAJOR = 2
 0 = <userdata>
 height = 40
 MINOR = 2
 HookNameplate = <function> defined @Interface\AddOns\Kui_Nameplates\hook.lua:45
 debug_config = true
}
layout = nil
kui = <table> {
 table_to_string = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:46
 DebugPopup = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:345
 FADEFRAMES = <table> {
 }
 Pluralise = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:227
 frameFadeFrame = <unnamed> {
 }
 print = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:70
 frameFade = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:428
 ModifyFontFlags = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:151
 frameFadeRemoveFrame = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:365
 utf8sub = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:249
 GetUnitColour = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:106
 num = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:197
 GetClassColour = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:81
 frameIsFading = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:358
 CreateFontString = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:165
 FormatTime = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:211
 frameFadeOnUpdate = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:368
 UnitLevel = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:133
 UnitIsPet = <function> defined @Interface\AddOns\Kui_Nameplates\lib\Kui/Kui.lua:103
 m = <table> {
 }
}
MEDIA = "interface/addons/kui_nameplates_prelegion/media/"
SCALE = 1
(*temporary) = <function> defined @Interface\AddOns\Kui_Nameplates_PreLegion\create.lua:9
(*temporary) = "attempt to index local 'layout' (a nil value)"

**Comment by kesava-wow** [comment]
Disable or delete the Kui_Nameplates_PreLegion, _Example and _BarAuras folders.
