### ISSUE TITLE
[Feature Request] Cast name inside cast bar

### ISSUE THREAD

**Issue by jcadduono** [kesava-wow/kuinameplates2#257]
I like to use quite thick cast bars so I find that the cast name is unnecessarily using a lot of extra space underneath it, when I think it would be easier to read the cast name inside the bar for my use case.
Perhaps a V position modifier?

example of how inconvenient it is having it under (sorry, quite a large image):
https://puu.sh/Ab553/ae829d736b.jpg

this would help with reducing nameplateOverlapV as well (they dont have to be separated so far to not block cast names)

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/issues/237
