### ISSUE TITLE
auras.lua:571: TexCoord out of range

### ISSUE THREAD

**Issue by Rastaphasta** [kesava-wow/kuinameplates2#259]
Message: Interface\AddOns\Kui_Nameplates\elements/auras.lua:571: TexCoord out of range
Time: 05/04/18 14:59:13
Count: 2
Stack: Interface\AddOns\Kui_Nameplates\elements/auras.lua:571: TexCoord out of range
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: in function `SetTexCoord'
Interface\AddOns\Kui_Nameplates\elements/auras.lua:571: in function `SetIconSize'
Interface\AddOns\Kui_Nameplates_Core\create.lua:1268: in function <Interface\AddOns\Kui_Nameplates_Core\create.lua:1253>
Interface\AddOns\Kui_Nameplates_Core\create.lua:1280: in function `UpdateAuras'
Interface\AddOns\Kui_Nameplates_Core\create.lua:404: in function `UpdateFrameSize'
Interface\AddOns\Kui_Nameplates_Core\hook.lua:64: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:53: in function `DispatchMessage'
Interface\AddOns\Kui_Nameplates\nameplate.lua:75: in function `OnShow'
Interface\AddOns\Kui_Nameplates\nameplate.lua:69: in function `OnUnitAdded'
Interface\AddOns\Kui_Nameplates\addon.lua:64: in function `?'
Interface\AddOns\Kui_Nameplates\addon.lua:108: in function <Interface\AddOns\Kui_Nameplates\addon.lua:105>

Locals: errorMessage = "Interface\AddOns\Kui_Nameplates\elements/auras.lua:571: TexCoord out of range"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

**Comment by Rastaphasta** [comment]
I dont know what is causing this is seems random, im just flying around doing world quests and picking up herbs and i keep getting this error.

**Comment by kesava-wow** [comment]
what version are you using? (It's at the top right of /knp if you can load that).

It seems like another add-on is conflicting. Do you have any other nameplate add-ons enabled, KNP modifications that aren't from curse?

**Comment by Rastaphasta** [comment]
2.15.5

I am using elvui but the nameplates are disabled and no i do not have any other name plate add-ons

**Comment by kesava-wow** [comment]
Well, this is a local problem as far as I can see. Does it still happen if you disable everything except KNP? There's no hint in there as to what might be causing it.
