### ISSUE TITLE
[If this is relevant to you, please reply to let me know.] A large number of Lua errors related to health text: 638x Kui_Nameplates_Core\create.lua:726: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by BlueNightSky** [kesava-wow/kuinameplates2#260]
use version: beta-splendid-howling-boar
When it happens in a Instance.
Use new features: "Current + percent" and "Current + deficit" health text options.
seem to have no errors after switching back to the original blank and percentage.
(Sorry for my poor English)

638x Kui_Nameplates_Core\create.lua:726: attempt to concatenate a nil value
Kui_Nameplates_Core\create.lua:726: in function `?'
Kui_Nameplates_Core\create.lua:731: in function <Kui_Nameplates_Core\create.lua:728>
Kui_Nameplates_Core\create.lua:750: in function `UpdateHealthText'
Kui_Nameplates_Core\hook.lua:114: in function `func'
Kui_Nameplates\messages.lua:77: in function `DispatchMessage'
Kui_Nameplates\elements/healthbar.lua:95: in function `UpdateHealth'
Kui_Nameplates\elements/healthbar.lua:108: in function `func'
Kui_Nameplates\messages.lua:123: in function <Kui_Nameplates\messages.lua:88>

Locals:
InCombatSkipped

**Comment by kesava-wow** [comment]
Do you have Kui_Nameplates_Custom (or one of those scripts) or _Extras?

**Comment by BlueNightSky** [comment]
Do you have Kui_Nameplates_Custom (or one of those scripts) or _Extras?
NO, but have Kui_Enemy_Colors.
Any instance in particular?
This is true for many Instances. I haven't recorded it in detail. It should be all Instances.

**Comment by kesava-wow** [comment]
kaay, I can't reproduce this. Can you make sure it's still happening, and if it is, replace your Kui_Nameplates_Core/create.lua with this one: https://raw.githubusercontent.com/kesava-wow/kuinameplates2/issue/260/Kui_Nameplates_Core/create.lua, and see if that fixes it.

**Comment by BlueNightSky** [comment]
Have downloaded the latest beta, and replaced Kui_Nameplates_Core/create.lua, Wait until I'm free to instance test.

**Comment by BlueNightSky** [comment]
I have tested it in (Antorus, the Burning Throne)，No more large number errors, Only one error occurred.

1x Kui_Nameplates_Core\create.lua:732: attempt to concatenate a nil value
Kui_Nameplates_Core\create.lua:732: in function `?'
Kui_Nameplates_Core\create.lua:737: in function <Kui_Nameplates_Core\create.lua:734>
Kui_Nameplates_Core\create.lua:760: in function `UpdateHealthText'
Kui_Nameplates_Core\hook.lua:114: in function `func'
Kui_Nameplates\messages.lua:77: in function `DispatchMessage'
Kui_Nameplates\elements/healthbar.lua:95: in function `UpdateHealth'
Kui_Nameplates\elements/healthbar.lua:108: in function `func'
Kui_Nameplates\messages.lua:123: in function <Kui_Nameplates\messages.lua:88>

Locals:
InCombatSkipped

**Comment by kesava-wow** [comment]
That modification helped, but I still can't reproduce this regardless, even in antorus. As far as I can tell, something else is calling one of my frame's functions before it's ready. That ~should~ be the only way this is possible. Specifically, something is calling f.UpdateHealthText.

I know it's annoying to do this but can you test it with every addon disabled, leaving just Kui_Nameplates, Kui_Nameplates_Core and Kui_Nameplates_Core_Config enabled?

Thanks.

**Comment by BlueNightSky** [comment]
Already used to using various addons, It's a bit difficult now for me not to use addons, Especially in the instance.

Can only say that I try to do the test in the outdoor, Try to kill some mobs, When I'm more free.

Thank you for your response and corrected the problem. Although not 100% resolved, thank you!

**Comment by BlueNightSky** [comment]
I have already tested kill mobs outdoors and still have errors.
Only use the following addons:
!BugGrabber
BugSack
Bazooka
Kui_Nameplates
Kui_Nameplates_Core
Kui_Nameplates_Core_Config

version: 
beta-caring-spider-giggling-tiger
replaced Kui_Nameplates_Core/create.lua
Setting:
health_text_hostile_max = maximum
health_text_hostile_dmg = Current + percent
All friendly = Blank

The error is as follows:
2x Kui_Nameplates_Core\create.lua:731: attempt to concatenate a nil value
Kui_Nameplates_Core\create.lua:731: in function `?'
Kui_Nameplates_Core\create.lua:737: in function <Kui_Nameplates_Core\create.lua:734>
Kui_Nameplates_Core\create.lua:760: in function `UpdateHealthText'
Kui_Nameplates_Core\hook.lua:114: in function `func'
Kui_Nameplates\messages.lua:77: in function `DispatchMessage'
Kui_Nameplates\elements/healthbar.lua:95: in function `UpdateHealth'
Kui_Nameplates\elements/healthbar.lua:108: in function `func'
Kui_Nameplates\messages.lua:123: in function <Kui_Nameplates\messages.lua:88>

Locals:
InCombatSkipped

**Comment by kesava-wow** [comment]
Ok. I've updated the create.lua so it should stop all those errors for you: https://raw.githubusercontent.com/kesava-wow/kuinameplates2/issue/260/Kui_Nameplates_Core/create.lua

I still can't reproduce this (even on the zhTW and zhCN clients), don't understand how it could be happening, haven't had any other reports of it, and this is an inefficient workaround. So I don't want to put it in the main addon (which would then make finding the cause more difficult).

My only suggestion at this point would be to try making a new profile in KNP (and applying your health text settings of course) aand perhaps deleting all the KNP folders and re-installing it. Otherwise, I just need to wait for anyone else to report it so that I can try to work out what's happening.

Thanks.

**Comment by BlueNightSky** [comment]
Thank you very much for your efforts, I don't know how it happened. Maybe it's just my case.
I will continue to try. In short don't worry too much, thank you!

**Comment by BlueNightSky** [comment]
OMG! I reinstall the KNP and delete all profiles, then there is an error when logging in, the KNP instruction has no effect, and the options in the interface are completely invisible.

What happened? The error is as follows:

1x Kui_Nameplates_Core\config.lua:786: attempt to index global 'KuiNameplatesCoreSaved' (a nil value)
Kui_Nameplates_Core\config.lua:786: in function `InitialiseConfig'
Kui_Nameplates_Core\hook.lua:268: in function `Initialise'
Kui_Nameplates\addon.lua:149: in function <Kui_Nameplates\addon.lua:115>

Locals:
self = <table> {
 NameOnlyCombatUpdate = <function> defined @Kui_Nameplates_Core\create.lua:1843
 CreateNameOnlyGlow = <function> defined @Kui_Nameplates_Core\create.lua:1672
 AurasButton_SetFont = <function> defined @Kui_Nameplates_Core\create.lua:305
 LSMMediaRegistered = <function> defined @Kui_Nameplates_Core\create.lua:256
 NameOnlyUpdate = <function> defined @Kui_Nameplates_Core\create.lua:1851
 CreateAuras = <function> defined @Kui_Nameplates_Core\create.lua:1368
 LostTarget = <function> defined @Kui_Nameplates_Core\hook.lua:150
 layout = true
 Create = <function> defined @Kui_Nameplates_Core\hook.lua:32
 GainedTarget = <function> defined @Kui_Nameplates_Core\hook.lua:138
 CreateHighlight = <function> defined @Kui_Nameplates_Core\create.lua:405
 ShowNameUpdate = <function> defined @Kui_Nameplates_Core\create.lua:1609
 InitialiseElements = <function> defined @Kui_Nameplates_Core\create.lua:1871
 Auras_PostCreateAuraButton = <function> defined @Kui_Nameplates_Core\create.lua:1393
 HealthColourChange = <function> defined @Kui_Nameplates_Core\hook.lua:118
 CreateThreatBrackets = <function> defined @Kui_Nameplates_Core\create.lua:1582
 CreateGuildText = <function> defined @Kui_Nameplates_Core\create.lua:809
 CreateCastBar = <function> defined @Kui_Nameplates_Core\create.lua:1174
 NameOnlyHealthUpdate = <function> defined @Kui_Nameplates_Core\create.lua:1779
 SetAurasConfig = <function> defined @Kui_Nameplates_Core\create.lua:1454
 SetLocals = <function> defined @Kui_Nameplates_Core\create.lua:203
 CreateTargetGlow = <function> defined @Kui_Nameplates_Core\create.lua:959
 configChangedTextOffset = <function> defined @Kui_Nameplates_Core\create.lua:273
 configChangedFontOption = <function> defined @Kui_Nameplates_Core\create.lua:309
 CreateAbsorbBar = <function> defined @Kui_Nameplates_Core\create.lua:512
 ExecuteUpdate = <function> defined @Kui_Nameplates_Core\hook.lua:169
 CreateHealthBar = <function> defined @Kui_Nameplates_Core\create.lua:435
 HealthUpdate = <function> defined @Kui_Nameplates_Core\hook.lua:113
 RaidIconUpdate = <function> defined @Kui_Nameplates_Core\hook.lua:165
 CastBarHide = <function> defined @Kui_Nameplates_Core\hook.lua:135
 NameOnlySetNameTextToHealth = <function> defined @Kui_Nameplates_Core\create.lua:1762
 ClassificationChanged = <function> defined @Kui_Nameplates_Core\hook.lua:162
 configChangedTargetArrows = <function> defined @Kui_Nameplates_Core\create.lua:286
 Hide = <function> defined @Kui_Nameplates_Core\hook.lua:105
 CreateFrameGlow = <function> defined @Kui_Nameplates_Core\create.lua:926
 CreateLevelText = <function> defined @Kui_Nameplates_Core\create.lua:707
 configChangedAbsorb = <function> defined @Kui_Nameplates_Core\create.lua:479
 GlowColourChange = <function> defined @Kui_Nameplates_Core\hook.lua:128
 configChangedCombatAction = <function> defined @Kui_Nameplates_Core\create.lua:298
 CreateBackground = <function> defined @Kui_Nameplates_Core\create.lua:396
 Initialise = <function> defined @Kui_Nameplates_Core\hook.lua:267
 InitialiseConfig = <function> defined @Kui_Nameplates_Core\config.lua:784
 CreateTargetArrows = <function> defined @Kui_Nameplates_Core\create.lua:985
 NameOnlyUpdateFunctions = <function> defined @Kui_Nameplates_Core\create.lua:1687
 CreateStateIcon = <function> defined @Kui_Nameplates_Core\create.lua:1280
 SetBarAnimat

**Comment by kesava-wow** [comment]
Oh whoops, that's my fault. The latest stable release should work - I'll
fix the beta next time I'm at my computer.

Thanks.

**Comment by kesava-wow** [comment]
Fixed that in beta-beaming-snake-caring-puppy.

**Comment by BlueNightSky** [comment]
I installed the beta-beaming-snake-caring-puppy, and replaced Kui_Nameplates_Core/create.lua
Into a Instance test (Mythic+), no more errors. maybe it's also possible that I reinstall and delete all profiles.
Thank you for your help !

**Comment by kesava-wow** [comment]
I'm relatively sure this is no longer an issue.
