### ISSUE TITLE
buffs on enemies / debuffs on friends

### ISSUE THREAD

**Issue by YunusY** [kesava-wow/kuinameplates2#267]
I am surprised that this is not already implemented in such a famous nameplate addon. Maybe Im too stupid to find it?

The ideal case would be buffs and debuffs growing from different sides and each having a different configurable rowwidth (or icons per row).

This feature is essential for any class who has to dispel anything.

**Comment by YunusY** [comment]
are you planning on adding this feature and if yes when do you think can you do that? depending on that i will need to look at other options

**Comment by kesava-wow** [comment]
yes, and no idea. I do this as a hobby.

**Comment by Gabb1995** [comment]
I agree this would be a great addition, being able to know if I can dispell a buff on enemy is very needed!

**Comment by Yama1291** [comment]
Thank you for all your work on this addon, I use it exclusively.
I came here to request the same feature as the OP.
Cheers!

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/0c154fedd3e2cf20a84b9907ba2d3c03e8736c3d
