### ISSUE TITLE
Vampiric Touch

### ISSUE THREAD

**Issue by Darkpriestx** [kesava-wow/kuinameplates2#27]
After the re-imposition of a vampire touches on the same goal, is no longer displayed on the strip debuff hp

**Comment by kesava-wow** [comment]
Vampiric touch -should- be tracked, it's in the whitelist, but there might be multiple spell IDs for it. Do you have any talents or something which modify it?

**Comment by Darkpriestx** [comment]
I can make a video

**Comment by Darkpriestx** [comment]
the same problem and the ability to Agony

**Comment by Darkpriestx** [comment]
https://youtu.be/NnLBrRbbZ-4
