### ISSUE TITLE
Class Power glow persists after arena/BG ending

### ISSUE THREAD

**Issue by mazzy12** [kesava-wow/kuinameplates2#271]
Only fixed with a /reload, happens regardless of whether or not your class power is full when the game ends. Stacks on top of each other, so if you leave it long enough without a /reload, you end up with a rather blinding glow around the border of your class power. Have only tested with Rogue, but I imagine it's the same with Chi, etc.

**Comment by kesava-wow** [comment]
Thanks - Were you using the beta (of KNP) or release?

**Comment by mazzy12** [comment]
This was on Live, 7.3.5, with the latest version from the Twitch client.

**Comment by mazzy12** [comment]
Appears to be fixed as of BFA.
