### ISSUE TITLE
Issue on Load with BFA

### ISSUE THREAD

**Issue by gunner007cd** [kesava-wow/kuinameplates2#272]
Not sure this is the right place, but using the "beta-hidden-beard-bathing-dik-dik" release on current beta. (saw a few post about a beta build working) - however get the following error on load and addon does not seem to load.

Message: Interface\AddOns\Kui_Nameplates\messages.lua:268: Attempt to register unknown event "UNIT_POWER"
Time: Sun Jul  8 19:47:47 2018
Count: 1
Stack: Interface\AddOns\Kui_Nameplates\messages.lua:268: Attempt to register unknown event "UNIT_POWER"
[C]: in function `RegisterEvent'
Interface\AddOns\Kui_Nameplates\messages.lua:268: in function `RegisterEvent'
Interface\AddOns\Kui_Nameplates\messages.lua:271: in function `RegisterUnitEvent'
...nterface\AddOns\Kui_Nameplates\elements/powerbar.lua:79: in function `OnEnable'
Interface\AddOns\Kui_Nameplates\messages.lua:408: in function `Enable'
Interface\AddOns\Kui_Nameplates\addon.lua:143: in function <Interface\AddOns\Kui_Nameplates\addon.lua:115>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "UNIT_POWER"

If you need more info, please let me know - Thanks.

Also, this is with KNP being the only addon loaded.
If there isn't a BFA compatible addon - sorry for my idiocy :)

**Comment by gunner007cd** [comment]
My guess is that UNIT_POWER was replaced with UNIT_POWER_UPDATE.

**Comment by kesava-wow** [comment]
Manually install this version for BFA support: https://github.com/kesava-wow/kuinameplates2/tree/bfa. The beta versions on Curse/Twitch are KNP's own betas - it's not referring to wow.
