### ISSUE TITLE
Nameplate buffs/debuffs not showing

### ISSUE THREAD

**Issue by mLgz0rn** [kesava-wow/kuinameplates2#274]
After the recent update the buff/debuffs used on the nameplates is not showing anymore, only 1 blank/green box shows up with some weird numbers, dunno if its the spell id's it shows.

**Comment by kesava-wow** [comment]
Refer to my comment on the curse page (the one in large, bold text).

**Comment by mLgz0rn** [comment]
aaah Sorry xD can't believe I didnt see that.
What is the latest release called that's not prepatch?
Best regards

**Comment by kesava-wow** [comment]
It's this one: https://wow.curseforge.com/projects/kuinameplates/files/2559812

**Comment by mLgz0rn** [comment]
Alright, thanks mate! 
And again, sorry :p
