### ISSUE TITLE
[feature request] glow/highlight on mouseover

### ISSUE THREAD

**Issue by Araiia** [kesava-wow/kuinameplates2#275]
Currently the only indication of mouseover is a slightly brighter health bar, which is difficult to see and is not shown in name-only mode. I'd like to request better visual indicators of which nameplate I'm mousing over:

1. option to use the "target glow" on mouseover
2. option(s) that are visible in name-only mode (highlight, opacity change, color change, glow, ..anything!)

**Comment by kesava-wow** [comment]
Both good ideas. Thanks.

**Comment by kesava-wow** [comment]
mouseover glow + avoid fade mouseover options added.
