### ISSUE TITLE
2.16a Not Working For Pre-Patch

### ISSUE THREAD

**Issue by Averfing** [kesava-wow/kuinameplates2#276]
I have updated to the latest release and it does not seem to be altering the nameplates. I have looked in the settings and can't find anything wrong with them. I have tried defaulting them and downloading the whole add-on again. I have the nameplates on but they are vanilla. The game says its the right version as does the twitch client and i checked by downloading off of the site in case it was twitch's fault. I would love help with this as I love this add-on. Swatter is also not throwing me any errors.

**Comment by kesava-wow** [comment]
Can you post a screenshot of both: the configuration interface (/knp); and your target's nameplate (I.e. target an enemy, and screenshot its nameplate)

**Comment by Averfing** [comment]
I will do that as soon as the servers let me on
