### ISSUE TITLE
[Bug] Player Cast Bar doesn't (always) show Soothing Mist channel

### ISSUE THREAD

**Issue by klaxce** [kesava-wow/kuinameplates2#277]
Mistweaver Monk: Player Cast Bar (on PRD) doesn't (always) show Soothing Mist channel. After the 8.0 pre-patch, KUI very rarely it shows the channel of Soothing Mists, but most of the time it just doesn't show it. Blizzard castbar shows the channel, as well as other addons/WA when KUI isn't. Other spell casts show just fine. I reset all settings/profile/saved variables/etc and was unable to make any improvements or changes to Soothing Mist's channel visibility.

Experienced in versions 2.16a and beta-walking-zebra-beaming-lion

**Comment by kesava-wow** [comment]
Will be related to: https://github.com/kesava-wow/kuinameplates2/issues/283
