### ISSUE TITLE
Death Knight Runes not displaying properly

### ISSUE THREAD

**Issue by Aniolora** [kesava-wow/kuinameplates2#278]
I have noticed an issue with "Show class resources" on target for Death Knight runes in version 2.16a. When all are full they show the correct amount, but in use an inaccurate amount is shown. For example you have 3 full runes but on target it only shows you having 1 full rune. Issue seems to appear when you hit 0 runes, then 1 refill but the rest do not even though you continue to gain runes.

Thank you for an amazing addon regardless.

**Comment by kesava-wow** [comment]
It is filling them correctly (as far as I can tell) but it's not changing them out of the inactive colour once they're filled. In the meantime you can make it more obvious by changing the "inactive colour" under /knp > class powers to something brighter.

Thanks.

**Comment by Aniolora** [comment]
Thank you for your reply, you are correct and that "fixed" the issue as far as I am concerned. Again thank you for all the effort you obviously puts into this addon, could not imagine playing without it!
