### ISSUE TITLE
Double Nameplates

### ISSUE THREAD

**Issue by Justhelpme** [kesava-wow/kuinameplates2#279]
There's two nameplates when I use Kui. Both the default nameplates and Kui. How do I fix this?

**Comment by kesava-wow** [comment]
That implies that you have another nameplate add-on enabled. Can you post a screenshot?

**Comment by cannadis18** [comment]
![double_nameplate](https://user-images.githubusercontent.com/41389791/42899841-89b75a50-8ac7-11e8-9bd1-4c2f67703218.JPG)

I think he mean this... Got the problem too.

**Comment by stimsong** [comment]
Ya, it's SpartanUI. I had exactly the same problem and just looked and found that SpartanUI has added namplates. Click on Modules and de-select nameplates and kui will be the only one on.
