### ISSUE TITLE
Nameplate of target disappearing in raids and dungeons

### ISSUE THREAD

**Issue by koicartel** [kesava-wow/kuinameplates2#281]
If I target someone, their nameplate and name disappears; there's nothing above them. It doesn't seem to happen only in raid groups (eg outside of an instance), I have to be in an actual raid for this to happen. The same happens with dungeons. I reset the settings to defaults and this is still the case, and has been happening for about 2 weeks I think. It also happens to NPC plates.

Thanks for the help!

**Comment by kesava-wow** [comment]
Answered on curse
