### ISSUE TITLE
Sometimes castbar gets hidden during the cast of hostile units

### ISSUE THREAD

**Issue by Weeeqt** [kesava-wow/kuinameplates2#283]
Here is twitch clip which demonstrates the issue: https://clips.twitch.tv/BombasticEmpathicWitchHotPokket
Please take a look at druid. He appears from stealth casting Cyclone and Kui, Gladius and Quartz picked up the cast just fine, but then a moment later Kui castbar disappears under the nameplate, even though Gladius and Quartz are just fine. Few moments later druid is casting some heals and they bug out the same way. I even interrupt one of them after the castbar disappeared.

It is very confusing because it makes me think that player is fake-casting.

**Comment by Weeeqt** [comment]
Maybe it happens because of spell pushback? When druid gets hit by the pet and his cast progress gets pushed back.

**Comment by kesava-wow** [comment]
Thanks

**Comment by kesava-wow** [comment]
So I did actually fix other instances of that function call.. but I forgot about the extra underscore in this one. whoops.

**Comment by klaxce** [comment]
In my light testing so far, the latest Alpha build appears to have fixed this bug in regards to Soothing Mist. Thank you so much
