### ISSUE TITLE
Friendly NPC Nameplates are blocking quest icon when zoomed out

### ISSUE THREAD

**Issue by jtam11** [kesava-wow/kuinameplates2#284]
I'm having a small issue with quest givers' icons being blocked by their nameplate if I'm zoomed out. It's just a slight inconvenience having to zoom in to see who the quest givers are, but it would be nice to somehow have the icons always shown above the nameplate.

Screenshots:

Zoomed In:
![zoomed_in](https://user-images.githubusercontent.com/16862252/43044770-9fe2c9d0-8d61-11e8-8bd2-75bd70d7fa76.jpg)

Zoomed Out:
![zoomed_out](https://user-images.githubusercontent.com/16862252/43044769-9fca7d58-8d61-11e8-89b3-269ae234e0be.jpg)

**Comment by kesava-wow** [comment]
This is a blizzard issue. Nameplates can't be moved by addons (without breaking the click-box), neither can the in-world markers.

Somewhat relevant: https://github.com/kesava-wow/kuinameplates2/issues/171
