### ISSUE TITLE
Current things

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#287]
(This is a persistent personal to-do list in no particular order)

Castbar
---
- [ ] toggling during animation desyncs spell icon alpha
- [ ] detach: (icon overlaid) limit height to aspect ratio
- [x] detach: option to match health bar length

Auras
---
- [x] Font sizes
- [x] toggle display on minor
- [x] personal / friendly / hostile toggles
- [ ] checkbox for vanilla text / omnicc ?
- [ ] needs a clean
- [ ] different side on personal frame
- [ ] mythicplus integration?

Threat page
---
- [x] allow changing threat colours
- [ ] improve distinction between threat glow and tank mode

Misc
---
- [x] #251
- [x] #269
- [x] option to disable "minor" nameplates
- [ ] borrow the "new option" exclamation points
- [ ] Fade out of combat (only while in combat?)
- [ ] name-only tapped colour (option?)
- [ ] auto profile switching #231

**Comment by isuckatscripting** [comment]
Thank you! I would love font sizes to be added, unless you already added it. Appreciate it man!
