### ISSUE TITLE
Separate enablers for nameplate auras

### ISSUE THREAD

**Issue by xface2face** [kesava-wow/kuinameplates2#290]
Having separate buttons to enable auras in personal/friendly/hostile nameplates would be nice. It might be easier to implement than adding debuffs to friendly/buffs to enemy plates. I like a lot of kui features (including personal resource display auras), but would also like to have a separate addon to track auras on enemy plates, and this could be a makeshift solution.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/issues/159

**Comment by kesava-wow** [comment]
You can still post on closed issues.
