### ISSUE TITLE
[Feature Request] Questig

### ISSUE THREAD

**Issue by xxchuoxx** [kesava-wow/kuinameplates2#292]
Is there a posibility to add a function that let us see in nameplate that enemy npcs are of this quest, or this option already exist?, maybe adding an exclamation mark above the npc nameplate or that the addon mark the npcs with another color the nameplate.

**Comment by kesava-wow** [comment]
https://www.curseforge.com/wow/addons/questplates should work acceptably with KNP. Adding something similar in KNP is tracked here: https://github.com/kesava-wow/kuinameplates2/issues/171
