### ISSUE TITLE
[Request] Colored Nameplates for a specific buff

### ISSUE THREAD

**Issue by trashlord5** [kesava-wow/kuinameplates2#293]
Hello,

we need colored nameplates for a specific buff , for example "infested" in m+
I found colored nameplates by name with a plugin, but it would be great if we get some more options.

(Plugin: KuiEnemyColors"

Kind Regards,

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates-customs/issues/2
