### ISSUE TITLE
Healing absorbs error

### ISSUE THREAD

**Issue by ksh1983** [kesava-wow/kuinameplates2#295]
https://github.com/kesava-wow/kuinameplates2/issues/288

I saw the link but Healing absorbs does not work

ex) necrotic strike

**Comment by kesava-wow** [comment]
That issue is just tracking the request - it's not implemented.

**Comment by ksh1983** [comment]
Do you plan to add it?

**Comment by ksh1983** [comment]
I'm playing DK, but necrotic strike does not show up in the heath bar.

Do you plan to add it?

I'm always thankful. ty
