### ISSUE TITLE
Massive Frame Loss in BfA with KuiNameplates & LunaEclipse Rotation Helper

### ISSUE THREAD

**Issue by suzumebachi** [kesava-wow/kuinameplates2#297]
There's some really strange behavior going on with KuiNameplates as of the most recent update (2.16.4) and the BfA launch.

For one thing there seems to be a bug with the default nameplate frames, or possibly another addon, that keeps resetting the "Always Show Nameplates" setting in the default interface options. This causes some very strange behavior with KuiNameplates, like nameplates not showing when they're supposed to or disappearing altogether.

Second, and more importantly, whenever entering combat with KuiNameplates enabled, framerate drops by as much as 50%. Have confirmed KuiNameplates to be the culprit here, because this does not happen when it's disabled or not installed.

**Comment by suzumebachi** [comment]
I figured out what's happening. You can disregard this, but I'll leave this up here in case anyone else is having issues.

The problem is caused by LunaEclipse Rotation Helper, which used to be just a collection of WeakAuras and/or Ovale settings, but is now a full fledged addon. If you had it previously installed via Curse/Twitch it will have automatically upgraded itself.

That's all well and good, the problem is that the new LunaEclipse relies on nameplates to do its thing, and as such overrides all nameplate settings in the default UI, as well as fights other nameplates for dominance, hence the frame loss.

Disable or delete it and you're good to go.

**Comment by kesava-wow** [comment]
Thanks. I assume it's trying to force the default nameplates to display, causing a loop if something else tries to keep them hidden. That shouldn't be necessary. Information about nameplate units is available whether or not the default nameplate is visible.
