### ISSUE TITLE
Name fonts not working

### ISSUE THREAD

**Issue by sponkster** [kesava-wow/kuinameplates2#298]
i have difficult reading the standart name fonts of wow, i thought kuinameplates changed that. cant seen to change then though. ( im using elvui also if thats something )

![image](https://user-images.githubusercontent.com/42449007/44227152-4caee080-a168-11e8-8413-414d3011bbeb.png)

**Comment by kesava-wow** [comment]
Those aren't nameplates, and the font can be modified by changing files, however the size can't be increased. They can't be changed by addons.

However, you can make the game render nameplates for them - check the "always show friendly NPCs" option under /knp cvars. That will make the game render nameplates for all friendly NPCs, which KNP then modifies.
