### ISSUE TITLE
Update execute abilities for BFA

### ISSUE THREAD

**Issue by Mageee** [kesava-wow/kuinameplates2#299]
On a warrior, while using the massacre talent my execute range is 35%, however with Auto-detect range option selected it still shows at 20%

**Comment by kesava-wow** [comment]
Thanks - I need to update the list for bfa.

**Comment by d87** [comment]
I made this patch for executes during beta
https://www.dropbox.com/s/n308jomjaxw8yeg/kui_plugins_execute.patch

maybe it'll be useful

**Comment by kesava-wow** [comment]
Finished by PRs, I believe
