### ISSUE TITLE
Last update, new error

### ISSUE THREAD

**Issue by meawke** [kesava-wow/kuinameplates2#300]
hello in last update i have error anytime

> Date: 2018-08-21 10:25:12
> ID: 1
> Error occured in: Global
> Count: 1
> Message: ..\AddOns\Kui_Nameplates_Core\create.lua line 1435:
>    'then' expected near 'self'
> Debug:
>    
> Locals:
> 
> AddOns:
>   Swatter, v7.5.5724 (TasmanianThylacine)
>   Auctionator, v5.0.4
>   BagBrother, v
>   Bagnon, v8.0.2
>   Bartender4, v4.8.1
>   DBMCore, v@project-version@
>   DBMDefaultSkin, v
>   DBMStatusBarTimers, v
>   GatherMate2, v1.43
>   HeroCache, v8.0.1.06
>   HeroLib, v8.0.1.06
>   HeroRotation, v8.0.1.06
>   KuiMedia, v
>   KuiNameplates, v
>   KuiNameplatesCore, v
>   BlizRuntimeLib_ruRU v8.0.1.80000 <none>
>   (ck=17d)

**Comment by kesava-wow** [comment]
yup, it was untested. You'll get that with the alpha sometimes.
