### ISSUE TITLE
Icon on nameplates for quest givers/quest turn-ins.

### ISSUE THREAD

**Issue by CMcFadyen** [kesava-wow/kuinameplates2#303]
Because #284 can't be controlled by KNP, could icons be added to KNP if they have an available quest, a completed quest, or a repeatable quest?  And maybe an incomplete quest too, though I wouldn't personally use that.  Is there even an API to check if an NPC has quests for the player?

**Comment by kesava-wow** [comment]
There isn't an API for it; it's pretty annoying to check for. Hence, it's not already included.

Duplicate: https://github.com/kesava-wow/kuinameplates2/issues/171

Thanks.
