### ISSUE TITLE
I Don't Understand at all

### ISSUE THREAD

**Issue by Whynohorn** [kesava-wow/kuinameplates2#304]
Hello,

First of all ty for all the work you do.

I have an issue and the issue is i can't even make the mod work, i did everything you say on README but nothing is changing in game it's driving me absolutly crazy it's been 5hours to find out what's wrong about it i can't find... I also might not understand the way i have to configurate the mod . In game or with the LUA file ? i'm lost i have no more options could you help me plz?

I'm looking for the aura mod, i need the CD number on the buff or debuff bigger and centered with the aura icon. That's it but i find really weird such text option are not available on the main addon set...

Could you help me plz? i'm desperate. Thank you in advance!

Mat

**Comment by kesava-wow** [comment]
What's the actual problem - can you not get KuiNameplates to work at all, or do you just want help getting the simple-aura-mods script working?

**Comment by Whynohorn** [comment]
Hey thank you for answering, i can't get Kui Name Plates Custom work, i see it in addons like you told us to check on and it even says in game that i use a custom version of KuiNP and it's not linked with curse for update

**Comment by kesava-wow** [comment]
Ok. I'll make a zip for you with those options enabled in a second.

**Comment by Whynohorn** [comment]
Very kind of you sir

**Comment by kesava-wow** [comment]
[Kui_Nameplates_Custom.zip](https://github.com/kesava-wow/kuinameplates2/files/2320890/Kui_Nameplates_Custom.zip)

That's got the script installed and set up to centre aura cooldown text and increase the text size by 2 "points". To change that, edit the custom.lua file with an editor that works in plain-text (like Notepad on windows).
For example, to increase the size of CD text, open custom.lua, and look for the "local CD_TEXT_SIZE_MOD = 2" line near the top. Change that final 2 to whatever you want and reload the interface.

Fully restart the game when you install a new addon. If you're modifying existing files, you can just reload the interface by typing: /run ReloadUI()

**Comment by Whynohorn** [comment]
Ok thank you very much i'll try and let you know if it worked

**Comment by Whynohorn** [comment]
It's working thanks alot !!!
