### ISSUE TITLE
Quest icons

### ISSUE THREAD

**Issue by VaporAPX** [kesava-wow/kuinameplates2#305]
Threat plates does this, and I love the feature, but I hate that mod.  Would very much prefer to keep using KUI (best one hands down :))  Any chance you can add quest icons to the name plates to mobs you have quests for?   

Much appreciated, great addon, have been using it forever!

**Comment by VaporAPX** [comment]
Can't seem to change the label to request, it's def not a bug :)

**Comment by kesava-wow** [comment]
Duplicate: https://github.com/kesava-wow/kuinameplates2/issues/171 (also links to another add-on which can be used alongside knp - though I agree it probably doesn't look consistent).

See also: #303

Thanks.
