### ISSUE TITLE
2.17 Target Arrows

### ISSUE THREAD

**Issue by ekenberg** [kesava-wow/kuinameplates2#307]
Target arrows in 2.17 look different from previous versions. I prefer the old look, it is visually clearer to me. Could you pretty please add an option to use the old look?

**Comment by BuurmanDeBuurman** [comment]
I agree, this feature is absolutely horrendous. Please give us back the old visuals for target arrows.

**Comment by Aur0r4** [comment]
Oh yes, please add this option, would be really nice.

**Comment by ekenberg** [comment]
Currently I've stayed on 2.16.4 because of this. I understand the will to make it look pretty but the new look doesn't work for me - in a larger pack of mobs I can't even see it. The older arrows might be less pretty but they are visually clear.

Is it a simple matter of some image file which I could overwrite after upgrading to say 2.17.*? Or are there other internal changes? It would be nice to follow new upgrades and if it's just some file to overwrite after upgrade I can accept doing that manually for the time being.

Of course, the nicest solution would be to have a selection of arrows to choose from in the configuration UI.

Thank you for your hard work on KUI, it's very much appreciated!

**Comment by kesava-wow** [comment]
@ekenberg As I commented here: https://github.com/kesava-wow/kuinameplates2/issues/312#issuecomment-417827847

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates-customs/raw/master/Kui_Nameplates_OldTextures.zip

**Comment by ekenberg** [comment]
Thank you for the OldTextures addon, it works nicely and is still, at least for me, a lot easier to see than the new fancy target arrows :)
Will you be putting this on Curse/Twitch for automatic updates?
Thanks again for KUI, couldn't play without it!

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/04eb61eac6cd912a06dddc0795fd607dfafdddc2

**Comment by Aur0r4** [comment]
can we get this to work for wow classic?
I get this error:

```
4x Kui_Nameplates\messages.lua:536: Ignoring out of date plugin: `OldTextures`
[C]: in function `error'
Kui_Nameplates\messages.lua:536: in function `NewPlugin'
Kui_Nameplates_OldTextures\custom-Benutzer.lua:4: in main chunk

Locals:
(*temporary) = "Ignoring out of date plugin: `OldTextures`"
```

**Comment by Aur0r4** [comment]
Got the same error in retail WoW but was able to fix it:

edited Kui_Nameplates_OldTextures.toc:
Line 1 `## Interface: 80205`

and edited custom.lua
Line 4 `local mod = addon:NewPlugin('OldTextures',101,5)`

Haven't tested it with wow classic yet.


Aur0r4
