### ISSUE TITLE
duplicate plates; unable to hide default blizz nameplates

### ISSUE THREAD

**Issue by ayylmao69420** [kesava-wow/kuinameplates2#309]
as the title states, i'm seeing both the default nameplates and the addon's nameplates
![](https://i.gyazo.com/2ab1f766bfeb90dc40a521dabba0a456.jpg)

![](https://i.gyazo.com/4d3a79070592e5f9367ab610ebe993ba.png)

I've tried deleting the wtf folder and reinstalling addons one by one. Tried disabling nameplates in the blizz UI but it removed both. I'm not using elvUI or tidyplates.

**Comment by kesava-wow** [comment]
Those aren't the default nameplates; you have another nameplate add-on enabled. Compilations like Elv or Spartan might have their own nameplate module which you need to disable in their settings.
