### ISSUE TITLE
Profile bug?

### ISSUE THREAD

**Issue by Davinnah** [kesava-wow/kuinameplates2#31]
Since the pre-patch, I have been encountering an error.  I have a profile with my saved settings.  If I log out or reload ui, I have to got to settings and toggle to default profile then back for my nameplates to work as I have set up.

Let me know if you need any more information, I'd be glad to provide it to you.

**Comment by kesava-wow** [comment]
Any particular setting, or all of them?

**Comment by kesava-wow** [comment]
Closing due to lack of info (also because I think it was probably fixed)

**Comment by Davinnah** [comment]
I apologize, I'm new to github.  I thought responding to the notification email would get back to you.  

I re-installed all my addons yesterday and this glitch is still there.  For me the issue is that in transition to combat, the texture of the target's health does not change to the bar "style".  So the threat brackets, target color, do not appear either.  I tried having just the default setting, but that did not correct the problem.  The "easiest" way for me to correct is by toggling profiles.  After that it is good until i switch characters or reload UI.  

Let me know if you need any other information

**Comment by kesava-wow** [comment]
Can you take before and after screenshots for me? Thanks.

**Comment by Davinnah** [comment]
![combat nameplate after toggle](https://cloud.githubusercontent.com/assets/20591093/17196005/2a04ea92-5427-11e6-8c35-1cbc82dfb2d9.jpg)
![back to profile 1](https://cloud.githubusercontent.com/assets/20591093/17196008/2a075296-5427-11e6-8438-bd0dc196cca4.jpg)
![default](https://cloud.githubusercontent.com/assets/20591093/17196004/2a0499f2-5427-11e6-9390-8e45924df5f0.jpg)
![profile 1](https://cloud.githubusercontent.com/assets/20591093/17196007/2a06a896-5427-11e6-89cc-f39330d980bf.jpg)
![combat nameplate before toggle profile](https://cloud.githubusercontent.com/assets/20591093/17196006/2a05b940-5427-11e6-881e-216bfff9f8b8.jpg)


Hope these help

**Comment by kesava-wow** [comment]
That first screenshot looks like a standard blizzard floating name rather than a nameplate.

Not entirely sure why that would be but I don't alter nameplate visibility other than for the "combat action" options.

Basically I have no idea what's going on there. Do they perhaps show if you use the keybinds? (V, etc, by default)
