### ISSUE TITLE
anyway to change color of nameplate to specific unit

### ISSUE THREAD

**Issue by eQuara** [kesava-wow/kuinameplates2#313]
like in dg some mobs are more important is there anyway to change color or anything about some mobs?

**Comment by d87** [comment]
Second this, would be nice if you could expand KuiSpellList to associate npc ids with color for default health. npc IDs can be parsed from GUIDs

**Comment by kesava-wow** [comment]
This custom script can change the bar colour of the mobs named in the table: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.name-and-target-colour.lua

As an example, by default it makes "Meredil Glider"  pure red (r,g,b = 1,0,0) and "Fel Explosives"... purple? (r,g,b = 1,0,1). You can just change those names/numbers, as long as you don't remove any quote marks, etc.

I realise it's not the most user-friendly, but customs are where I put this sort of extensive customisation, until I either come up with a nice way of integrating it, or enough people ask for it.

**Comment by wwbrandon** [comment]
I totally 3rd this! However, I will try your method here first.

I always vote KUI but really wish it had capability to change colors. For example I think Explosives are much easier to spot when a different color. Or the best Schism target per pull in M+ standing out with a color. Or even debuff tracking..... Happy to support any way I can

**Comment by Stanzilla** [comment]
There is https://www.curseforge.com/wow/addons/kuinameplates-target-helper as well now

**Comment by wwbrandon** [comment]
Life changing thanks

**Comment by wwbrandon** [comment]
Life changing thanks! I see the "Class Aura" tracking but says doesn't support Discipline. D:
Would be amazing to track my Soulglow Spectrometer
