### ISSUE TITLE
(Feature Suggestion) Nameplate fade based on Line of Sight

### ISSUE THREAD

**Issue by TrueShale** [kesava-wow/kuinameplates2#316]
Default nameplates have the ability to fade based on whether they are in your characters direct line of sight. I would love to see such an option in this addon as well.

**Comment by kesava-wow** [comment]
In terms of performance impact, it's non-trivial to provide both this and the other custom fade rules, as the API doesn't give enough information or ability for us to efficientlyg reimplement it. That goes for the distance fading, too.

For that reason I don't want to put it in core, but you can find a custom script for it here: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.los-fade.lua
