### ISSUE TITLE
Health text not showing for certain mobs

### ISSUE THREAD

**Issue by Dimdansum** [kesava-wow/kuinameplates2#317]
![image](https://user-images.githubusercontent.com/42922133/44964509-f4653600-aefe-11e8-8dfb-f20190a3130f.png)

Been seeing mobs where health text doesn't show. Is this is option or a bug?

**Comment by kesava-wow** [comment]
Those mobs are flagged as "minus" by the game, meaning they have significantly lower health, they're likely grouped up, and they have smaller nameplates by default.  So yes, it's a feature.

**Comment by Dimdansum** [comment]
Is it possible for you to add that option? It would really be nice to see the health left on some "minus" mobs that are in the game and do have a significant amount of hp.
