### ISSUE TITLE
Bar Auras Support

### ISSUE THREAD

**Issue by hiramloram** [kesava-wow/kuinameplates2#318]
I've been using one of your custom lua plugins called "BarAuras" to use bars instead of icons to track auras on enemies.  This custom works with kuinameplates2 up to version 2.16.

With version 2.17 I get an "out of date addon" error because of a variable called "max_minor".    I see you've added "max_minor" to your custom luas on kuinameplates-customs but I don't see a "BarAuras" custom there.  I don't see bar auras as an option in baseline kuinameplates2.  Are bar auras still implemented?

**Comment by kesava-wow** [comment]
I moved it to its own repository: https://github.com/kesava-wow/kuinameplates-barauras

I haven't checked if it's working on 2.17 yet though, so it'll still give you that error.
