### ISSUE TITLE
Can't disable pet bars

### ISSUE THREAD

**Issue by NiklasDL** [kesava-wow/kuinameplates2#319]
Even though they're disabled in standard blizzard interface, they won't go off.
Really annoying in arena vs bm zoo + enhancer. Can't see anything.
All CVars won't help either:
/run SetCVar("nameplateShowEnemyPets", 0)
/run SetCVar("nameplateShowEnemyGuardians", 0)
/run SetCVar("nameplateShowEnemyTotems", 0)
.. and without kui nameplates I don't have the issue.
Any idea how to fix it?

**Comment by kesava-wow** [comment]
If the vanilla nameplates are rendering for something, then so will KNP, and vice versa - All KNP does is change the appearance of nameplates. It doesn't (and can't, correctly) show or hide them arbitrarily. So if those cvars aren't hiding them, then they're either affected by a different cvar, or there just isn't a way to turn them off.

I don't know off by heart which cvars might help, but you can use AdvancedInterfaceOptions' cvar browser to find a complete list (search "nameplateshow").

(you can still reply to closed issues)
