### ISSUE TITLE
Debuffs on the personal frame

### ISSUE THREAD

**Issue by jokullion** [kesava-wow/kuinameplates2#324]
Set AURAS select TOP ,debuff on the nameplate,personal buff on the personal resources bar
select bottom,debuff under the nameplate,personal buff under the personal resources bar 
so how to make debuff on the nameplate and personal buff under the personal resources bar ?
I'm sorry that my Enlish is not so good
I hope you can understand my means

**Comment by kesava-wow** [comment]
I'm not sure I understand.

If you want to also see debuffs on the personal frame, that's not possible at the moment. The aura frame shows buffs on friends and debuffs on enemies. Enemies also show purgable debuffs in a different frame - it can't be set to show anything specific.

If you just want the aura frames to be on the bottom of all nameplates, setting it to "bottom" should do that.
If, however, you want buffs on the personal nameplate to show on a different side than the other nameplates, that's not possible, but it's something I could add easily enough.

**Comment by kesava-wow** [comment]
Duplicate: #106
