### ISSUE TITLE
Change color of enemy nameplate based on debuff

### ISSUE THREAD

**Issue by Dystrance** [kesava-wow/kuinameplates2#329]
Is it possible to change the color of an enemies nameplate if it is affected by a specific debuff? ( for example color it white when affected by vendetta)?

**Comment by kesava-wow** [comment]
Not without a custom script (which I haven't made yet), I'll move this to here: https://github.com/kesava-wow/kuinameplates2/issues/351 and close that issue when I update the custom script to support it.
