### ISSUE TITLE
Enemy Nameplayes showing but not Koi mode, just default letters

### ISSUE THREAD

**Issue by altrus1** [kesava-wow/kuinameplates2#330]
Hi, i dont know what changed but suddenly the enemy playes went to default blue letters, and i cant find a solution to bring it back to show in koi plates. i see npc, and friendlies as usual koi plates.
tried reinstalling, deleting cache, V keybind to show-hide plates, disabled-enabled default blizzard optionms, but nothing works.
![koinameplatesbug](https://user-images.githubusercontent.com/43300444/45588969-e6aba980-b91d-11e8-92e2-35ac2099b3c0.png)

**Comment by kesava-wow** [comment]
There are a few situations under which the game won't render nameplates for certain units, and there aren't options to make it - see FAQs 2 and 7 in the description on curse.
