### ISSUE TITLE
NPC Names

### ISSUE THREAD

**Issue by Berrystuff** [kesava-wow/kuinameplates2#331]
Ive checked everything I can think of to check, but all the NPC name plates are still the Blizzard version. I turned off all other addons and left KUI running to see if somehow I had clashing addons, and I cant seem to get the NPC names to take on the KUI look.

**Comment by kesava-wow** [comment]
FAQ 1a in the [curse description](https://www.curseforge.com/wow/addons/kuinameplates). Also see FAQ 1 and 2 if that doesn't help.
