### ISSUE TITLE
possible to change backdrop?

### ISSUE THREAD

**Issue by niichtsShaiaz** [kesava-wow/kuinameplates2#332]
Is it possible to change the backdrop of the nameplates ? I don't see it in options and I tried looking through the files and I can't seem to find it either. Possibly make it a feature or if you could tell me where tochange it in the code I'd be very happy

**Comment by kesava-wow** [comment]
The background isn't a standard wow API backdrop, it's just a flat texture. It's created in Kui_Nameplates_Core/create.lua, line 415, function core:CreateBackground.

I don't plan to make it changeable (without a custom or editing code) in this version.
