### ISSUE TITLE
[Feature Request] Nameplate Style Filters

### ISSUE THREAD

**Issue by kennywasafk** [kesava-wow/kuinameplates2#335]
Apologies if that's already been requested but it'd be amazing to see a nameplate filter option similar to what ElvUI's got. Whereby you could choose to color nameplates differently based on a number of things including buffs/debuffs. Would be amazing to be able to have the nameplates change colour if the mob is infested for example. 

Thanks in advance, hopefully even if it doesn't make it into the actual addon you'll consider adding it to the Kui_Custom page. 

Cheers!

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/issues/351
