### ISSUE TITLE
[DK] Double "Blood plague" aura doesn't appear properly

### ISSUE THREAD

**Issue by cedille7** [kesava-wow/kuinameplates2#336]
![wowscrnshot_092218_215427](https://user-images.githubusercontent.com/43503730/45921247-453ecd80-beb2-11e8-963d-e1a4bde68f55.jpg)
Hello and thanks for you work, i noticed as a blood death knight, when i use my dancing rune weapon and blood boil or death's embrace , it should show 2 blood plague auras (it appears fine in my unit target frame) but only one is shown and i'm pretty sure it was working fine a few weeks ago.

**Comment by kesava-wow** [comment]
See my response here (it's the same problem): https://github.com/kesava-wow/kuinameplates2/issues/337#issuecomment-431172239
