### ISSUE TITLE
barbed shot doesn't display on target

### ISSUE THREAD

**Issue by bulgomi** [kesava-wow/kuinameplates2#337]
first, thank you for makin this great addon. just realized that every thing displays with its time correctly on target(such as murder of crows), but barbed shot doesn't even display. pleased fix this...
thank you,

**Comment by kesava-wow** [comment]
Use KuiSpellListConfig from Curse to whitelist it yourself - by default KNP shows the auras which are flagged by the game to be shown on nameplates. Blizzard didn't flag this one, for whatever reason.
