### ISSUE TITLE
[Feature Request] Disable NPC nameplates by filter

### ISSUE THREAD

**Issue by felixriermaier** [kesava-wow/kuinameplates2#338]
I'm using NPC and friendly player nameplates in name only mode. Exactly in as in this screenshot of yours:
![image](https://user-images.githubusercontent.com/35110494/46004952-6ff87400-c0b4-11e8-80c1-a2dd4fbdd8a8.png)

This is nice and good, actually perfect, except for when you enter a bigger city or outpost. As soon as you do that, the screen gets cluttered with nameplates, as there are so many NPC's.

Feature request:
Add the option to disable friendly NPC nameplates by filters. Actually disable, not fade.
The filter required for my use case would be: Disable all friendly NPC nameplates where the NPC does NOT have a title.

Referencing the screenshot above, the expected behaviour would be:
- Tenden: Nameplate still visible as he is not an NPC
- Koraud: Nameplate still visible as he has the title "Body Guard"
- Aerith Primrose: Nameplate still visible as she has the title "Flower Vendor"
- Violet Hold Guard: Nameplate disabled as he/she does not have any title

I think this feature would greatly increase the usability of friendly NPC nameplates in name only mode.

**Comment by kesava-wow** [comment]
Add-ons can't arbitrarily disable nameplates. So the only way this could be achieved would be to fade them out. That, however, would leave an invisible click box, which is confusing.

**Comment by kesava-wow** [comment]
It's a simple fade rule. I put it in the recent beta release to see how it looked. Enable it by checking the option to fade friendly NPCs under /knp > fade rules, then type: `/knp set fade_friendly_npc_exclude_titled true`

That will make friendly NPCs' nameplates fade out to the "conditional alpha" value at the top of the page. The typed option then excludes NPCs which have a vendor title from that rule. To completely hide them, set conditional alpha to 0.

**Comment by felixriermaier** [comment]
Thank you so much. This is exactly what I was looking for.
Here is some comparison to make clear what impact it has for my UI: https://imgur.com/a/SyGiZPB

Let me know when you get yourself something like a paypal tipjar.
