### ISSUE TITLE
Automatic increase of the target health band

### ISSUE THREAD

**Issue by Cosandra2007** [kesava-wow/kuinameplates2#339]
Add the option, if possible. So that the band of health of the target is slightly outscored in width, unlike the others (those who are not targeting).

**Comment by kesava-wow** [comment]
This can do target scaling: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.target-scale.lua, but it's ugly-scaling, meaning it might introduce aliasing problems.

This is an ongoing consideration, so I'll move it here: https://github.com/kesava-wow/kuinameplates2/issues/287.
