### ISSUE TITLE
Enemy's "True sight" not visible behind the frames

### ISSUE THREAD

**Issue by xGaSeRx** [kesava-wow/kuinameplates2#347]
That "true sight" blue ring above the enemy is quite rare but so crucial to see, it makes me scared to use the nameplates because like 80% of the time those are not visible behind the enemy health frame. I seem to be unable to move the frames up or down to make it clearly visible either, so for now its either use the frames bearing the risk of occasionally wiping your party or avoid using it at all :(

**Comment by kesava-wow** [comment]
Use /knp set frame_vertical_offset 0 (changing 0 for whatever works for you - it'll update instantly).

That option doesn't move the clickbox - add-ons can't move nameplate clickbo es - so don't move it too far. 

Other than that, this is something blizzard needs fix.
