### ISSUE TITLE
Name-only «In combat» detection delay.  

### ISSUE THREAD

**Issue by AterNoxis** [kesava-wow/kuinameplates2#348]
In version 2.18 and recent beta, I noticed delay in detection «In combat» status. I can hit target few times and still don’t trigger «In combat» status (in add-on, not the game). . 
This wasn't the case in 2.17 and earlier.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/dab3a407dace8f2399f87eea5f4d4473e4b58b7f
