### ISSUE TITLE
Stealth detection indicator hidden by unit frame

### ISSUE THREAD

**Issue by NeodiuM08** [kesava-wow/kuinameplates2#352]
The stealth detection indicator is being hidden by the unit frames, i've noticed this in the atal'dazar dungeon.  The indicator is behind the unit frame and visible just below and above the unit frame, though not obvious.

**Comment by kesava-wow** [comment]
Can't fix this directly, it's a blizzard issue.

You can vertically move nameplate frames slightly by changing frame_vertical_offset: `/knp set frame_vertical_offset 10`. You can change 10 to anything else, _however_ this will only move KNP's graphical representation of nameplates. Not the clickbox; the clickbox can't be moved by addons.
