### ISSUE TITLE
Nameplates not expanding in combat

### ISSUE THREAD

**Issue by Freaky-Freddy** [kesava-wow/kuinameplates2#355]
When using Kui version 2.16.4 the nameplates of all the units im in combat with automatically "expand", but recently i installed version 2.18.1 and now the nameplates don't automatically expand anymore, i have to target each unit individually if i want their nameplate to expand (spinning the camera around also seems to work in making them expand).

Here are some images that roughly show what i'm talking about: https://imgur.com/a/D3E5Ze6

Is this behavior intended?

**Comment by kesava-wow** [comment]
It's a bug. #348.
