### ISSUE TITLE
Nameplates Showing, but Invisible

### ISSUE THREAD

**Issue by TrinitysEnd** [kesava-wow/kuinameplates2#356]
Occasionally I get a bug where the nameplate of a mob is showing, but the bar itself is transparent. It throws no errors at all when it happens. I have no clue how to duplicate it besides just running wild until randomly one enemy will have it. Sometimes more. It can get rather frustrating. I've known others to get this issue, and my scouring of the current issues and closed couldn't find any issue mentioning it. Sometimes spamming V to hide and reshow the nameplates will make it reappear, but not always.
![example one](https://user-images.githubusercontent.com/37823216/47322546-32ccc680-d60d-11e8-8123-224e07e82281.png)
![example two](https://user-images.githubusercontent.com/37823216/47322559-3b250180-d60d-11e8-99fb-9b3eb394c3bb.png)

Secondly, I get an issue with pets. Where they also similarly get an invisible nameplate but no name like the above. It looks like below.
![2018-10-22_15-05-49](https://user-images.githubusercontent.com/37823216/47322646-91924000-d60d-11e8-9f88-2a0b9192d8bf.png)

Edit: I wanted to mention I am also on Release version 2.18.1

**Comment by kesava-wow** [comment]
This is almost always due to a third party modification (including the custom scripts I provide). What's the output of `/knp dump`?

**Comment by kesava-wow** [comment]
Try disabling TRP3:KuiNameplates.

**Comment by TrinitysEnd** [comment]
Alright, after having run around for a lengthy enough time and not finding a single instance of it, I'll chalk it up to TRP3's module. I'll let the proper people know and maybe see if they can do anything about it
