### ISSUE TITLE
option to highlight on target

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#36]

**Comment by ncsibra** [comment]
I would love to see this feature, the target glow worth almost nothing, in a bigger fight I can't see who am I targeting right now.
A solution like the threat brackets would be awesome!

**Comment by whi5p** [comment]
If this means that mouseovering your target wont light the nameplate even more then yes, please!

**Comment by leobolin** [comment]
This would be amazeballs!
