### ISSUE TITLE
Glitchy healthbars

### ISSUE THREAD

**Issue by sponkster** [kesava-wow/kuinameplates2#363]
apparently, my healthbars appear to be kinda glitchy and out  of place when i move my camera up and down or left and right, it seens it tries to move with the camera instead of staying still, cant describe it any better, also i cant make a video of it, any ideas?

**Comment by sponkster** [comment]
![image](https://user-images.githubusercontent.com/42449007/49887760-4a157c80-fe24-11e8-9e28-50defe7e6474.png)

this is the closest i can get with image, the black thin bar undearneath the health bar is glitching while it tries to follow the ui scale

**Comment by kairix-reforged** [comment]
I'm having the same issue - you can see it in this picture pretty well

[
![image](https://user-images.githubusercontent.com/16170583/49922639-27a45300-fe66-11e8-88a9-371f54cba3b6.png)
](url)

**Comment by kesava-wow** [comment]
related: #365 
(and apologies for the close/open spam if that's emailing you)

**Comment by kairix-reforged** [comment]
Not sure about #365, but I can see that this issue appears to have been fixed with commit 3eccf96.

I made a quick GIF here: https://i.imgur.com/6Ji7Jiu.gif
