### ISSUE TITLE
Truncate Nameplate Text

### ISSUE THREAD

**Issue by hjlinde** [kesava-wow/kuinameplates2#367]
I'm currently trying to do a custom addon, however it's going rather slow to learn how to do this xD

I really would like a function to truncate the name text for when positioning the name text inside the healthbar. Happy to do this as a custom, just not really sure where to start :)

To prevent this essentially...
![image](https://user-images.githubusercontent.com/920794/50399970-dd876f80-078b-11e9-8f9b-fbebc850531b.png)

**Comment by kesava-wow** [comment]
truncated by default now, can be edited with name_constrain_offset
