### ISSUE TITLE
Nameplates fade out the further away from the target

### ISSUE THREAD

**Issue by Asphalosa** [kesava-wow/kuinameplates2#370]
This has never happened before the latest update, the further away from the mobs I am, the less visible the nameplates are. If the body of the enemy is not visible their nameplate will also fade out really heavily. Thats. Pretty bad.  http://prntscr.com/m3g8gu Comparison of closer and further away target. http://prntscr.com/m3g8y0 Completely different alphas for the nameplates of the same mob type but in different range away from me. If this is a feature revert it or let me turn it off, because frankly I can't find any option to deal with it. Cheers mate.

**Comment by kesava-wow** [comment]
I assume you found the options? I made it as clear as I could without spamming messages in chat (which people usually miss anyway) or other such intrusive things.
