### ISSUE TITLE
Kui Nameplates Extra has a bug report and does not work

### ISSUE THREAD

**Issue by holycinders** [kesava-wow/kuinameplates2#371]
Having Kui nameplates extra on disables them completely as the extra module is bugged. Kui nameplates will work when disabling the extra features, however. This only occurred after updating recently.

Here is the report:
Date: 2019-01-07 19:17:11
ID: 1
Error occured in: Global
Count: 1
Message: ...face\AddOns\Kui_Nameplates_Extras\modules\leftie.lua line 57:
   attempt to perform arithmetic on field 'text_vertical_offset' (a nil value)
Debug:
   ...face\AddOns\Kui_Nameplates_Extras\modules\leftie.lua:57: UpdateHealthText()
   Kui_Nameplates_Core\hook.lua:65: func()
   Kui_Nameplates\messages.lua:128: DispatchMessage()
   Kui_Nameplates\nameplate.lua:73: OnShow()
   Kui_Nameplates\nameplate.lua:67: OnUnitAdded()
   Kui_Nameplates\addon.lua:80: ?()
   Kui_Nameplates\addon.lua:126:
      Kui_Nameplates\addon.lua:123
Locals:
f = KuiNamePlate1 {
 LevelText = <unnamed> {
 }
 Highlight = <unnamed> {
 }
 UpdateMainBars = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:469
 parent = NamePlate1 {
 }
 UpdateHealthText = <function> defined @Interface\AddOns\Kui_Nameplates_Extras\modules\leftie.lua:50
 UpdateRaidIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1444
 AbsorbBar = <unnamed> {
 }
 UpdateFrameGlow = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:879
 bg = <unnamed> {
 }
 UpdateGuildText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:821
 NameText = <unnamed> {
 }
 IN_NAMEONLY = true
 unit = "nameplate1"
 UpdateNameOnlyGlowSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:2017
 state = <table> {
 }
 NameOnlyGlow = <unnamed> {
 }
 RaidIcon = <unnamed> {
 }
 animated_bars = <table> {
 }
 ShowCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1060
 UpdateStateIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1406
 CastBar = <unnamed> {
 }
 Auras = <table> {
 }
 ThreatBrackets = <table> {
 }
 UpdateFrameSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:397
 UpdateAuras = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1552
 UpdateAbsorbBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:547
 UpdateCastbarSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1205
 HealthText = <unnamed> {
 }
 StateIcon = <unnamed> {
 }
 handler = <table> {
 }
 GuildText = <unnamed> {
 }
 SpellIconSetWidth = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1053
 0 = <userdata>
 UpdateFrameGlowSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:927
 SpellIcon = <unnamed> {
 }
 UpdateCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1163
 PowerBar = <unnamed> {
 }
 SpellName = <unnamed> {
 }
 HideCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1101
 UpdateSpellNamePosition = <function> defined @Interface\AddOns\Kui_Nameplates_Extras\modules\leftie.lua:63
 UpdatePowerBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:501
 SpellShield = <unnamed> {
 }
 UpdateNameTextPosition = <function> defined @Interface\AddOns\Kui_Nameplates_Extras\modules\leftie.lua:32
 elements = <table> {
 }
 UpdateStateIconSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1427
 UpdateThreatBrackets = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1910
 UpdateHighlight = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:432
 UpdateLevelText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:729
 CastBarUpdateFrame = <unnamed> {
 }
 BossModAuraFrame = <unnamed> {
 }
 HealthBar = <unnamed> {
 }
 UpdateNameText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:679
 ThreatGlow = <table> {
 }
 cast_state = <table> {
 }
}
(*temporary) = nil
(*temporary) = -2
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'text_vertical_offset' (a nil value)"
orig_UpdateHealthText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:779
mod = <table> {
 __EVENTS = <table> {
 }
 Leftie_PostCreate = <function> defined @Interface\AddOns\Kui_Nameplates_Extras\modules\leftie.lua:82
 Leftie_Init = <function> defined @Interface\AddOns\Kui_Nameplates_Extras\modules\leftie.lua:107
 priority = 101
 CustomCode_Init = <function> defined @Interface\AddOns\Kui_Nameplates_Extras\modules\custom.lua:5
 enable_on_load = true
 enabled = true
 profile = <table> {
 }
 config = <table> {
 }
 Create = <function> defined @Interface\AddOns\Kui_Nameplates_Extras\main.lua:14
 ADDON_LOADED = <function> defined @Interface\AddOns\Kui_Nameplates_Extras\main.lua:21
 plugin = true
 Leftie_PostShow = <function> defined @Interface\AddOns\Kui
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  Ace3, v
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BelowAverageItems, v1.29
  ChatSounds, vv1.2.2
  ClassicUI, v1.1.2
  Clique, vv80000-1.0.0
  CollectMe, v2.10.1
  CrossRP, v1.8.0
  DBMCore, v8.1.1
  DBMDefaultSkin, v
  DBMInterrupts, v7.3.0
  DBMLDB, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r103
  Details, v
  DetailsDeathGraphs, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTimeLine, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Elephant, v3.7.7
  EmoteSplitter, v1.5.8
  GatherMate2, v1.43.4
  GnomTEC, v8.1.0.13
  GnomTECNPCEmote, v8.1.0.22
  HandyNotes, vv1.5.3
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBoralusRP, v0.331
  HandyNotesBrokenShore, vv1.30
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.45
  HandyNotesHallowsEnd, vv1.4.3
  HandyNotesLegionClassOrderHalls, vv1.30
  HandyNotesLegionInstanceWorldQuests, vv1.17
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesLunarFestival, vv1.5
  HandyNotesSummerFestival, vv1.5
  HandyNotesSuramarShalAranTelemancy, vv1.20
  HandyNotesSuramarTelemancy, v1
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWitheredArmyTraining, v1
  Informant, v8.0.6159 (SwimmingSeadragon)
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  KuiNameplatesExtras, v3
  LeatrixPlus, v8.1.00
  Listener, v2.1.5
  LucidNightmareHelper, v
  MageNuggets, v6.1.1
  MageNuggetsCooldownMonitor, v6.0.2
  Misspelled, v1.7.2
  npcGenerator, v
  npcGToTRP3, v
  NPCScan, v8.0.1.13
  Pawn, v2.2.33
  Postal, vv3.6.0
  ProfessionAssistance, v3.5.6-HotFix
  QuestCompletist, v109.20
  SavedInstances, v8.0.8
  SexyMap, vv8.0.8
  Simulationcraft, v1.10.10
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  SmexyMats, v8.1.0.2
  Sounds4Chat, vv6.1.1
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TomCats, v1.0.1
  TomCatsDarkshoreRares, v1.2.5
  TomTom, vv80001-1.0.2
  totalRP3, v1.5.2
  totalRP3Data, v
  totalRP3Extended, v1.3.0
  totalRP3ExtendedImpExport, v1.3.0
  totalRP3ExtendedTools, v1.3.0
  totalRP3KuiNameplates, v1.4.1
  TransmogTokens, v1.4.9
  WeakAuras, v2.10.11
  WIM, v3.7.18
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=aae)

**Comment by kesava-wow** [comment]
Extras isn't being maintained anymore, so uninstall it. Leftie was moved into customs.

**Comment by holycinders** [comment]
I see. Thank you for informing me!
