### ISSUE TITLE
Name only view not working correct with the option for showing NPCs in the Blizzard UI 

### ISSUE THREAD

**Issue by pexlar** [kesava-wow/kuinameplates2#372]
**Hello, we have the following option in the Blizzard UI.**
https://i.imgur.com/MuMeDiX.png

**This is option is not working correct with the "Name only view", for example here is the view with the Blizzard UI. I see only the "Flugmeister-NPC" on the left side and the "Schmied-NPC" on the right side.**
https://i.imgur.com/urguqst.jpg

**Here is the same with the "Kuinameplates / Name only view" active. I see two more "garbage" NPCs which i dont want to see.**
https://i.imgur.com/IRUCYCE.jpg

If you can fix this, it would be great.

Regards 
pexlar

**Comment by kesava-wow** [comment]
That option affects the old floating names (visible in your second screenshot), not nameplates. The game decides where nameplates render; addons can't arbitrarily hide them.  So the only way I could "hide" these is to make them invisible, which would leave the click-box up, which is a bad UI experience.
