### ISSUE TITLE
Energy bar on enemy nameplates?

### ISSUE THREAD

**Issue by Maximos7** [kesava-wow/kuinameplates2#373]
Hello! Where is the option to enable and customize the enemy's energy bar? I mean bosse's energy bar in raids etc not on pvp.
Thank you! :)

**Comment by Maximos7** [comment]
Can someone answer pls? Tommorow the new raid opens and i really need to know. Thank you!

**Comment by kesava-wow** [comment]
KNP doesn't have an option to show an energy bar on nameplates (except the PRD). WeakAuras (or similar) could show one on nameplates, if it's important for a particular boss.

**Comment by Maximos7** [comment]
Ok  ty :)
