### ISSUE TITLE
No health bars on friendly players

### ISSUE THREAD

**Issue by bluesh34** [kesava-wow/kuinameplates2#376]
I'm not seeing any health bars on friendly players.  I would like to see them and I would like them all to be blue for friendly players.  I did have this working before but a WoW error caused all my addons to reset the other day and I haven't be able to get it working again.  Help appreciated.  For enemy players I would like to see health bars with class colours and this is currently working ok.

I tried the thing in the faq about checking the 'Always Show Friendly NPC Nameplates' Under cvars, although this was probably irrelevant as it's players I'm interested in rather than npcs.  Anyway I checked the box and not only did it not help, but it has actually messed up the default ui, which was working ok.  I wasn't seeing any health bars when I used the default Blizz ui either, although I've no fixed this by resetting the ui.  I'd still like to be able to get it right when using kui though, as I said in the 1st paragraph.

**Comment by kesava-wow** [comment]
I try to imply the risk of enabling the cvar page in the checkbox's tooltip. Cvars are just character specific settings in the game which don't have an option anywhere in the default interface, for whatever reason that might be. So, that page is for altering nameplate-related options that are hidden in the game. As such, changes made there also affect the vanilla nameplates. 

You just need to disable KNP's name-only mode. `/knp nameonly` - uncheck the checkbox at the top.

**Comment by bluesh34** [comment]
Perfect.  Thanks.
