### ISSUE TITLE
Tank mode not enabled after LFD auto-spec switch to tank

### ISSUE THREAD

**Issue by ronin-seven** [kesava-wow/kuinameplates2#377]
It appears that threat tank mode is not enabled when you are automatically switched to tank spec upon entering a LFD dungeon, at least for my level 80 DK.  It's only enabled if I manually switch to tank spec.

**Comment by ronin-seven** [comment]
I fixed this by adding:

self:RegisterEvent('PLAYER_ENTERING_WORLD','SpecUpdate')

to OnEnable in tankmode.lua

**Comment by kesava-wow** [comment]
Thanks!
