### ISSUE TITLE
2-7-beta-1 classpowers_on_target ticked error

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates2#38]
I'm pretty positive you aren't done setting up the section for Class powers yet so this bug report is most likely pointless but just wanted to raise an issue that upon clicking the Class powers option and checking the classpowers_on_target, this error popped up

`1x ...rfaceKui_Nameplates\elements/classpowers.lua:277: attempt to index upvalue 'cpf' (a nil value)
...rfaceKui_Nameplates\elements/classpowers.lua:277: in function <...rfaceKui_Nameplates\elements/classpowers.lua:258>
...rfaceKui_Nameplates\elements/classpowers.lua:349: in function `func'
Kui_Nameplates\messages.lua:29: in function `DispatchMessage'
Kui_Nameplates\elements/target.lua:9: in function <Kui_Nameplates\elements/target.lua:7>
Kui_Nameplates\elements/target.lua:41: in function `func'
Kui_Nameplates\messages.lua:29: in function `DispatchMessage'
Kui_Nameplates\nameplate.lua:69: in function `OnShow'
Kui_Nameplates\nameplate.lua:63: in function `OnUnitAdded'
Kui_Nameplates\addon.lua:54: in function `?'
Kui_Nameplates\addon.lua:90: in function <Kui_Nameplates\addon.lua:87>

Locals:
frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "target"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'cpf' (a nil value)"
on_target = true
cpf = nil
FRAME_POINT = nil
ele = <table> {
 Enable = <function> defined @Kui_Nameplates\messages.lua:321
 PLAYER_ENTERING_WORLD = <function> defined @Kui_Nameplates\elements/classpowers.lua:352
 Initialise = <function> defined @Kui_Nameplates\elements/classpowers.lua:483
 Initialised = <function> defined @Kui_Nameplates\elements/classpowers.lua:458
 PowerEvent = <function> defined @Kui_Nameplates\elements/classpowers.lua:435
 priority = 0
 CVAR_UPDATE = <function> defined @Kui_Nameplates\elements/classpowers.lua:356
 OnDisable = <function> defined @Kui_Nameplates\elements/classpowers.lua:453
 __CALLBACKS = <table> {
 }
 callbacks = <table> {
 }
 enabled = true
 element = true
 RuneUpdate = <function> defined @Kui_Nameplates\elements/classpowers.lua:418
 OnEnable = <function> defined @Kui_Nameplates\elements/classpowers.lua:447
 name = "ClassPowers"
 __MESSAGES = <table> {
 }
 TargetUpdate = <function> defined @Kui_Nameplates\elements/classpowers.lua:348
 PowerInit = <function> defined @Kui_Nameplates\elements/classpowers.lua:367
 UpdateConfig = <function> defined @Kui_Nameplates\elements/classpowers.lua:302
 Disable = <function> defined @Kui_Nameplates\messages.lua:330
}
`

**Comment by kesava-wow** [comment]
Probably because it didn't initialise in that session. Thanks.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/09863eaeb8762cb1b167de0ecfc5af59a0f1237a
