### ISSUE TITLE
Auras Bug

### ISSUE THREAD

**Issue by TheCaptnawesome** [kesava-wow/kuinameplates2#383]
2.21 2.4
enUS DEATHKNIGHT
{ ["profile"] = "default" }
{ ["auras_icon_squareness"] = 1, ["auras_centre"] = false, ["auras_icon_normal_size"] = 15, ["threat_brackets"] = true, ["frame_height"] = 20, ["auras_icon_minus_size"] = 0 }
HealthBar, CombatUpdate, NameText, [LevelText], RaidIcon, ClassPowers, CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, Fading, GuildText, PlayerAnchor, TankMode, BossMods, [CombatToggle], BarAnimation, ArenaID, Target

34x Kui_Nameplates\elements/auras.lua:304: TexCoord out of range
[C]: in function `SetTexCoord'
Kui_Nameplates\elements/auras.lua:304: in function <Kui_Nameplates\elements/auras.lua:295>
Kui_Nameplates\elements/auras.lua:414: in function `GetButton'
Kui_Nameplates\elements/auras.lua:446: in function `DisplayButton'
Kui_Nameplates\elements/auras.lua:396: in function `GetAuras'
Kui_Nameplates\elements/auras.lua:359: in function `Update'
Kui_Nameplates\elements/auras.lua:827: in function `func'
Kui_Nameplates\messages.lua:164: in function <Kui_Nameplates\messages.lua:146>
Kui_Nameplates\messages.lua:211: in function <Kui_Nameplates\messages.lua:186>

**Comment by kesava-wow** [comment]
auras_icon_minus_size must be above 0.
`/knp set auras_icon_minus_size nil`

The textboxes under sliders intentionally let you bypass the limits, but do
that with the knowledge that you can break things, for example, by inducing
division by zero.

**Comment by kesava-wow** [comment]
auras_icon_minus_size must be above 0. `/knp set auras_icon_minus_size nil`

The textboxes under sliders intentionally let you bypass the limits, but do
that with the knowledge that you can break things, for example, by inducing
division by zero.
