### ISSUE TITLE
Nameplates not showing after updating from 2.18.2.

### ISSUE THREAD

**Issue by ApplesGoneBloopie** [kesava-wow/kuinameplates2#384]
I'm currently having an issue wherein my nameplates completely disappear after switching from version 2.18.2; I've tried every other release version, but none of them show nameplates, meaning I have to stick with 2.18.2. I've had it for a few months now, but I'd like to update. I don't have any other addons that change nameplates, except flyPlateBuffs, which I disabled, but it has done nothing. I'm also using the profile from 2.18.2, but it shows nothing. Creating a new profile doesn't seem possible for some reason. I can type in a name for the profile and click okay, but it does nothing, and I don't want to delete my profiles to potentially "force" a new one.

Other than that, I really like this addon.

**Comment by kesava-wow** [comment]
Update to the most recent version and try running this in chat:
```
/knp set cvar_enable true && set cvar_disable_alpha nil && set cvar_occluded_mult nil
````

If that doesn't help, enable lua errors and reload the ui:
```
/consle scriptErrors 1
/console ReloadUI
```

Do any errors relating to KNP pop up? Does one pop up if you try to make a new profile? Copy them here.

You don't need to comment in both places.

**Comment by ApplesGoneBloopie** [comment]
I updated to the most recent version and ran that first command in chat, but nothing happened. I then downloaded AdvancedInterfaceOptions, enabled error reporters, and then I ran both your commands in chat. I didn't get anything from those either. I then reverted back to 2.18.2 and ran the bottom two commands again, but nothing showed up.

This is with the most recent update of KNP, and I changed nothing from 2.18.2:
![wowscrnshot_030519_023858](https://user-images.githubusercontent.com/45555981/53791799-def1b880-3eef-11e9-9a43-03893ae3c5cf.jpg)

This is how it looks when I use 2.18.2, yet again with nothing changed:
![image](https://user-images.githubusercontent.com/45555981/53791959-40b22280-3ef0-11e9-99b0-7f6b32ab2c5b.png)

**Comment by kesava-wow** [comment]
Ok, can you also give me the ouput of: `/knp dump` - it should open a window you can copy text out of. It has your KNP profile and some other things which try to help me recreate your environment.

If I can't work it out from that then, without any lua errors, I don't really have enough information to know what's happening.

**Comment by ApplesGoneBloopie** [comment]
2.18.2 2.4+x
{ ["profile"] = "Person" }
{ ["font_size_normal"] = 14, ["guild_text_players"] = true, ["ignore_uiscale"] = true, ["title_text_players"] = true, ["health_text_friend_dmg"] = 1, ["health_text"] = true, ["frame_height"] = 15, ["cvar_disable_scale"] = false, ["cvar_show_friendly_npcs"] = true, ["name_colour_npc_neutral"] = { [1] = 1, [2] = 0.96862745098039, [3] = 1 }, ["name_colour_player_hostile"] = { [1] = 0.6078431372549, [2] = 0, [3] = 0 }, ["colour_player_class"] = true, ["cvar_personal_show_combat"] = false, ["class_colour_enemy_names"] = true, ["name_colour_npc_hostile"] = { [1] = 0.6078431372549, [2] = 0, [3] = 0 }, ["cvar_enable"] = true, ["name_colour_npc_friendly"] = { [1] = 0, [2] = 0.57254901960784, [3] = 0 }, ["castbar_colour"] = { [1] = 1, [2] = 1, [3] = 0 }, ["fade_neutral_enemy"] = true }
HealthBar, CombatUpdate, NameText, [LevelText], RaidIcon, ClassPowers, CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, TankMode, Fading, GuildText, CombatToggle, ArenaID, BossMods, BarAnimation, PlayerAnchor, KuiNameplatesExtras, Target

2.21 2.4+x
enUS DRUID
{ ["profile"] = "Person" }
{ ["font_size_normal"] = 14, ["guild_text_players"] = true, ["ignore_uiscale"] = true, ["title_text_players"] = true, ["health_text_friend_dmg"] = 1, ["health_text"] = true, ["frame_height"] = 15, ["cvar_disable_scale"] = false, ["cvar_show_friendly_npcs"] = true, ["name_colour_npc_neutral"] = { [1] = 1, [2] = 0.96862745098039, [3] = 1 }, ["name_colour_player_hostile"] = { [1] = 0.6078431372549, [2] = 0, [3] = 0 }, ["colour_player_class"] = true, ["cvar_personal_show_combat"] = false, ["class_colour_enemy_names"] = true, ["name_colour_npc_hostile"] = { [1] = 0.6078431372549, [2] = 0, [3] = 0 }, ["cvar_enable"] = true, ["name_colour_npc_friendly"] = { [1] = 0, [2] = 0.57254901960784, [3] = 0 }, ["castbar_colour"] = { [1] = 1, [2] = 1, [3] = 0 }, ["fade_neutral_enemy"] = true }
HealthBar, CombatUpdate, NameText, [LevelText], RaidIcon, ClassPowers, CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, TankMode, Fading, GuildText, [CombatToggle], ArenaID, BossMods, BarAnimation, PlayerAnchor, KuiNameplatesExtras, Target

I tried looking through these myself and I didn't notice any differences, but maybe you will. Yet again, these are with no apparent changes, so anything changed would be inbetween version changes. In the end, if I don't figure out what's up, I'm fine with that, assuming the addon still works in future patches, because this addon is fantastic. I'm moreso just scared that I won't be able to have this addon work in a new patch.

If it comes to that, how would you recommend completely uninstalling the addon? Maybe a completely clean install would work.

**Comment by kesava-wow** [comment]
OK, should've asked for that first. Disable (and uninstall) Kui_Nameplates_Extras - it doesn't exist anymore, and [leftie](https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.leftie.lua) was moved into customs, if you were using that at some point.

That should fix it.

**Comment by ApplesGoneBloopie** [comment]
That fixed it. Thank you. Other than that, I'm wondering if there's only two things I'm curious about:

1. Is there a way to separate friendly player/NPC nameplate font sizes from the font size of enemy nameplates?

2. Is there a way to make friendly nameplates not stack while still making enemy nameplates stack?

If not, that's okay. Thanks for your support, gamer. 
![3x (1)](https://user-images.githubusercontent.com/45555981/54064324-d394da80-41d8-11e9-8d12-23fec00ca6f9.gif)
