### ISSUE TITLE
casting bar - detach check bug

### ISSUE THREAD

**Issue by woohunter** [kesava-wow/kuinameplates2#386]
error
469x Kui_Nameplates_Core\create.lua:985: attempt to index field 'bg' (a nil value)
Kui_Nameplates_Core\create.lua:985: in function `UpdatePosition'
Kui_Nameplates_Core\create.lua:997: in function `SetSize'
Kui_Nameplates_Core\create.lua:1009: in function `UpdateTargetArrows'
Kui_Nameplates_Core\create.lua:1127: in function `ShowCastBar'
Kui_Nameplates_Core\hook.lua:108: in function `func'
Kui_Nameplates\messages.lua:129: in function `DispatchMessage'
Kui_Nameplates\elements/castbar.lua:83: in function `CastBarShow'
Kui_Nameplates\elements/castbar.lua:139: in function `func'
Kui_Nameplates\messages.lua:164: in function <Kui_Nameplates\messages.lua:146>
Kui_Nameplates\messages.lua:211: in function <Kui_Nameplates\messages.lua:186>

Locals:
InCombatSkipped

2.21 2.4
koKR HUNTER
{ ["profile"] = "default" }
{ ["auras_icon_normal_size"] = 30, ["health_text_hostile_max"] = 6, ["castbar_detach_height"] = 20, ["health_text_hostile_dmg"] = 6, ["health_text"] = true, ["frame_width_personal"] = 170, ["castbar_detach_width"] = 180, ["cvar_max_distance"] = 45, ["auras_show_all_self"] = true, ["bar_texture"] = "Kui shaded bar", ["auras_offset"] = 10, ["colour_hated"] = { [1] = 0, [2] = 1, [3] = 1 }, ["target_arrows_size"] = 35, ["auras_purge_size"] = 45, ["target_arrows"] = true, ["target_glow_colour"] = { [1] = 1, [2] = 0, [3] = 0, [4] = 1 }, ["frame_width_minus"] = 120, ["frame_width"] = 180, ["castbar_detach_combine"] = false, ["frame_height_minus"] = 12, ["mouseover_highlight"] = false, ["auras_centre"] = false, ["frame_glow_size"] = 16, ["powerbar_height"] = 10, ["hide_names"] = false, ["frame_height"] = 15, ["auras_icon_minus_size"] = 25, ["frame_height_personal"] = 15, ["castbar_height"] = 23, ["auras_icon_squareness"] = 0.80000001192093, ["cvar_enable"] = true, ["global_scale"] = 0.89999997615814, ["castbar_colour"] = { [1] = 1, [2] = 1, [3] = 0 }, ["level_text"] = true }
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, [ClassPowers], CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, Fading, GuildText, PlayerAnchor, TankMode, Elite, BossMods, [CombatToggle], BarAnimation, ArenaID, Target

**Comment by Dajova** [comment]
getting the same issue here 
`90x Kui_Nameplates_Core\create.lua:985: attempt to index field 'bg' (a nil value)
Kui_Nameplates_Core\create.lua:985: in function `UpdatePosition'
Kui_Nameplates_Core\create.lua:997: in function `SetSize'
Kui_Nameplates_Core\create.lua:1009: in function `UpdateTargetArrows'
Kui_Nameplates_Core\create.lua:1127: in function `ShowCastBar'
Kui_Nameplates_Core\hook.lua:108: in function `func'
Kui_Nameplates\messages.lua:129: in function `DispatchMessage'
Kui_Nameplates\elements/castbar.lua:83: in function `CastBarShow'
Kui_Nameplates\elements/castbar.lua:139: in function `func'
Kui_Nameplates\messages.lua:164: in function <Kui_Nameplates\messages.lua:146>
Kui_Nameplates\messages.lua:211: in function <Kui_Nameplates\messages.lua:186>

Locals:
InCombatSkipped`

**Comment by kesava-wow** [comment]
@dajova, can you also post the output of `/knp dump` - it should open a
window you can copy text out of. Thanks.

**Comment by Dajova** [comment]
Sure.
`2.21 2.4
enUS HUNTER
{ ["profile"] = "default" }
{ ["fade_avoid_execute_friend"] = true, ["bot_vertical_offset"] = 3, ["castbar_showpersonal"] = true, ["frame_height_personal"] = 20, ["fade_avoid_mouseover"] = true, ["castbar_detach_height"] = 22, ["ignore_uiscale"] = true, ["health_text"] = true, ["frame_width_personal"] = 200, ["fade_avoid_tracked"] = true, ["combat_friendly"] = 3, ["castbar_detach_width"] = 150, ["fade_friendly_npc"] = true, ["cvar_personal_show_target"] = true, ["cvar_max_distance"] = 100, ["cvar_self_clamp_top"] = 0.099999986588955, ["clickthrough_self"] = true, ["fade_speed"] = 0.25, ["threat_brackets"] = true, ["font_size_normal"] = 14, ["powerbar_height"] = 5, ["cvar_clamp_bottom"] = 0.29999998211861, ["frame_height_minus"] = 13, ["mouseover_glow"] = true, ["fade_avoid_nameonly"] = false, ["frame_glow_size"] = 10, ["colour_absorb"] = { [1] = 0.30196078431373, [2] = 0.70196078431373, [3] = 1, [4] = 0.7843137254902 }, ["auras_count_offset_x"] = 0, ["auras_icon_minus_size"] = 26, ["castbar_detach_offset"] = 2, ["font_face"] = "Supermolot", ["fade_conditional_alpha"] = 0, ["castbar_colour"] = { [1] = 0.19607843137255, [2] = 0.19607843137255, [3] = 1 }, ["cvar_clamp_top"] = 0.19999998807907, ["cvar_overlap_v"] = 1, ["auras_icon_normal_size"] = 36, ["execute_colour"] = { [1] = 1, [2] = 0.39607843137255, [3] = 0.82745098039216 }, ["health_text_hostile_max"] = 3, ["auras_cd_offset_y"] = 0, ["cvar_name_only"] = true, ["castbar_unin_colour"] = { [1] = 0.7843137254902, [2] = 0.19607843137255, [3] = 0.7843137254902 }, ["name_vertical_offset"] = 2, ["health_text_hostile_dmg"] = 2, ["nameonly_neutral"] = true, ["font_size_small"] = 12, ["cvar_show_friendly_npcs"] = true, ["clickthrough_friend"] = true, ["tankmode_other_colour"] = { [1] = 0.23529411764706, [2] = 0.63529411764706, [3] = 0.70196078431373 }, ["fade_non_target_alpha"] = 0.69999998807907, ["name_colour_npc_friendly"] = { [1] = 0.3921568627451, [2] = 1, [3] = 0.3921568627451 }, ["name_colour_npc_hostile"] = { [1] = 1, [2] = 0.3921568627451, [3] = 0.3921568627451 }, ["bar_animation"] = 1, ["castbar_detach"] = true, ["fade_avoid_casting_uninterruptible"] = false, ["fade_neutral_enemy"] = true, ["auras_offset"] = 30, ["colour_self_class"] = false, ["colour_hated"] = { [1] = 1, [2] = 0.2, [3] = 0.10196078431373 }, ["target_arrows"] = true, ["auras_purge_size"] = 40, ["auras_count_offset_y"] = 0, ["target_glow_colour"] = { [1] = 1, [2] = 1, [3] = 1, [4] = 0.58823529411765 }, ["fade_avoid_casting_hostile"] = true, ["cvar_enable"] = true, ["frame_width"] = 150, ["level_text"] = true, ["castbar_detach_combine"] = false, ["classpowers_size"] = 30, ["castbar_height"] = 12, ["cvar_occluded_mult"] = 0, ["classpowers_on_target"] = false, ["frame_width_minus"] = 100, ["frame_height"] = 20, ["nameonly_combat_hostile_player"] = false, ["target_arrows_size"] = 36, ["auras_cd_offset_x"] = 0, ["name_colour_npc_neutral"] = { [1] = 1, [2] = 1, [3] = 0.3921568627451 }, ["guild_text_players"] = true, ["castbar_name_vertical_offset"] = 18, ["auras_icon_squareness"] = 0.80000001192093, ["bossmod_clickthrough"] = true, ["cvar_self_clamp_bottom"] = 0.19999998807907, ["fade_avoid_casting_interruptible"] = true, ["auras_cd_size"] = 14, ["auras_count_size"] = 12, ["bar_texture"] = "Dajova", ["nameonly_no_font_style"] = true }
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, [ClassPowers], CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, Fading, GuildText, PlayerAnchor, TankMode, BossMods, CombatToggle, BarAnimation, ArenaID, Target`

**Comment by Dajova** [comment]
Any news yet? Its starting to get ridicolus how much its triggers.

`155x Kui_Nameplates_Core\create.lua:985: attempt to index field 'bg' (a nil value)
Kui_Nameplates_Core\create.lua:985: in function `UpdatePosition'
Kui_Nameplates_Core\create.lua:997: in function `SetSize'
Kui_Nameplates_Core\create.lua:1009: in function `UpdateTargetArrows'
Kui_Nameplates_Core\create.lua:1127: in function `ShowCastBar'
Kui_Nameplates_Core\hook.lua:108: in function `func'
Kui_Nameplates\messages.lua:129: in function `DispatchMessage'
Kui_Nameplates\elements/castbar.lua:83: in function `CastBarShow'
Kui_Nameplates\elements/castbar.lua:139: in function `func'
Kui_Nameplates\messages.lua:164: in function <Kui_Nameplates\messages.lua:146>
Kui_Nameplates\messages.lua:211: in function <Kui_Nameplates\messages.lua:186>

Locals:
InCombatSkipped`
