### ISSUE TITLE
Kui_Nameplates\elements/auras.lua:817: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Thrumbar** [kesava-wow/kuinameplates2#389]
Message: Interface\AddOns\Kui_Nameplates\elements/auras.lua:817: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sat Apr 13 20:53:58 2019
Count: 10
Stack: Interface\AddOns\Kui_Nameplates\elements/auras.lua:817: bad argument #1 to 'pairs' (table expected, got nil)
[C]: ?
Interface\AddOns\Kui_Nameplates\elements/auras.lua:817: in function `FactionUpdate'
Interface\AddOns\Kui_Nameplates\elements/auras.lua:806: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:129: in function `DispatchMessage'
Interface\AddOns\Kui_Nameplates\nameplate.lua:73: in function `OnShow'
Interface\AddOns\Kui_Nameplates\nameplate.lua:67: in function `OnUnitAdded'
Interface\AddOns\Kui_Nameplates\addon.lua:80: in function `?'
Interface\AddOns\Kui_Nameplates\addon.lua:126: in function <Interface\AddOns\Kui_Nameplates\addon.lua:123>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by kesava-wow** [comment]
caused by #388
