### ISSUE TITLE
Quesiton: Class Powers?

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates2#39]
So was excited you added a class powers section but then got to thinking... is it what I think it is?

So enabling it doesn't really show anything at all tried different classes (rogue to see if something would show up) and nothing at all. Tried in a group, in a raid, solo, standing next to different classes, etc.

Is it just not implemented yet? What is exactly supposed to show? A power bar? Power gains (such as combo points, hence testing with a rogue)?

Can you expand on it and what if anything should be shown?

**Comment by kesava-wow** [comment]
combo points, shards, holy power, etc.

**Comment by ceylina** [comment]
I figured it out after doing a logout and back in. Finally showed up on the target nameplate. Thanks for taking the time to answer my dumb question (yes there are dumb questions!)
