### ISSUE TITLE
Kui_Nameplates\elements/auras.lua:826: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Thrumbar** [kesava-wow/kuinameplates2#390]
Message: Interface\AddOns\Kui_Nameplates\elements/auras.lua:826: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sat Apr 13 20:55:42 2019
Count: 9
Stack: Interface\AddOns\Kui_Nameplates\elements/auras.lua:826: bad argument #1 to 'pairs' (table expected, got nil)
[C]: ?
Interface\AddOns\Kui_Nameplates\elements/auras.lua:826: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:164: in function <Interface\AddOns\Kui_Nameplates\messages.lua:146>
Interface\AddOns\Kui_Nameplates\messages.lua:211: in function <Interface\AddOns\Kui_Nameplates\messages.lua:186>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by kesava-wow** [comment]
caused by #388
