### ISSUE TITLE
Minor suggestion - Level text

### ISSUE THREAD

**Issue by Thrus** [kesava-wow/kuinameplates2#399]
Hi, just wanted to suggest a little tweaking, the idea could be used for anything else though.
In the Text tab, when "Show level" is selected it will also show "Player" if target is one. Could you make this "Player" text separated from the level number. Some players may want it to show, others may not.
Thanks.

**Comment by kesava-wow** [comment]
That's not something I've ever seen, so it might be interference from another addon or a custom script. Post the output of /knp dump (it should open a window you can copy the text from).
