### ISSUE TITLE
Auras (Debuffs on enemy nameplates) not working.

### ISSUE THREAD

**Issue by BigKingAlexxx** [kesava-wow/kuinameplates2#400]
Version: Classic

@project-version@ 2.4+debug
enUS SHAMAN
{ ["profile"] = "default" }
{ ["frame_height"] = 15 }
HealthBar, CombatUpdate, NameText, [LevelText], RaidIcon, ClassPowers, CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, Fading, GuildText, PlayerAnchor, TankMode, BossMods, [CombatToggle], BarAnimation, ArenaID, Target

**Comment by kesava-wow** [comment]
Aura data doesn't exist on classic. It might be possible to fake-track them via the combat log again. Will be removing non-functional things from the classic version in the future.
