### ISSUE TITLE
[classic] Lua error (castbar related?)

### ISSUE THREAD

**Issue by Olorun** [kesava-wow/kuinameplates2#402]
Currently playing on Classic beta, get this error from time to time:

Message: Interface\AddOns\Kui_Nameplates\elements/castbar.lua:107: attempt to call global 'UnitCastingInfo' (a nil value)
Time: Tue Jun 11 13:54:45 2019
Count: 3
Stack: Interface\AddOns\Kui_Nameplates\elements/castbar.lua:107: attempt to call global 'UnitCastingInfo' (a nil value)
Interface\AddOns\Kui_Nameplates\elements/castbar.lua:107: in function `Show'
Interface\AddOns\Kui_Nameplates\elements/castbar.lua:173: in function `EnableOnFrame'
Interface\AddOns\Kui_Nameplates\nameplate.lua:55: in function `EnableElement'
Interface\AddOns\Kui_Nameplates_Core\create.lua:1186: in function `UpdateCastBar'
Interface\AddOns\Kui_Nameplates_Core\create.lua:2095: in function `NameOnlyUpdateFunctions'
Interface\AddOns\Kui_Nameplates_Core\hook.lua:122: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:129: in function `DispatchMessage'
Interface\AddOns\Kui_Nameplates\elements/target.lua:9: in function <Interface\AddOns\Kui_Nameplates\elements/target.lua:7>
Interface\AddOns\Kui_Nameplates\elements/target.lua:29: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:166: in function <Interface\AddOns\Kui_Nameplates\messages.lua:146>
Interface\AddOns\Kui_Nameplates\messages.lua:219: in function <Interface\AddOns\Kui_Nameplates\messages.lua:213>
[C]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: self = <table> {
 DisableOnFrame = <function> defined @Interface\AddOns\Kui_Nameplates\elements/castbar.lua:176
 Enable = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:499
 HIDE_SUCCESS = 3
 priority = 0
 HIDE_FRAME = 0
 enabled = true
 CastStart = <function> defined @Interface\AddOns\Kui_Nameplates\elements/castbar.lua:121
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @Interface\AddOns\Kui_Nameplates\elements/castbar.lua:166
 HIDE_INTERRUPT = 1
 CastUpdate = <function> defined @Interface\AddOns\Kui_Nameplates\elements/castbar.lua:148
 enable_on_load = true
 element = true
 Show = <function> defined @Interface\AddOns\Kui_Nameplates\elements/castbar.lua:106
 CastStop = <function> defined @Interface\AddOns\Kui_Nameplates\elements/castbar.lua:141
 name = "CastBar"
 EnableOnFrame = <function> defined @Interface\AddOns\Kui_Nameplates\elements/castbar.lua:171
 Hide = <function> defined @Interface\AddOns\Kui_Nameplates\elements/castbar.lua:117
 Create = <function> defined @Interface\AddOns\Kui_Nameplates\elements/castbar.lua:98
 HIDE_STOP = 2
 Disable = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:508
}
f = KuiNamePlate8 {
 LevelText = <unnamed> {
 }
 Highlight = <unnamed> {
 }
 UpdateMainBars = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:455
 parent = NamePlate8 {
 }
 UpdateHealthText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:701
 UpdateRaidIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1521
 UpdateFrameGlow = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:832
 bg = <unnamed> {
 }
 UpdateGuildText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:743
 unit = "nameplate1"
 UpdateLevelText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:651
 TargetGlow = <unnamed> {
 }
 ThreatGlow = <table> {
 }
 state = <table> {
 }
 UpdateNameOnlyGlowSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:2067
 ShowCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1055
 NameOnlyGlow = <unnamed> {
 }
 RaidIcon = <unnamed> {
 }
 0 = <userdata>
 UpdateStateIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1483
 UpdateFrameSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:383
 ThreatBrackets = <table> {
 }
 SpellIcon = <unnamed> {
 }
 elements = <table> {
 }
 HealthText = <unnamed> {
 }
 StateIcon = <unnamed> {
 }
 handler = <table> {
 }
 CastBar = <unnamed> {
 }
 UpdateAuras = <function> defined @Interface\AddOns\Kui_N

**Comment by stampis** [comment]
Just turn off castbars in /knp options for now..
the API 'UnitCastingInfo' does not exist in classic, and the whole castbar needs a total rewrite.
