### ISSUE TITLE
KUI Nameplates Not Displayed At All

### ISSUE THREAD

**Issue by Zadden** [kesava-wow/kuinameplates2#404]
I just installed KUI nameplates and it looks like i never even installed it. Stock nameplates are showing on everything. I can get to the KUI config screen but it does me no good cuz nothing shows up via KUI Nameplates .. any ideas?

**Comment by kesava-wow** [comment]
You probably have nameplates disabled. The old, in-world floating names aren't "nameplates" and can't be modified by add-ons. Make sure they're enabled in Esc > interface > names (and they have a keybind, V by default). Also see the FAQ in the curse description (https://www.curseforge.com/wow/addons/kuinameplates).
