### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by Hakamaori** [kesava-wow/kuinameplates2#405]
These three issues occurred after the latest patch.

Issue 1:
"xx1  Kui_Nameplates\hook.lua:61: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: KuiNamePlate1PositionHelper:SetPoint.
Stack: [C] in function 'SetPoint'
Kui_Nameplates\hook.lua:61: in function 'HookNameplate'
Kui_Nameplates\addon.lua:58: in function '?'
Kui_Nameplates\addon.lua:118: in function <Kui_Nameplates\addon.lua:115>
Time: 2019/07/25 22:14:49 Index: 1/3
RealUI Version: 2.0.14
Locals:
(*temporary) = KuiNamePlate1PositionHelper {
    0 = <userdata>
}
(*temporary) = "TOPRIGHT"
(*temporary) = NamePlate1 {
    OnSizeChanged = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:458
    GetPreferredInsets = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:439
    GetAdditionalInsetPadding = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:428
    ApplyOffsets = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:410
    OnRemoved = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:397
    OnAdded = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:374
    kui = KuiNamePlate1 {}
    UnitFrame = NamePlate1UnitFrame {}
    0 = <userdata>
    OnOptionsUpdated = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:404
}
(*temporary) = "CENTER"
"

Issue 2:
"x1  Kui_Nameplates\addon.lua:74: attempt to index field 'handler' (a nil value)
Stack: Kui_Nameplates\addon.lua:74: in function '?'
Kui_Nameplates\addon.lua:118: in function <Kui_Nameplates\addon.lua:115>
Time: 2019/07/25 22:14:49 Index: 2/3
RealUI Version: 2.0.14
Locals:
self = <unnamed> {
    NAME_PLATE_UNIT_REMOVED = <function> defined @Kui_Nameplates\addon.lua:77
    UI_SCALE_CHANGED = <function> defined @Kui_Nameplates\addon.lua:98
    DispatchMessage = <function> defined @Kui_Nameplates\messages.lua:61
    uiscale = 0.711111
    Frames = <function> defined @Kui_Nameplates\addon.lua:53
    NewElement = <function> defined @Kui_Nameplates\messages.lua:467
    NewPlugin = <function> defined @Kui_Nameplates\messages.lua:430
    plugins = <table> {}
    GetPlugin = <function> defined @Kui_Nameplates\messages.lua:460
    NAME_PLATE_UNIT_ADDED = <function> defined @Kui_Nameplates\addon.lua:64
    MINOR = 2
    USE_BLIZZARD_PERSONAL = false
    IGNORE_UISCALE = false
    Layout = <function> defined @Kui_Nameplates\messages.lua:475
    layout = <table> {}
    width = 140
    PLAYER_LEAVING_WORLD = <function> defined @Kui_Nameplates\addon.lua:89
    NAME_PLATE_CREATED = <function> defined @Kui_Nameplates\addon.lua:57
    MAJOR = 2
    Nameplate = <table> {}
    height = 40
    0 = <userdata>
    HookNameplate = <function> defined @Kui_Nameplates\hook.lua:45
    print = <function> defined @Kui_Nameplates\addon.lua:49
}
unit = "nameplate1"
f = NamePlate1 {
    OnSizeChanged = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:458
    driverFrame = NamePlateDriverFrame {}
    GetPreferredInsets = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:439
    GetAdditionalInsetPadding = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:428
    ApplyOffsets = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:410
    namePlateUnitToken = "nameplate1"
    OnRemoved = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:397
    OnAdded = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:374
    kui = KuiNamePlate1 {}
    UnitFrame = NamePlate1UnitFrame {}
    0 = <userdata>
    OnOptionsUpdated = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:404
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'handler' (a nil value)"
addon = <unnamed> {
    NAME_PLATE_UNIT_REMOVED = <function> defined @Kui_Nameplates\addon.lua:77
    UI_SCALE_CHANGED = <function> defined @Kui_Nameplates\addon.lua:98
    DispatchMessage = <function> defined @Kui_Nameplates\messages.lua:61
    uiscale = 0.711111
    Frames = <function> defined @Kui_Nameplates\addon.lua:53
    NewElement = <function> defined @Kui_Nameplates\messages.lua:467
    NewPlugin = <function> defined @Kui_Nameplates\messages.lua:430
    plugins = <table> {}
    GetPlugin = <function> defined @Kui_Nameplates\messages.lua:460
    NAME_PLATE_UNIT_ADDED = <function> defined @Kui_Nameplates\addon.lua:64
    MINOR = 2
    USE_BLIZZARD_PERSONAL = false
    IGNORE_UISCALE = false
    Layout = <function> defined @Kui_Nameplates\messages.lua:475
    layout = <table> {}
    width = 140
    PLAYER_LEAVING_WORLD = <function> defined @Kui_Nameplates\addon.lua:89
    NAME_PLATE_CREATED = <function> defined @Kui_Nameplates\addon.lua:57
    MAJOR = 2
    Nameplate = <table> {}
    height = 40
    0 = <userdata>
    HookNameplate = <function> defined @Kui_Nameplates\hook.lua:45
    print = <function> defined @Kui_Nameplates\addon.lua:49
}
UnitIsUnit = <function> defined =[C]
"

Issue 3:
"x2  ...terface\Kui_Nameplates\elements/highlight.lua:83: attempt to index field 'handler' (a nil value)
Stack: ...terface\Kui_Nameplates\elements/highlight.lua:83: in function 'func'
Kui_Nameplates\messages.lua:125: in function <Kui_Nameplates\messages.lua:88>
Time: 2019/07/25 22:14:49 Index: 3/3
RealUI Version: 2.0.14
Locals:
self = <table> {
    enabled = true
    UPDATE_MOUSEOVER_UNIT = <function> defined @Kui_Nameplates\elements/highlight.lua:78
    Enable = <function> defined @Kui_Nameplates\messages.lua:403
    __EVENTS = <table> {}
    GainedTarget = <function> defined @Kui_Nameplates\elements/highlight.lua:67
    element = true
    Show = <function> defined @Kui_Nameplates\elements/highlight.lua:57
    OnEnable = <function> defined @Kui_Nameplates\elements/highlight.lua:86
    name = "Highlight"
    LostTarget = <function> defined @Kui_Nameplates\elements/highlight.lua:72
    __MESSAGES = <table> {}
    priority = 0
    Hide = <function> defined @Kui_Nameplates\elements/highlight.lua:64
    Disable = <function> defined @Kui_Nameplates\messages.lua:412
}
event = "UPDATE_MOUSEOVER_UNIT"
f = KuiNamePlate1 {
    state = <table> {}
    parent = NamePlate1 {}
    elements = <table> {}
    0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'handler' (a nil value)"
"

**Comment by Hakamaori** [comment]
These three issues occur when I target a follower. Such as the Alliance/Horde followers in nazjatar but, the issues continue to occur in Kul Tiras and Zuldazar as well.

**Comment by thomas-moeller** [comment]
I am experiencing the same 3 errors - Entirely new installation of WOW

--------------------

x1  Kui_Nameplates\hook.lua:61: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: KuiNamePlate1PositionHelper:SetPoint.
Stack: [C] in function 'SetPoint'
Kui_Nameplates\hook.lua:61: in function 'HookNameplate'
Kui_Nameplates\addon.lua:58: in function '?'
Kui_Nameplates\addon.lua:118: in function <Kui_Nameplates\addon.lua:115>
Time: 2019/07/29 07:10:42 Index: 1/7
RealUI Version: 2.0.14
Locals:
(*temporary) = KuiNamePlate1PositionHelper {
    0 = <userdata>
}
(*temporary) = "TOPRIGHT"
(*temporary) = NamePlate1 {
    OnSizeChanged = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:458
    GetPreferredInsets = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:439
    GetAdditionalInsetPadding = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:428
    ApplyOffsets = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:410
    OnRemoved = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:397
    OnAdded = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:374
    kui = KuiNamePlate1 {}
    UnitFrame = NamePlate1UnitFrame {}
    0 = <userdata>
    OnOptionsUpdated = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:404
}
(*temporary) = "CENTER"

-------------------------------------------------

x8  Kui_Nameplates\addon.lua:74: attempt to index field 'handler' (a nil value)
Stack: Kui_Nameplates\addon.lua:74: in function '?'
Kui_Nameplates\addon.lua:118: in function <Kui_Nameplates\addon.lua:115>
Time: 2019/07/29 07:10:42 Index: 6/7
RealUI Version: 2.0.14
Locals:
self = <unnamed> {
    NAME_PLATE_UNIT_REMOVED = <function> defined @Kui_Nameplates\addon.lua:77
    UI_SCALE_CHANGED = <function> defined @Kui_Nameplates\addon.lua:98
    DispatchMessage = <function> defined @Kui_Nameplates\messages.lua:61
    uiscale = 0.533333
    Frames = <function> defined @Kui_Nameplates\addon.lua:53
    NewElement = <function> defined @Kui_Nameplates\messages.lua:467
    NewPlugin = <function> defined @Kui_Nameplates\messages.lua:430
    plugins = <table> {}
    GetPlugin = <function> defined @Kui_Nameplates\messages.lua:460
    NAME_PLATE_UNIT_ADDED = <function> defined @Kui_Nameplates\addon.lua:64
    MINOR = 2
    USE_BLIZZARD_PERSONAL = false
    ClassPowersFrame = <unnamed> {}
    IGNORE_UISCALE = false
    Layout = <function> defined @Kui_Nameplates\messages.lua:475
    layout = <table> {}
    width = 140
    PLAYER_LEAVING_WORLD = <function> defined @Kui_Nameplates\addon.lua:89
    NAME_PLATE_CREATED = <function> defined @Kui_Nameplates\addon.lua:57
    MAJOR = 2
    Nameplate = <table> {}
    height = 40
    0 = <userdata>
    HookNameplate = <function> defined @Kui_Nameplates\hook.lua:45
    print = <function> defined @Kui_Nameplates\addon.lua:49
}
unit = "nameplate1"
f = NamePlate1 {
    OnSizeChanged = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:458
    driverFrame = NamePlateDriverFrame {}
    GetPreferredInsets = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:439
    GetAdditionalInsetPadding = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:428
    ApplyOffsets = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:410
    namePlateUnitToken = "nameplate1"
    OnRemoved = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:397
    OnAdded = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:374
    kui = KuiNamePlate1 {}
    UnitFrame = NamePlate1UnitFrame {}
    0 = <userdata>
    OnOptionsUpdated = <function> defined @Blizzard_NamePlates\Blizzard_NamePlates.lua:404
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'handler' (a nil value)"
addon = <unnamed> {
    NAME_PLATE_UNIT_REMOVED = <function> defined @Kui_Nameplates\addon.lua:77
    UI_SCALE_CHANGED = <function> defined @Kui_Nameplates\addon.lua:98
    DispatchMessage = <function> defined @Kui_Nameplates\messages.lua:61
    uiscale = 0.533333
    Frames = <function> defined @Kui_Nameplates\addon.lua:53
    NewElement = <function> defined @Kui_Nameplates\messages.lua:467
    NewPlugin = <function> defined @Kui_Nameplates\messages.lua:430
    plugins = <table> {}
    GetPlugin = <function> defined @Kui_Nameplates\messages.lua:460
    NAME_PLATE_UNIT_ADDED = <function> defined @Kui_Nameplates\addon.lua:64
    MINOR = 2
    USE_BLIZZARD_PERSONAL = false
    ClassPowersFrame = <unnamed> {}
    IGNORE_UISCALE = false
    Layout = <function> defined @Kui_Nameplates\messages.lua:475
    layout = <table> {}
    width = 140
    PLAYER_LEAVING_WORLD = <function> defined @Kui_Nameplates\addon.lua:89
    NAME_PLATE_CREATED = <function> defined @Kui_Nameplates\addon.lua:57
    MAJOR = 2
    Nameplate = <table> {}
    height = 40
    0 = <userdata>
    HookNameplate = <function> defined @Kui_Nameplates\hook.lua:45
    print = <function> defined @Kui_Nameplates\addon.lua:49
}
UnitIsUnit = <function> defined =[C]

---------------------------------------

x23  ...terface\Kui_Nameplates\elements/highlight.lua:83: attempt to index field 'handler' (a nil value)
Stack: ...terface\Kui_Nameplates\elements/highlight.lua:83: in function 'func'
Kui_Nameplates\messages.lua:125: in function <Kui_Nameplates\messages.lua:88>
Time: 2019/07/29 07:10:43 Index: 7/7
RealUI Version: 2.0.14
Locals:
self = <table> {
    enabled = true
    UPDATE_MOUSEOVER_UNIT = <function> defined @Kui_Nameplates\elements/highlight.lua:78
    Enable = <function> defined @Kui_Nameplates\messages.lua:403
    __EVENTS = <table> {}
    GainedTarget = <function> defined @Kui_Nameplates\elements/highlight.lua:67
    element = true
    Show = <function> defined @Kui_Nameplates\elements/highlight.lua:57
    OnEnable = <function> defined @Kui_Nameplates\elements/highlight.lua:86
    name = "Highlight"
    LostTarget = <function> defined @Kui_Nameplates\elements/highlight.lua:72
    __MESSAGES = <table> {}
    priority = 0
    Hide = <function> defined @Kui_Nameplates\elements/highlight.lua:64
    Disable = <function> defined @Kui_Nameplates\messages.lua:412
}
event = "UPDATE_MOUSEOVER_UNIT"
f = KuiNamePlate11 {
    state = <table> {}
    parent = NamePlate11 {}
    elements = <table> {}
    0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'handler' (a nil value)"

**Comment by kesava-wow** [comment]
I'm pretty sure you're using a really old version of KNP. Get the most recent version from curse (or [here](https://github.com/kesava-wow/kuinameplates2/archive/2.24.zip)).
