### ISSUE TITLE
log in error classic server (not classic beta)

### ISSUE THREAD

**Issue by amey1956** [kesava-wow/kuinameplates2#406]
i get this error on login to classic server using classic version posted here:

3x Kui_Nameplates\messages.lua:347: Attempt to register unknown event "UNIT_THREAT_LIST_UPDATE"
[C]: in function `RegisterEvent'
Kui_Nameplates\messages.lua:347: in function `RegisterEvent'
Kui_Nameplates\messages.lua:353: in function `RegisterUnitEvent'
...faceKui_Nameplates\plugins/combat-update.lua:55: in function `OnEnable'
Kui_Nameplates\messages.lua:503: in function `Enable'
Kui_Nameplates\addon.lua:156: in function <Kui_Nameplates\addon.lua:127>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "UNIT_THREAT_LIST_UPDATE"

**Comment by kesava-wow** [comment]
That's fixed in the classic version, so you probably downloaded the wrong zip. [This one should work](https://github.com/kesava-wow/kuinameplates2/archive/classic.zip), bearing in mind the classic branch is basically just a quick fix right now.
