### ISSUE TITLE
classic release dont work

### ISSUE THREAD

**Issue by reaper123123123** [kesava-wow/kuinameplates2#408]
im trying it out for classic but i cant get the addon to load

**Comment by Sojiro84** [comment]
Did you extracted it properly?

I downloaded the master and inside the zip was one folder and inside that folder are four folders you need to extract to your AddOn directory.

Your AddOn directory needs:

- Kui_Media
- Kui_Nameplates_
- Kui_Nameplates_Core
- Kui_Nameplates_Core_Config

Then it works. It worked for me.

**Comment by reaper123123123** [comment]
Wow, i must be retarded i never moved them out of the folder. Did it now miste have been it. Ty so much

-------- Opprinnelig melding --------
Fra: Sojiro84 <notifications@github.com>
Dato: 13.08.2019 20:56 (GMT+01:00)
Til: kesava-wow/kuinameplates2 <kuinameplates2@noreply.github.com>
Ko: reaper123123123 <Andlie89@live.no>, Author <author@noreply.github.com>
Emne: Re: [kesava-wow/kuinameplates2] classic release dont work (#408)


Did you extracted it properly?

I downloaded the master and inside the zip was one folder and inside that folder are four folders you need to extract to your AddOn directory.

Your AddOn directory needs:

  *   Kui_Media
  *   Kui_Nameplates_
  *   Kui_Nameplates_Core
  *   Kui_Nameplates_Core_Config

Then it works. It worked for me.
