### ISSUE TITLE
[classic] health prediction

### ISSUE THREAD

**Issue by hodde87** [kesava-wow/kuinameplates2#410]
been trying this in classic, works fine. however there is one problem, i cant get it to show the healthnumber (the health it has----->health until it dies,

ex: a mob has 150hp (it shows 150 from start), then i hit it for 30, it then shows 120hp etc, this doesnt work.

as it works now a mob always shows 100 (percentage) from start, and then it goes down in percentage numbers.

 

any fix/help for this?

**Comment by Shadow26Wolf** [comment]
Health numbers did not exist in classic WoW, only percentages. There are addons that help predict the current HP.

**Comment by hodde87** [comment]
ye but wich one works with kui then? i have realmobhealth but that doesnt work with kui.

**Comment by kesava-wow** [comment]
None of them do, I need to code support for it. I'm pretty sure there are libraries for it; i.e. you won't have to install a specific add-on.

**Comment by hodde87** [comment]
so for a noob like me what shall i do then, wait for you to code or something else (didnt really get u on the "libraries" thing).?

**Comment by kesava-wow** [comment]
Yup, you just need to wait for me to fix it.

Thanks.
