### ISSUE TITLE
[classic] Combo Points missing

### ISSUE THREAD

**Issue by xRaen** [kesava-wow/kuinameplates2#412]
I've been trying to use Kui in Classic and overall it works great, but the one thing that doesn't seem to work is the display of Combo Points on the enemy nameplates. I prefer to have them there are the personal nameplate off, but the Combo Points aren't showing up.

**Comment by kesava-wow** [comment]
Yup. They're different on classic so I need to do some work to implement them.

**Comment by Oddwin** [comment]
Debuffs and dots aren't showing either.
