### ISSUE TITLE
[classic] Nameplates not visible

### ISSUE THREAD

**Issue by bigtimeweenfan** [kesava-wow/kuinameplates2#413]
I've installed Kui, the version listed on https://willitclassic.com ... which I believe is the most recent. The nameplates do not show up at all when I turn them on. Nothing is visible.

Even more interesting is that I can see all 4 Kui addons enabled in Addons, but /knp command does not work and it's not listed in the addOns sections of Interface Options.

**Comment by Stanzilla** [comment]
Install addons from CurseForge/WowInterface please

**Comment by kesava-wow** [comment]
Try using the most recent version from here (classic-3 as of now) and let me know: https://www.curseforge.com/wow/addons/kuinameplates/files (note that since I only just uploaded it, it probably won't come through on the Twitch app for a little while)
