### ISSUE TITLE
Enemy castbars not showing classic

### ISSUE THREAD

**Issue by staren93** [kesava-wow/kuinameplates2#415]
Enemy castbars not showing classic

@project-version@ 2.4+debug
enUS WARRIOR
{profile=default}
{}
HealthBar, CombatUpdate, NameText, [LevelText], RaidIcon, [ClassPowers], [CastBar], Highlight, PowerBar, [AbsorbBar], [Threat], Auras, Classification, Execute, Fading, GuildText, PlayerAnchor, [TankMode], BossMods, [CombatToggle], BarAnimation, ArenaID, Target

**Comment by kesava-wow** [comment]
Cast data doesn't exist on classic.
