### ISSUE TITLE
Debuffs don't show up (classic)

### ISSUE THREAD

**Issue by KumquatSherbet** [kesava-wow/kuinameplates2#416]
Using Kui ver 3. from github, playing WOW in South Korean realm
Debuffs don't show up on the health? bars...
Tried all the solutions written on the Internet (such as changing the duration to -1 etc...)

I don't know whether this is the problem of Language gap or something... But I can't make the debuffs show in any way.

Sorry I am new at Github,  I am not aware of the precise way of submitting issues...

**Comment by kesava-wow** [comment]
They'll be in the next version.
