### ISSUE TITLE
option to change class power colour

### ISSUE THREAD

**Issue by Toxicz101** [kesava-wow/kuinameplates2#42]
I was wondering if there are any plans to add more customization to the class power?

I know the beta version allows you to make the class power larger, but are there any plans to allow you to move it around, change the color, etc?

**Comment by SilverSeraphim** [comment]
+1 for changing color (maybe shape too?) on class power. It's a little hard to tell if those yellow combo-point circles are filled in or not sometimes on my rogue. It would be cool to allow progressive coloring as well. One-two combo points yellow, three-four orange, five or more red. Helps to know very easily at a glance if you're ready for a finisher.
