### ISSUE TITLE
Classic: No nameplate debuff timer and ClassicCodex's nameplate quest icon overlaps debuff icons

### ISSUE THREAD

**Issue by alecjpav** [kesava-wow/kuinameplates2#422]
Hello,

Thank you for this addon. I'm having an issue where debuff timers do not show up and the ClassicCodex quest icon that appears over a mob's nameplate overlaps the debuffs. You can see so here:

![WoWScrnShot_090219_090800](https://user-images.githubusercontent.com/28431403/64126441-9ada5600-cd62-11e9-8ab2-4e4300b22b8c.jpg)

I tried configuring it in the options but I don't see anything relevant to this. Also, both issues were resolved with Plater, so I know at least the debuff timer part isn't a limitation of Classic:

![WoWScrnShot_090219_092712](https://user-images.githubusercontent.com/28431403/64126802-112b8800-cd64-11e9-90a0-53a9d9d6e766.jpg)

However I vastly prefer the look of your addon. Is there a way I can configure it to do this, and if not is this something that can be added? Thank you very much!

**Comment by MysticalOS** [comment]
He just needs to add support for LibClassicDurations so timers can be added.

**Comment by kesava-wow** [comment]
Debuff timers are a limitation of classic, but there are workarounds. It'll be in a future version.

I can't do anything about another addon's icon. It should have its own options to move it.

**Comment by alecjpav** [comment]
> Debuff timers are a limitation of classic, but there are workarounds. It'll be in a future version.
> 
> I see what you mean about the icon, does it not have its own options to change the strata, or move the icon?

It does not, you can only enable and disable it in the options, so Plater is doing something to change it.
