### ISSUE TITLE
[classic] Cast bar dont show

### ISSUE THREAD

**Issue by FooX-X** [kesava-wow/kuinameplates2#423]
i dont view cast bar always 

classic-5 2.4
ruRU WARRIOR
{profile=default}
{bar_texture=Aluminium,cvar_enable=true,cvar_name_only=true,fade_avoid_combat=true,fade_avoid_execute_friend=true,fade_avoid_mouseover=true,fade_conditional_alpha=0.45,fade_non_target_alpha=1,fade_speed=0.5,font_face=Nimrod MT,font_size_normal=14,font_size_small=11,font_style=4,frame_height=15,frame_height_personal=6,frame_width=128,health_text=true,health_text_friend_dmg=4,health_text_friend_max=4,health_text_hostile_max=4,hide_names=false,level_text=true,name_colour_player_friendly={1=1,2=1,3=1},name_colour_white_in_bar_mode=false,name_vertical_offset=0,nameonly=false,nameonly_combat_friends=false,nameonly_friendly_players=false,tankmode_force_enable=true,target_arrows=true,target_glow=false,threat_brackets=true}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, [ClassPowers], [CastBar], Highlight, PowerBar, [AbsorbBar], [Threat], Auras, Classification, Execute, Fading, GuildText, PlayerAnchor, [TankMode], BossMods, [CombatToggle], BarAnimation, ArenaID, Target

**Comment by kesava-wow** [comment]
Cast data doesn't exist on classic. There are are workarounds I'll look at in future.
