### ISSUE TITLE
global error for line 179 error window daily

### ISSUE THREAD

**Issue by KaptinKazual** [kesava-wow/kuinameplates2#428]
..\AddOns\Quartz\modules\EnemyCasts.lua line 179: attempt to perform arithmetic on local 'castTime' (a nil value)

is the message under count.  each day, the count resets so while I may get 3 to 5 of them in a day.. next day it is 1.  here is whole bug window:

> Date: 2019-09-09 10:12:07
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Quartz\modules\EnemyCasts.lua line 179:
   attempt to perform arithmetic on local 'castTime' (a nil value)
Debug:
   Quartz\modules\EnemyCasts.lua:179: ?()
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.7
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  CTBuffMod, v8.2.0.5
  CTCore, v8.2.0.8
  CTExpenseHistory, v8.2.0.1
  CTLibrary, v8.2.0.5
  CTMailMod, v8.2.0.8
  CTMapMod, v8.2.0.8
  CTPartyBuffs, v8.2.0.1
  CTRaidAssist, v8.2.0.8
  CTTimer, v8.2.0.1
  CTViewport, v8.2.0.4
  Details, v
  DetailsTinyThreat, v
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  OmniCC, v8.2.4
  Prat30, v3.2.31
  Prat30Libraries, v
  Quartz, v3.5.1
  Questie, v4.0.18 BETA
  ShadowedUnitFrames, vv4.2-Classic-Beta7-1-g69bd965
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11302-1.0.7
  VendorPrice, v1.2.2
  WeakAuras, v2.14.6
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=49e)

>

**Comment by KaptinKazual** [comment]
just had this popup as well:   ..\AddOns\Quartz\modules\EnemyCasts.lua line 212:
   attempt to compare number with nil

**Comment by kesava-wow** [comment]
This is from Quartz, not KNP?

**Comment by KaptinKazual** [comment]
haha oops.
