### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dylan404** [kesava-wow/kuinameplates2#434]
Date: 2019-09-23 12:03:47
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\Kui_Nameplates\elements/healthbar.lua line 77:
   attempt to call field 'GetUnitHealth' (a nil value)
Debug:
   ...terface\AddOns\Kui_Nameplates\elements/healthbar.lua:77: UpdateHealth()
   ...terface\AddOns\Kui_Nameplates\elements/healthbar.lua:100: func()
   Kui_Nameplates\messages.lua:128: DispatchMessage()
   Kui_Nameplates\nameplate.lua:75: OnShow()
   Kui_Nameplates\nameplate.lua:68: OnUnitAdded()
   Kui_Nameplates\addon.lua:102: ?()
   Kui_Nameplates\addon.lua:145:
      Kui_Nameplates\addon.lua:142
Locals:
f = KuiNamePlate1 {
 LevelText = <unnamed> {
 }
 Highlight = <unnamed> {
 }
 UpdateMainBars = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:470
 parent = NamePlate1 {
 }
 UpdateHealthText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:780
 UpdateRaidIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1600
 UpdateFrameGlow = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:911
 bg = <unnamed> {
 }
 UpdateGuildText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:822
 NameText = <unnamed> {
 }
 guid = "Player-4477-017DB2B7"
 unit = "nameplate1"
 UpdateNameOnlyGlowSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:2190
 ThreatGlow = <table> {
 }
 NameOnlyGlow = <unnamed> {
 }
 RaidIcon = <unnamed> {
 }
 Auras = <table> {
 }
 ShowCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1134
 UpdateStateIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1562
 UpdateCastbarSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1283
 UpdateFrameGlowSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:966
 ThreatBrackets = <table> {
 }
 UpdateFrameSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:398
 UpdateAuras = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1708
 SpellIcon = <unnamed> {
 }
 SpellIconSetWidth = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1104
 HealthText = <unnamed> {
 }
 StateIcon = <unnamed> {
 }
 handler = <table> {
 }
 GuildText = <unnamed> {
 }
 elements = <table> {
 }
 animated_bars = <table> {
 }
 UpdateHighlight = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:433
 0 = <userdata>
 UpdateCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1241
 PowerBar = <unnamed> {
 }
 SpellName = <unnamed> {
 }
 HideCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1178
 UpdateSpellNamePosition = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1279
 UpdatePowerBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:502
 SpellShield = <unnamed> {
 }
 UpdateNameTextPosition = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:715
 CastBar = <unnamed> {
 }
 UpdateStateIconSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1583
 UpdateThreatBrackets = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:2083
 TargetGlow = <unnamed> {
 }
 HealthBar = <unnamed> {
 }
 CastBarUpdateFrame = <unnamed> {
 }
 BossModAuraFrame = <unnamed> {
 }
 UpdateLevelText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:730
 UpdateNameText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:680
 state = <table> {
 }
 cast_state = <table> {
 }
}
show = true
(*temporary) = <table> {
 personal = false
}
(*temporary) = <table> {
 personal = false
}
(*temporary) = nil
(*temporary) = "nameplate1"
(*temporary) = "attempt to call field 'GetUnitHealth' (a nil value)"
RMH = <table> {
 IsUnitMob = <function> defined @Interface\AddOns\RealMobHealth\Core.lua:100
 CreatureHealthOverrides = <table> {
 }
 IsMobGUID = <function> defined @Interface\AddOns\RealMobHealth\Core.lua:94
 GetHealth = <function> defined @Interface\AddOns\RealMobHealth\Core.lua:105
}
addon = <unnamed> {
 0 = <userdata>
 ui_print = <function> defined @Interface\AddOns\Kui_Nameplates\addon.lua:57
 DispatchMessage = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:108
 uiscale = 0.533333
 Frames = <function> defined @Interface\AddOns\Kui_Nameplates\addon.lua:60
 NewElement = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:564
 Nameplate = <table> {
 }
 NewPlugin = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:527
 USE_BLIZZARD_PERSONAL = false
 plugins = <table> {
 }
 GetPlugin = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:557
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnFontManager, v1.0.0     
  ArkInventoryClassic, v10004
  ArkInventoryClassicRules, v10000
  ArkInventoryClassicRulesExample, v10000
  ArkInventoryClassicSearch, v10000
  Atlas, v1.13.0
  AtlasLootClassic, vv1.1.12
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.7
  BasicMinimap, vv1-classic
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterAlign, v
  ClassicCodex, v1.2.2
  ClassicWorldMapEnhanced, v1.0-Release
  dashingDismount, v
  DBMCore, v1.13.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r026
  Details, v
  DetailsTinyThreat, v
  eCastingBar, v1.3.0
  Enchantrix, v8.2.6411 (SwimmingSeadragon)
  ErrorFilter, vv3.6
  FasterLooting, v1.1.1
  Informant, v8.2.6374 (SwimmingSeadragon)
  kgPanels, v1.23
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  Masque, v8.2.7-Classic
  MasqueApathy, v8.2.6-Classic
  MasqueAzerite, v1.0
  MasqueOnyx, v8.0.0
  MasqueRenaitre, vv7.0.3
  MaxCam, vv2.3.0
  ModernQuestWatch, v1.0.9
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  NugCast, v1.13.3
  OmniCC, v8.2.4
  Prat30, v3.7.36
  Prat30Libraries, v
  QuestLogEx, v1.2
  RealMobHealth, v1.0
  SellJunk, v3.0.20
  ShadowedUnitFrames, vv4.2-Classic-Beta3
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TinyTooltip, v8.2.1
  TitanClassic, v1.1.0.11302
  TitanClassicAmmo, v1.1.0.11302
  TitanClassicBag, v1.1.0.11302
  TitanClassicClock, v1.1.0.11302
  TitanClassicGold, v1.1.0.11302
  TitanClassicLootType, v1.1.0.11302
  TitanClassicPerformance, v1.1.0.11302
  TitanClassicRegen, v1.1.0.11302
  TitanClassicRepair, v1.1.0.11302
  TitanClassicVolume, v1.1.0.11302
  TitanClassicXP, v1.1.0.11302
  UIScaler, v5.2.0.4
  VendorPrice, v1.2.6
  WeakAuras, v2.14.6
  WIM, v3.7.35
  BlizRuntimeLib_deDE v1.13.2.11302 <none>
  (ck=87d)

**Comment by kesava-wow** [comment]
I think you have a very old version of RealMobHealth? Try getting the latest version from here: https://www.curseforge.com/wow/addons/real-mob-health/files.

(Regardless, that commit is now in the latest beta: https://www.curseforge.com/wow/addons/kuinameplates/files)
