### ISSUE TITLE
WoW Retail Issues 9/24/19

### ISSUE THREAD

**Issue by Hakamaori** [kesava-wow/kuinameplates2#435]
These issues happened after todays content patch.

Issue #1:
`x1  ...ates\lib\LibClassicCasterino\LibClassicCasterino-13.lua:482: table index is nil
Stack: ...ates\lib\LibClassicCasterino\LibClassicCasterino-13.lua:482: in main chunk
Time: 2019/09/24 20:36:13 Index: 1/6
RealUI Version: 2.1.0
Locals:
MAJOR = "LibClassicCasterino"
MINOR = 13
lib = <table> {
    casters = <table> {}
    UnitCastingInfo = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:238
    callbacks = <table> {}
    RegisterCallback = <function> defined @RealUI_Bugs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
    movecheckGUIDs = <table> {}
    UnregisterCallback = <function> defined @RealUI_Bugs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
    frame = <unnamed> {}
    UnitChannelInfo = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:255
    UnregisterAllCallbacks = <function> defined @RealUI_Bugs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
}
f = <unnamed> {
    0 = <userdata>
    COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:134
    UNIT_SPELLCAST_START = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:269
    UNIT_SPELLCAST_CHANNEL_START = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:269
    UNIT_SPELLCAST_DELAYED = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:269
    UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:269
    UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:269
    UNIT_SPELLCAST_STOP = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:269
    UNIT_SPELLCAST_INTERRUPTED = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:269
    UNIT_SPELLCAST_FAILED = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:269
}
callbacks = <table> {
    recurse = 0
    events = <table> {}
    OnUsed = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:283
    Fire = <function> defined @RealUI_Bugs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
    OnUnused = <function> defined @Kui_Nameplates\lib\LibClassicCasterino\LibClassicCasterino.lua:301
}
casters = <table> {}
movecheckGUIDs = <table> {}
MOVECHECK_TIMEOUT = 4
UnitGUID = <function> defined =[C]
bit_band = <function> defined =[C]
GetTime = <function> defined =[C]
CastingInfo = nil
ChannelInfo = nil
GetUnitSpeed = <function> defined =[C]
COMBATLOG_OBJECT_TYPE_PLAYER = 1024
COMBATLOG_OBJECT_REACTION_FRIENDLY = 16
classCasts = <table> {
    10468 = 1.500000
    24239 = 1
    10216 = 3
    126 = 5
    10605 = 2.500000
    19943 = 1.500000
    17923 = 1.500000
    5784 = 3
    25297 = 3.500000
    759 = 3
    9858 = 2
    25307 = 3
    25309 = 2
    25311 = 2
    688 = 10
    17951 = 3
    17953 = 3
    982 = 10
    20755 = 3
    20757 = 3
    6366 = 3
    20773 = 10
    17727 = 5
    28270 = 1.500000
    13819 = 3
    25357 = 3
    10140 = 3
    3552 = 3
    23214 = 3
    10912 = 3
    10054 = 3
    8690 = 10
    14327 = 1.500000
    18658 = 1.500000
    2641 = 5
    1002 = 2
    20904 = 3
    12826 = 1.500000
    9853 = 1.500000
    1842 = 2
    10623 = 2.500000
    20777 = 10
    556 = 10
    691 = 10
    9912 = 2
    2645 = 3
    6196 = 2
    17924 = 4
    25292 = 2.500000
    17928 = 2
    10934 = 2.500000
    25298 = 3.500000
    15208 = 3
    4068 = 1
    25304 = 3
    25306 = 3.500000
    6064 = 3
    6201 = 3
    10053 = 3
    6202 = 3
    25316 = 3
    17952 = 3
    23161 = 3
    10947 = 1.500000
    20752 = 3
    10876 = 3
    20756 = 3
    2053 = 2.500000
    15261 = 3.500000
    10318 = 2
    25314 = 3
    10955 = 1.500000
    10917 = 1.500000
    20770 = 10
    10207 = 1.500000
    693 = 3
    17728 = 5
    10326 = 1.500000
    28612 = 3
    20748 = 2
    28023 = 3
    18960 = 10
    9901 = 1.500000
    11729 = 3
    11730 = 3
    6215 = 1.500000
    11605 = 1.500000
    2362 = 5
    712 = 10
    697 = 10
    1122 = 2
    18647 = 1.500000
    11726 = 3
}
classChannels = <table> {
    13544 = 5
    9863 = 9.500000
    11700 = 4.500000
    17402 = 9.500000
    1515 = 20
    126 = 45
    11678 = 7.500000
    12051 = 8
    746 =`

Issue #2:
`x1  ...dOns\Kui_Nameplates\lib\LibClassicDurations-17\core.lua:147: table index is nil
Stack: ...dOns\Kui_Nameplates\lib\LibClassicDurations-17\core.lua:147: in function 'Spell'
...ameplates\lib\LibClassicDurations-17\classAbilities.lua:71: in main chunk
Time: 2019/09/24 20:36:13 Index: 2/6
RealUI Version: 2.1.0
Locals:
id = 26635
opts = <table> {
    type = "BUFF"
    duration = 10
}
lastRankID = 26635
spellName = nil
(*temporary) = <table> {
    Free Action = 6615
    Mind Amplification Dish = 13181
    Goblin Rocket Boots = 8892
    Shadow Reflector = 23132
    Invulnerability = 3169
    Freedom = 9774
    Gnomish Rocket Boots = 13141
    Running Speed = 9175
    Goblin Mortar = 13237
    Mithril Insignia = 12733
    Damage Absorb = 23991
    Recently Bandaged = 11196
    Tidal Charm = 835
    Spell Vulnerability = 23605
    Restoration = 11359
    Self Invulnerability = 16621
    Thorium Grenade = 19769
    Fire Reflector = 23097
    Abolish Poison = 14253
    Aura of Protection = 23506
    Frost Reflector = 23131
    The Burrower's Shell = 29506
    Flash Bomb = 5134
    Flee = 5024
    Berserking = 23505
    Reckless Charge = 13327
    Sleep = 1090
    Net-o-Matic = 16566
    Dazed = 1604
    Poison Mushroom = 6727
    Living Free Action = 24364
    Speed = 14530
}
(*temporary) = "number"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"
GetSpellInfo = <function> defined =[C]
spellNameToID = <table> {
    Free Action = 6615
    Mind Amplification Dish = 13181
    Goblin Rocket Boots = 8892
    Shadow Reflector = 23132
    Invulnerability = 3169
    Freedom = 9774
    Gnomish Rocket Boots = 13141
    Running Speed = 9175
    Goblin Mortar = 13237
    Mithril Insignia = 12733
    Damage Absorb = 23991
    Recently Bandaged = 11196
    Tidal Charm = 835
    Spell Vulnerability = 23605
    Restoration = 11359
    Self Invulnerability = 16621
    Thorium Grenade = 19769
    Fire Reflector = 23097
    Abolish Poison = 14253
    Aura of Protection = 23506
    Frost Reflector = 23131
    The Burrower's Shell = 29506
    Flash Bomb = 5134
    Flee = 5024
    Berserking = 23505
    Reckless Charge = 13327
    Sleep = 1090
    Net-o-Matic = 16566
    Dazed = 1604
    Poison Mushroom = 6727
    Living Free Action = 24364
    Speed = 14530
}
spells = <table> {
    3169 = <table> {}
    23451 = <table> {}
    29506 = <table> {}
    11196 = <table> {}
    4068 = <table> {}
    14253 = <table> {}
    26740 = <table> {}
    11359 = <table> {}
    1090 = <table> {}
    23097 = <table> {}
    25746 = <table> {}
    25747 = <table> {}
    25750 = <table> {}
    13099 = <table> {}
    19769 = <table> {}
    23991 = <table> {}
    16621 = <table> {}
    5134 = <table> {}
    5024 = <table> {}
    6615 = <table> {}
    9774 = <table> {}
    2379 = <table> {}
    8892 = <table> {}
    13141 = <table> {}
    16566 = <table> {}
    9175 = <table> {}
    6727 = <table> {}
    13237 = <table> {}
    13138 = <table> {}
    24364 = <table> {}
    12733 = <table> {}
    23506 = <table> {}
    13327 = <table> {}
    23505 = <table> {}
    1604 = <table> {}
    23493 = <table> {}
    835 = <table> {}
    23131 = <table> {}
    23132 = <table> {}
    13181 = <table> {}
    14530 = <table> {}
    23605 = <table> {}
}
`

Issue #3:

`x1  ...dOns\Kui_Nameplates\lib\LibClassicDurations-17\core.lua:175: table index is nil
Stack: ...dOns\Kui_Nameplates\lib\LibClassicDurations-17\core.lua:175: in function <...dOns\Kui_Nameplates\lib\LibClassicDurations\core.lua:170>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>
Time: 2019/09/24 20:36:18 Index: 4/6
RealUI Version: 2.1.0
Locals:
dataTable = <table> {
    28616 = 30
    24713 = 3600
    16587 = 600
    7236 = 3600
    7252 = 3600
    14534 = 300
    16843 = 4
    7300 = 1800
    21066 = 10
    25289 = 120
    17227 = 120
    7396 = 30
    14822 = 15
    17483 = 6
    17547 = 5
    10855 = 10
    10951 = 600
    26121 = 8
    15366 = 3600
    15398 = 8
    22666 = 6
    22730 = 600
    15494 = 10
    7764 = 1800
    7812 = 30
    15654 = 18
    7844 = 1800
    19275 = 15
    11719 = 30
    15878 = 3
    27721 = 3600
    11879 = 5
    8052 = 12
    8068 = 1800
    8100 = 1800
    8116 = 1800
    24394 = 3
    16326 = 600
    4101 = 6
    16460 = 1800
    20619 = 10
    4149 = 10
    2091 = 12
    8392 = 10
    12551 = 10
    21067 = 10
    8552 = 120
    17292 = 30
    543 = 30
    17484 = 30
    17548 = 3600
    553 = 30
    12967 = 15
    30089 = 3600
    8936 = 21
    9032 = 30
    18124 = 27
    9128 = 120
    9192 = 120
    26634 = 604800
    9256 = 10
    22667 = 15
    22731 = 27
    22859 = 5
    589 = 18
    13543 = 5
    18956 = 30
    595 = 30
    23179 = 1200
    9576 = 10
    4805 = 15
    603 = 60
    605 = 60
    9736 = 30
    27722 = 3600
    9800 = 60
    19660 = 60
    9896 = 12
    19852 = 300
    24011 = 10
    9992 = 10
    24203 = 30
    14183 = 10
    20236 = 120
    20300 = 10
    14279 = 8
    28618 = 1
    24587 = 10
    16461 = 1800
    20620 = 300
    16717 = 5
    14535 = 300
    10472 = 8
    29194 = 120
    21068 = 24
    2651 = 15
    17165 = 3
    17293 = 8
    5365 = 20
    673 = 3600
    5413 = 120
    10856 = 8
    10888 = 8
    17741 = 60
    10952 = 600
    687 = 1800
    689 = 5
    18125 = 600
    5573 = 8
    699 = 5
    22412 = 30
    703 = 18
    2819 = 12
    707 = 15
    709 = 5
    18765 = 20
    22924 = 10
    18957 = 30
    5781 = 30
    23244 = 4
    731 = 8
    2947 = 180
    5909 = 600
    19597 = 900
    745 = 10
    16071 = 300
    12040 = 30
    755 = 10
    16231 = 120
    3043 = 20
    20301 = 10
    6117 = 1800
    16359 = 30
    8233 = 1.500000
    24716 = 3
    775 = 8
    6213 = 15
    6229 = 30
    12520 = 4
    785 = 20
    3147 = 12
    17038 = 1200
    3163 = 3600
    17230 = 300
    8649 = 30
    6405 = 180
    3219 = 3600
    25804 = 900
    12968 = 15
    13032 = 60
    3267 = 7
    6581 = 10
    13224 = 15
    829 = 30
    833 = 10
    835 = 3
    837 = 6
    839 = 30
    18702 = 60
    6741 = 20
    3387 = 120
    849 = 60
    851 = 10
    853 = 3
    855 = 30
    3427 = 300
    6869 = 2
    3443 = 15
    863 = 60
    865 = 8
    867 = 30
    13896 = 15
    871 = 10
    23885 = 8
    877 = 30
    7045 = 60
    14120 = 30
    885 = 120
    3547 = 8
    24333 = 2
    7125 = 120
    14280 = 8
    28620 = 2
    3603 = 15
    10345 = 20
    905 = 600
    3627 = 12
    3635 = 6
    10473 = 8
    3651 = 10
    25165 = 15
    29388 = 12
    7365 = 30
    3699 = 10
    14888 = 1800
    10857 = 35
    3747 = 30
    17743 = 120
    10953 = 15
    945 = 600
    11113 = 6
    7621 = 10
    22478 = 15
    11273 = 6
    11305 = 15
    22734 = 30
    15656 = 15
    23182 = 900
    11657 = 20
    15784 = 60
    11721 = 300
    15848 = 1800
    23694 = 5
    15976 = 10
    19727 = 3600
    23886 = 8
    8037 = 8
    8053 = 12
    1009 = 5
    16168 = 20
    8101 = 1800
    8117 = 1800
    4067 = 2
    20303 = 10
    4083 = 30
    28621 = 2
    4102 = 15
    20559 = 6
    4134 = 10
    1038 = 300
    4166 = 3
    8362 = 20
    24974 = 12
    12521 = 3
    1058 = 12
    1062 = 15
    29325 = 25
    8554 = 2
    17168 = 10
    8650 = 30
    1086 = 1800
    1090 = 30
    1094 = 15
    1098 = 300
    25806 = 30
    17680 = 60
    12969 = 15
    8938 = 21
    1126 = 1800
    1130 = 120
    1138 = 60
    22415 = 10
    22479 = 6
    29252 = 5
    301100 = 3
    22735 = 7200
    19710 = 900
    22863 = 10
    31562 = 6
    31466 = 1
    9482 = 30
    13951 = 20
    23183 = 12
    9578 = 10
    31316 = 0.100000
    13737 = 5
    27534 = 6
    19408 = 8
    9738 = 120
    29220 = 300
    30918 = 1
    9834 = 12
    28011 = 120
    9898 = 30
    9930 = 30
    27556 = 15
    30805 = 10
    28754 = 15
    28825 = 8
    30441 = 30
    24335 = 12
    24596 = 120
    14275 = 20
    28622 = 60
    10250 = 30
    20560 = 6
    20624 = 3600
    16593 = 120
    30336 = 7200
    1302 = 45
    24975 = 12
    29134 = 5
    5254 = 30
    18791 = 1800
    30297 = 1800
    5302 = 5
    30285 = 15
    30238 = 1800
    29198 = 120
    5366 = 20
    30167 = 600
    10794 = 30
    30165 = 10
    30113 = 30
    10890 = 8
    17745 = 10
    25999 = 1
    30112 = 2
    17937 = 300
    30110 = 604800
    30109 = 5
    30095 = 8
    18193 = 600
    30094 = 8
    30092 = 8
    30090 = 3600
    11274 = 6
    30088 = 3600
    30082 = 3
    22736 = 600
    15497 = 4
    1430 = 12
    30081 = 300
    15593 = 8
    30080 = 300
    5782 = 10
    1450 = 1800
    11328 = 3600
    11658 = 15
    1462 = 30
    5862 = 1800
    12097 = 20
    23568 = 8
    30002 = 6
    23696 = 8
    30001 = 8
    1490 = 300
    23888 = 8
    5990 = 8
    29998 = 21
    12042 = 15
    20223 = 10
    29915 = 10
    29910 = 1
    24336 = 12
    20305 = 30
    16329 = 600
    16361 = 1.5`

**Comment by kesava-wow** [comment]
You're using an alpha or one of the classic releases. Use 2.24 on retail (https://www.curseforge.com/wow/addons/kuinameplates/files/2730194)
