### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by a268-Beefy** [kesava-wow/kuinameplates2#446]
No idea what is wrong with it but BugGrabber reports me an Error:

2x Kui_Nameplates_Auras\auras-Ауры.lua:8: Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'KuiNameplates'.
[C]: ?
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0-12.lua:155: in function `GetAddon'
Kui_Nameplates_Auras\auras-Ауры.lua:8: in main chunk

Locals:
(*temporary) = "Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'KuiNameplates'."

**Comment by kesava-wow** [comment]
Kui_Nameplates_Auras is long obsolete. Delete it.
