### ISSUE TITLE
New DBM threat lib interfering with Kui nameplates

### ISSUE THREAD

**Issue by beriah** [kesava-wow/kuinameplates2#448]
https://github.com/DeadlyBossMods/DeadlyBossMods/issues/100#issuecomment-569851013

What untargeted, non-player nameplates look like: 
![385cI](https://user-images.githubusercontent.com/1399263/71621947-e860b580-2bd2-11ea-8da7-94daf616d759.png)

**Comment by rbtwrrr** [comment]
Should be fixed in the latest beta: https://www.curseforge.com/wow/addons/kuinameplates/files/2852488

**Comment by beriah** [comment]
All fixed, cheers.
