### ISSUE TITLE
Kui Nameplates fails to show companion experience bar

### ISSUE THREAD

**Issue by denisbider** [kesava-wow/kuinameplates2#449]
Without Kui Nameplates, some types of targets show a companion experience bar. Most relevantly right now, this includes the Aqir larva or hatchling in Uldum, most importantly on the quest [Aqir Instincts](https://www.wowhead.com/quest=58830/aqir-instincts#comments). With Kui Nameplates, the Aqir hatchling's experience bar is completely hidden, and the player has no way to observe progress on this quest. The player has to know to disable Kui Nameplates during this quest, which can be difficult because there is no indication what add-on is hiding information, or that important information is being hidden.

Other types of targets affected by this issue include Nazjatar companions and the Honeyback Harvester hatchling.

**Comment by teqnodude** [comment]
I hope this gets resolved.
