### ISSUE TITLE
Suggestion: Allow x coordiante horizontal positioning between level and health text

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates2#45]
I would love to be able to put the text for level to the left of the name plate and the health amount to the right instead of having them only move vertically on the same text element.

If we could either have them as separate elements that we could adjust the x (horizontal) positioning or have the ability to space them apart horizontally, that would make my day ;)

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplatesextras/issues/11
