### ISSUE TITLE
Thing From Beyond nameplate not showing

### ISSUE THREAD

**Issue by zmoose** [kesava-wow/kuinameplates2#451]
When running more than 40 corruption in BFA a "Thing From Beyond" can sometimes spawn chasing you and dealing damage if it hits you.  I'm not seeing a nameplate appear for this mob.  Is there a setting I'm missing or does something need to be added to this addon to allow it to show up?  I've seen videos/screen shots of other nameplate addons and they seem to show the nameplate for this mob.

**Comment by kesava-wow** [comment]
If nameplates don't appear, it's usually a setting in the game (I.e. not in KNP), or Blizzard didn't flag that mob to have a nameplate. All KNP does is skin the default nameplates; it can't truly hide them or define what mobs they appear on.

See the checkboxes for nameplates under Esc > Interface > Names. That mob might, for instance, be flagged as "minor", if you have that unchecked. 

If you can only see the nameplate with KNP disabled, then it's likely that KNP would be throwing a script error. I'd need to see that to help (install bugsack and buggrabber to keep track of script errors).

**Comment by zmoose** [comment]
Thanks for the reply!  I have bugsack installed and will check the blizzard nameplate settings and try to replicate with and without KNP to see what happens and report back here.

**Comment by zmoose** [comment]
Ok I was able to resolve this. It is in fact a default blizzard option that needed to be changed.
ESC > Interface > Names > Enemy Units (V) > Minions (enable this)
![image](https://user-images.githubusercontent.com/10065577/74995483-a60b6600-5416-11ea-8038-e39031dc59e2.png)
