### ISSUE TITLE
Increase Cvars in Classic?

### ISSUE THREAD

**Issue by sakrax** [kesava-wow/kuinameplates2#453]
Not sure if its a bug or something else is messing it up but if I increase my Cvars range it doesnt actually increase the range (I believe it did back in normal WoW) but playing classic right now and its really annoying to have the nameplates pop up 10m infront of you...

Is there a way to fix this?

**Comment by kesava-wow** [comment]
That CVar isn't modifiable on classic. (And I didn't get around to hiding things that don't work yet)
