### ISSUE TITLE
Nameplate Issues

### ISSUE THREAD

**Issue by HayleyGeek** [kesava-wow/kuinameplates2#456]
I cannot turn off NPC namteplates, the ones that are just random and not interactable. When KUI overrides it is just a mound of nameplates on top of one another, I have tried every combination between blizzard and kui settings and nothing fixes it. It is too busy on the screen. When i turn off all npc or turn on only interactable and hostile it reverts to blizzards nameplates and text with no override. I have also reinstalled and everything, all is up to date. Thanks

**Comment by kesava-wow** [comment]
I need to see screenshots. But it sounds like you have another addon, or addons, providing their own nameplates. If you're using a pack like elvui, they usually have a nameplate module which you'll need to disable in their options.

The in-world floating names (which aren't nameplates, but, sure, I don't know what to call them either) are controlled by the "NPC Names" drop-down you already found. That option doesn't affect nameplates (unless they choose to obey it - KNP only uses it to show or hide names on health **bars**).
