### ISSUE TITLE
Debuffs attached to nameplates in dungeons

### ISSUE THREAD

**Issue by nnebb** [kesava-wow/kuinameplates2#458]
Is it possible to disable these debuffs showing? I've tried checking the "blacklist all other auras" box and I've tried disabling auras completely but they still show up.

![vFueA4vM6O](https://user-images.githubusercontent.com/46135799/83982208-b50e1980-a91c-11ea-96de-0e6748962e6c.png)

**Comment by kesava-wow** [comment]
These are the default nameplates (the only type available in dungeons). There aren't any options for them. Thankfully ~I think~ nameplate modifications in dungeons are being re-enabled in shadowlands.
