### ISSUE TITLE
Neutral npcs not showing in yellow

### ISSUE THREAD

**Issue by Rhess86** [kesava-wow/kuinameplates2#459]
Hi, sorry if isnt an issue but some npcs that are neutral, which should have yellow names are being shown as green.
The monsters are fine, they show yellow, but npcs dont.
Is there a way to fix or add the option please?
Thanks.

**Comment by Rhess86** [comment]
Thanks, worked like a charm.
I dont want to open a new ticket so if you can answer here i'd really appreciate.
Is there an option to disable auras on friendly players/npc?
im siting on the city and i see mages with presense of mind aura all the time flying around.
To elaborate a bit, i dont have healthbars for friendly players, just names, and seeing those auras are quite weird.
Thanks in advance.

**Comment by kesava-wow** [comment]
`/knp set auras_on_friends false` but the aura frames should only be showing things the game has flagged as important. I'm pretty sure PoM isn't whitelisted by default.

**Comment by Rhess86** [comment]
Thanks for the quick response.
So far i've seen pom, ignite and bestial wrath on friendly players, so it appear to be only a few that are showing up.

**Comment by kesava-wow** [comment]
That (the aura) isn't KNP. I don't recognise what it is, either.

**Comment by Rhess86** [comment]
Well, now that's awkard lol it only shows when i use knp, i'm currently messing around with knp, plater and neatplates to see which one is better for me and that only appears when using knp, even elvui builtin doesnt show them. (ofc im only using one at the time)
Thanks for the awesome support, im gonna try to find the culprit on my own.
