### ISSUE TITLE
Suggestion: nameonly mode behaviour

### ISSUE THREAD

**Issue by itcotta** [kesava-wow/kuinameplates2#46]
I really love this mode for healing, being able to easily see where friendly targets are is really useful, there is only one thing about this mode I wish could be changed though and that is to be able to keep nameonly mode at all times. Currently whenever nameonly mode is activated and I have to target a friendly player the friendly target's HP bar is shown, so my question is if this is intended? if it's not would it be asking too much if you could add an option to keep friendly players hp bars hidden even when im targetting them in nameonly mode?
Thank you and you're doing an awesome job with this addon! :)

**Comment by kesava-wow** [comment]
Intended, without it there'd be no difference between the target and anyone else.
https://github.com/kesava-wow/kuinameplatesextras/issues/9

Thanks.
