### ISSUE TITLE
[Beta] Addon fails to hide Blizz nameplates in 9.0 (fix provided)

### ISSUE THREAD

**Issue by jcai1** [kesava-wow/kuinameplates2#464]
In Shadowlands Beta the `nameplate.UnitFrame` is populated [later than usual](https://github.com/Gethe/wow-ui-source/blob/259c1520902c28cb4d3a7d4596e2ace1d07776ca/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua#L101-L102), so Kui's [Blizzard hider](https://github.com/kesava-wow/kuinameplates2/blob/2af35a9f8ba74b62e5cdd90ea2674da8dca12cd8/Kui_Nameplates/hook.lua#L45-L47) will fail silently.

My (inelegant) fix is to replace in `addon.lua`,

    addon:RegisterEvent('NAME_PLATE_CREATED')

with

    hooksecurefunc(NamePlateDriverFrame, "AcquireUnitFrame", function(_, frame) addon:NAME_PLATE_CREATED(frame) end)

**Comment by kesava-wow** [comment]
Thanks <3
