### ISSUE TITLE
Colours keep resetting

### ISSUE THREAD

**Issue by Hedgefather** [kesava-wow/kuinameplates2#465]
Hi, 

When I change colours in my KUI name only mode, my other colours reset. For example, if I'm setting target glow to green, it works, when I go to set mouseover glow to any other colour, my target glow resets to the default blue. 

This is also happening with Hostile and Hostile Player, I'm trying to set them to two different reds that are also different from the DK/Pally colours. I can set either properly, but as soon as I try to change the colour of the other one, the first one resets. 

I've added on the colourpickerplus as well and this hasn't seemed to help. I'm confused as to what is happening because my addon was working just fine before the recent update. 

Thanks,

The Hedgefather

**Comment by kesava-wow** [comment]
Thanks, this is fixed in beta-talking-horse-sprinting-whale.

**Comment by Hedgefather** [comment]
I'm sorry, but I have no idea what that means. I found a work-around though, change one colour, then log out, change another colour, then log out again, and so on so forth.

**Comment by kesava-wow** [comment]
It means it's fixed. I fixed it. Thanks. It'll work properly in the next version.
