### ISSUE TITLE
Widget for Nazjatar Follower Exp bar unskinned

### ISSUE THREAD

**Issue by Dajova** [kesava-wow/kuinameplates2#466]
So i noticed that this bar is still not skinned. Makes it a bit awkvard when watching stuff like this:
![image](https://i.imgur.com/Pb4S8uw.png)
![image2](https://i.imgur.com/9BgpRED.png)
It uses the same widget as far as i understand it.

**Comment by kesava-wow** [comment]
There are various nameplate widgets in shadowlands. I don't intend to try to re-implement them or modify them.
