### ISSUE TITLE
[request] No personal raid icon over head

### ISSUE THREAD

**Issue by freche** [kesava-wow/kuinameplates2#47]
I would love if there was an option so that if I have a raid icon on myself, it wouldn't pop up above my head when the personal nameplate fades (the icon should still be on me so others can see it, I just don't have to see it myself).

My friend and I usually mark ourselves when we are playing to easier keep track of where we have eachother and this feature would be so very very appreciated!

**Comment by kesava-wow** [comment]
It isn't possible to modify the floating raid icons, unfortunately.

**Comment by freche** [comment]
Maybe you don't have to modify them directly, the floating icon is moved to the nameplate when the nameplate is visible. Could it be possible to always show the personal nameplates?
And maybe even add an option to always show but fade to 1% alpha when out of combat.

**Comment by kesava-wow** [comment]
It isn't possible to tell the game to render the personal nameplate, either.
