### ISSUE TITLE
Suggestion: More options for auras

### ISSUE THREAD

**Issue by leobolin** [kesava-wow/kuinameplates2#48]
Moved this from /kuinameplates, sorry for the double post.

I'd love to see the following settings in the future:

- Option to change the aura icon offset
- Option to change how auras are sorted (I see you've already written the index_sort code, so it shouldn't require too much work? - I also think index_sort should be default rather than time_sort as having auras move around is generally bad as a multidotter)
- Option to change timer text and count text offset/positioning
- Option to change timer text color
- Option to turn decimals off for the timer

I'd also argue the default timer text settings - especially the colors - are really bad. They are really hard to read when you have to keep track of multiple dots on multiple targets. Might be something worth taking a look at.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplatesextras/issues/11
