### ISSUE TITLE
Twitch client (and others) not showing KuiNameplates in addons lists.

### ISSUE THREAD

**Issue by CamdenQ** [kesava-wow/kuinameplates2#480]
If you try to search for KuiNameplates in the Twitch client or others (such as WowUp), the CurseForge listing doesn't show. 

WowUp's "install from URL" doesn't even work.

Right now, manual install/update is the only option.

**Comment by kesava-wow** [comment]
It shows in Twitch for me and other people I've watched using it. Even if it wasn't I don't know what I could do to fix that; I don't control either of those services and I don't have some sort of option to enable it to show in clients that I've accidentally disabled or anything. On 14 Oct 2020 21:20, "Camden Q. Miller" <notifications@github.com> wrote:
If you try to search for KuiNameplates in the Twitch client or others (such as WowUp), the CurseForge listing doesn't show.
WowUp's "install from URL" doesn't even work.
Right now, manual install/update is the only option.

**Comment by CamdenQ** [comment]
It seems to have been a temporary issue that has resolved itself. I figured it was probably on Overwolf's end, but I just wanted to make it known.
