### ISSUE TITLE
UNIT_HEALTH_FREQUENT

### ISSUE THREAD

**Issue by Fringetastic** [kesava-wow/kuinameplates2#481]
Getting this message upon logging into the game.

`1x Kui_Nameplates\messages.lua:347: Attempt to register unknown event "UNIT_HEALTH_FREQUENT"
[string "=[C]"]: in function `RegisterEvent'
[string "@Kui_Nameplates\messages.lua"]:347: in function `RegisterEvent'
[string "@Kui_Nameplates\messages.lua"]:353: in function `RegisterUnitEvent'
[string "@Kui_Nameplates\elements/healthbar.lua"]:108: in function `OnEnable'
[string "@Kui_Nameplates\messages.lua"]:503: in function `Enable'
[string "@Kui_Nameplates\addon.lua"]:156: in function <Kui_Nameplates\addon.lua:127>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "UNIT_HEALTH_FREQUENT"
`

I went to see the version in-game, to ensure that I am using the most recent (wowup thinks I am) but then I see the only addon listed in blizz's Interface > AddOns list is Kui Spell List. However, in the AddOn list (from BetterAddonList) shows I have 5 Kui modules enabled, including Nameplates and Nameplates:Core.

**Comment by kesava-wow** [comment]
You're on an old version. Try manually downloading the most recent release for 9.0.1 from curse.On 14 Oct 2020 23:46, Fringetastic <notifications@github.com> wrote:
Getting this message upon logging into the game.
1x Kui_Nameplates\messages.lua:347: Attempt to register unknown event "UNIT_HEALTH_FREQUENT" [string "=[C]"]: in function RegisterEvent'
[string "@Kui_Nameplates\messages.lua"]:347: in function RegisterEvent' [string "@Kui_Nameplates\messages.lua"]:353: in function RegisterUnitEvent'
[string "@Kui_Nameplates\elements/healthbar.lua"]:108: in function OnEnable' [string "@Kui_Nameplates\messages.lua"]:503: in function Enable'
[string "@Kui_Nameplates\addon.lua"]:156: in function <Kui_Nameplates\addon.lua:127>
Locals:
(*temporary) =  {
0 = 
}
(*temporary) = "UNIT_HEALTH_FREQUENT"
`
I went to see the version in-game, to ensure that I am using the most recent (wowup thinks I am) but then I see the only addon listed in blizz's Interface > AddOns list is Kui Spell List. However, in the AddOn list (from BetterAddonList) shows I have 5 Kui modules enabled, including Nameplates and Nameplates:Core.
