### ISSUE TITLE
Error with friendly NPC nameplate inside instance

### ISSUE THREAD

**Issue by CMcFadyen** [kesava-wow/kuinameplates2#482]
It was in my garrison, with NPC nameplates only visible when they're selected.  Selecting an NPC gave this error:

2x Kui_Nameplates\hook.lua:24: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `HookScript'
[string "@Kui_Nameplates\hook.lua"]:24: in function <Kui_Nameplates\hook.lua:21>
[string "=[C]"]: in function `AcquireUnitFrame'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:114: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/6809f6f23036be36a76ff25f12715ab9d549b25f Thanks.
