### ISSUE TITLE
cant hover over elvui frames at times

### ISSUE THREAD

**Issue by rsblunden** [kesava-wow/kuinameplates2#483]
At times when I hover over some frames (my health bar, action bars, etc) it doesn't recognize that I am hovering over them.  When I tested turning on and off all addons and determined KUI is the issue.

**Comment by rsblunden** [comment]
after a bunch more trial and error, it just seemed like this was issue but in fact wasnt.  AtlasLoot was causing it, my apologies.

**Comment by kesava-wow** [comment]
Thanks.
