### ISSUE TITLE
Can't change Bar texture

### ISSUE THREAD

**Issue by Edvorn** [kesava-wow/kuinameplates2#484]
Screenshot: 
![image](https://user-images.githubusercontent.com/69559145/96198414-c26a8e80-0f22-11eb-8687-65a5aa58a6f7.png)

LUA Error:
Message: ...terface\AddOns\Kui_Nameplates_Core_Config\create.lua:229: attempt to call method 'SetBackdrop' (a nil value)
Time: Thu Oct 15 20:11:38 2020
Count: 2
Stack: ...terface\AddOns\Kui_Nameplates_Core_Config\create.lua:229: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Kui_Nameplates_Core_Config\create.lua"]:229: in function `callback'
[string "@Interface\AddOns\Kui_Nameplates_Core_Config\lib\SomeoneElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua"]:220: in function <...ElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua:159>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Kui_Nameplates_Core_Config\lib\SomeoneElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua"]:45: in function <...ElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua:34>
[string "@Interface\AddOns\Kui_Nameplates_Core_Config\lib\SomeoneElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua"]:297: in function <...ElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua:293>

Locals: self = <unnamed> {
 0 = <userdata>
 OnLeave = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:44
 Enable = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:175
 GetList = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\lib\SomeoneElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua:329
 bgMiddle = <unnamed> {
 }
 list = SomeoneElsesConfigDropdown1 {
 }
 button = <unnamed> {
 }
 selected = "Kui status bar"
 bgLeft = <unnamed> {
 }
 SetList = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\lib\SomeoneElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua:333
 Get = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:139
 GetValue = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\lib\SomeoneElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua:312
 bgRight = <unnamed> {
 }
 OnEnter = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:23
 labelText = <unnamed> {
 }
 Set = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:143
 items = <table> {
 }
 valueText = <unnamed> {
 }
 OnValueChanged = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:149
 initialize = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\create.lua:214
 env = "bar_texture"
 OnListButtonChanged = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\create.lua:227
 SetValue = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\lib\SomeoneElsesConfig-Dropdown\SomeoneElsesConfig-Dropdown.lua:316
 Disable = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:180
}
button = <unnamed> {
 0 = <userdata>
 value = "Blizzard"
 check = <unnamed> {
 }
 label = <unnamed> {
 }
}
item = <table> {
 value = "Blizzard"
 text = "Blizzard"
 selected = false
}
texture = "Interface\TargetingFrame\UI-StatusBar"
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 value = "Blizzard"
 check = <unnamed> {
 }
 label = <unnamed> {
 }
}
(*temporary) = <table> {
 bgFile = "Interface\TargetingFrame\UI-StatusBar"
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
LSM = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 SetDefault = <function> defined @Interface\AddOns\Kui_Nameplates_Core\lib\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:293
 GetDefault = <function> defined @Interface\AddOns\Kui_Nameplates_Core\lib\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:289
 LOCALE_BIT_ruRU = 2
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\Kui_Nameplates\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 SetGlobal = <function> defined @Interface\AddOns\Kui_Nameplates_Core\lib\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:280
 GetGlobal = <function> defined @Interface\AddOns\Kui_Nameplates_Core\lib\LibSharedMedia-3.0\LibSharedMedi

**Comment by kesava-wow** [comment]
Whoops. Thanks.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/55b16a84586d3a2617bd03582c2606efad44257d
