### ISSUE TITLE
Class power not shown for Protection Paladin

### ISSUE THREAD

**Issue by ncsibra** [kesava-wow/kuinameplates2#485]
After 9.0 I can't see my class power as a Protection Paladin, does not show any holy power.  
For other classes, like Feral Druid, it works fine.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/fafec40f150f867236fa478fc8b95fc77820aaf8

**Comment by ncsibra** [comment]
Thanks, it works now!
