### ISSUE TITLE
Lua Error "SetBackdrop"

### ISSUE THREAD

**Issue by Sinsei33** [kesava-wow/kuinameplates2#487]
So my buggrabber is spamming me with this lua-error. Maybe it helps.

9x Kui_Enemy_Colors\custom-Custom.lua:136: attempt to call method 'SetBackdrop' (a nil value)
[string "@Kui_Enemy_Colors\custom-Custom.lua"]:136: in main chunk

Locals:
folder = "Kui_Enemy_Colors"
ns = <table> {
}
addon = <unnamed> {
 NAME_PLATE_UNIT_REMOVED = <function> defined @Kui_Nameplates\addon.lua:117
 ui_print = <function> defined @Kui_Nameplates\addon.lua:59
 DispatchMessage = <function> defined @Kui_Nameplates\messages.lua:108
 Frames = <function> defined @Kui_Nameplates\addon.lua:62
 NewElement = <function> defined @Kui_Nameplates\messages.lua:564
 NewPlugin = <function> defined @Kui_Nameplates\messages.lua:527
 plugins = <table> {
 }
 GetPlugin = <function> defined @Kui_Nameplates\messages.lua:557
 layout = <table> {
 }
 NAME_PLATE_UNIT_ADDED = <function> defined @Kui_Nameplates\addon.lua:93
 MINOR = 5
 GetActiveNameplateForUnit = <function> defined @Kui_Nameplates\addon.lua:71
 NamePlateDriverFrame_AcquireUnitFrame = <function> defined @Kui_Nameplates\hook.lua:21
 Nameplate = <table> {
 }
 Layout = <function> defined @Kui_Nameplates\messages.lua:571
 GetNameplateForGuid = <function> defined @Kui_Nameplates\addon.lua:77
 PrintTrace = <function> defined @Kui_Nameplates\messages.lua:88
 0 = <userdata>
 UI_SCALE_CHANGED = <function> defined @Kui_Nameplates\addon.lua:135
 NAME_PLATE_CREATED = <function> defined @Kui_Nameplates\addon.lua:86
 MAJOR = 2
 PLAYER_LEAVING_WORLD = <function> defined @Kui_Nameplates\addon.lua:126
 print = <function> defined @Kui_Nameplates\addon.lua:55
 DEBUG_IGNORE = <table> {
 }
 HookNameplate = <function> defined @Kui_Nameplates\hook.lua:27
 GetNameplateForUnit = <function> defined @Kui_Nameplates\addon.lua:65
}
core = <table> {
 OnEnter = <function> defined @Kui_Nameplates_Core\hook.lua:152
 Scale = <function> defined @Kui_Nameplates_Core\config.lua:272
 CreateNameOnlyGlow = <function> defined @Kui_Nameplates_Core\create.lua:2125
 AurasButton_SetFont = <function> defined @Kui_Nameplates_Core\create.lua:1800
 LSMMediaRegistered = <function> defined @Kui_Nameplates_Core\create.lua:297
 NameOnlyUpdate = <function> defined @Kui_Nameplates_Core\create.lua:2329
 CreateAuras = <function> defined @Kui_Nameplates_Core\create.lua:1652
 LostTarget = <function> defined @Kui_Nameplates_Core\hook.lua:129
 layout = true
 Create = <function> defined @Kui_Nameplates_Core\hook.lua:23
 GainedTarget = <function> defined @Kui_Nameplates_Core\hook.lua:117
 CreateHighlight = <function> defined @Kui_Nameplates_Core\create.lua:458
 QuestUpdate = <function> defined @Kui_Nameplates_Core\hook.lua:162
 ShowNameUpdate = <function> defined @Kui_Nameplates_Core\create.lua:2061
 InitialiseElements = <function> defined @Kui_Nameplates_Core\create.lua:2338
 Auras_PostCreateAuraButton = <function> defined @Kui_Nameplates_Core\create.lua:1700
 HealthColourChange = <function> defined @Kui_Nameplates_Core\hook.lua:93
 CreateThreatBrackets = <function> defined @Kui_Nameplates_Core\create.lua:2014
 configChangedStateIcons = <function> defined @Kui_Nameplates_Core\create.lua:1472
 CreateGuildText = <function> defined @Kui_Nameplates_Core\create.lua:839
 PowerTypeUpdate = <function> defined @Kui_Nameplates_Core\hook.lua:99
 CreateQuestIcon = <function> defined @Kui_Nameplates_Core\create.lua:2049
 InitialiseFadeRules = <function> defined @Kui_Nameplates_Core\hook.lua:315
 SetAurasConfig = <function> defined @Kui_Nameplates_Core\create.lua:1809
 SetLocals = <function> defined @Kui_Nameplates_Core\create.lua:222
 configChangedTextOffset = <function> defined @

**Comment by kesava-wow** [comment]
This is coming from another addon, "Kui_Enemy_Colors", which hasn't been updated for shadowlands. That's not an addon I made so I can't fix it. Its last update was in 2017.
