### ISSUE TITLE
Name-only level text spam

### ISSUE THREAD

**Issue by SuperLeiyan** [kesava-wow/kuinameplates2#489]
Level-text in name-only mode gets longer at every update call.

![image](https://user-images.githubusercontent.com/5438286/96347985-22149580-10ed-11eb-8d34-b74ab03b5270.png)

**Comment by kesava-wow** [comment]
This should be fixed in the beta and alpha of KNP - if you're still on release, I believe it's caused by having /knp > name-only > "health colour" UNchecked (basically, I forgot to test that, whoops).
