### ISSUE TITLE
Request: Quest Icons

### ISSUE THREAD

**Issue by jlilly1227** [kesava-wow/kuinameplates2#490]
Quest icons next to nameplate for enemies needed for quest objectives

**Comment by kesava-wow** [comment]
already implemented, I'm doing some more work on it before exposing the option (e.g. making it movable)

**Comment by kesava-wow** [comment]
OH BY THE WAY, you can enable the quest icon in the current release but there aren't any options for it yet.

 /knp set show_quest_icon true
