### ISSUE TITLE
Class resources showing on *all* targets

### ISSUE THREAD

**Issue by stko-cmd** [kesava-wow/kuinameplates2#491]
Since 2.26.3d, my class resource (soul shards, runes, etc) show on _all_ target nameplates and not just attackable ones. Is there any way to revert it to only showing on attackable enemies? I don't need to see how many soul shards I have when I'm speaking to Auctioneer Jaxon. 😄

**Comment by kesava-wow** [comment]
(implemented in the future)

**Comment by stko-cmd** [comment]
Is it possible to have a toggle for friendly players?

**Comment by kesava-wow** [comment]
Sorry, yes, an option is already implemented in the next version (currently the beta or alpha).
