### ISSUE TITLE
Some nameplates are not showing.

### ISSUE THREAD

**Issue by Addvi777** [kesava-wow/kuinameplates2#497]
I have encountered this issue multiple times both in BFA prepatch and in Shadowlands beta. It happens randomly in different places. Sometimes it's just one mob in a pack.
https://i.imgur.com/YgwKBZX.png
Typing /rl fixes the issue.

beta-dancing-dik-dik-swimming-rhino 2.5
ruRU PALADIN
{profile=MyDefaultProfile}
{absorb_striped=false,auras_cd_size=20,auras_centre=false,auras_colour_long={1=0,2=1,3=0},auras_colour_medium={1=0,2=1,3=0},auras_colour_short={1=0,2=1,3=0},auras_count_size=20,auras_icon_minus_size=20,auras_icon_normal_size=34,auras_icon_squareness=0.7,auras_pulsate=false,auras_show_purge=false,auras_sort=1,bar_animation=1,bar_texture=Smooth v2,castbar_colour={1=1,2=0.565,3=0},castbar_detach_width=125,castbar_height=13,castbar_unin_colour={1=1,2=0,3=1},class_colour_enemy_names=true,cvar_clamp_bottom=0.22,cvar_clamp_top=0.21,cvar_max_distance=45,cvar_overlap_v=2.4,cvar_self_clamp_bottom=0.22,cvar_self_clamp_top=0.23,execute_enabled=false,fade_speed=0,font_size_normal=15,font_size_small=12,frame_height=15,frame_height_personal=17,frame_width=125,frame_width_minus=67,frame_width_personal=125,global_scale=1.5,hide_names=false,ignore_uiscale=true,name_vertical_offset=-2.5,powerbar_height=6,target_arrows=true,target_arrows_size=45,threat_brackets=true,use_blizzard_personal=true}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, ClassPowers, CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, [Execute], TankMode, Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target

**Comment by kesava-wow** [comment]
Do you have any lua errors along with this?

**Comment by kesava-wow** [comment]
Oh, and, do you have friendly nameplates enabled in instances, by any chance?

**Comment by Addvi777** [comment]
Seems like this issue was cause by ExRT NPA plugin. I turned it off and so far have not encountered any bugged nameplates.
