### ISSUE TITLE
The configuration interface does not display content.

### ISSUE THREAD

**Issue by kitekingw** [kesava-wow/kuinameplates2#507]
beta-caring-kookaburra-running-tamarin-6-gf151a89 2.5
zhCN MAGE
{profile=default}
{}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, [ClassPowers], CastBar, Highlight, PowerBar, [AbsorbBar], Threat, Auras, Classification, Execute, TankMode, Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target

The configuration interface does not display content.
<img width="598" alt="20201119080716" src="https://user-images.githubusercontent.com/73381353/99603482-59ed6080-2a3e-11eb-89fa-964619787bc2.png">

**Comment by kesava-wow** [comment]
There should be a lua error; I need to see that.

(And bear in mind if you've made modifications to a locale file, and you've forgotten a bit of syntax or something, that would cause this to happen.)

**Comment by kitekingw** [comment]
Message: ...erface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:877: CreateFrame(): Couldn't find inherited node "DialogHeaderTemplate"
Time: Mon Nov 23 22:23:40 2020
Count: 1
Stack: ...erface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:877: CreateFrame(): Couldn't find inherited node "DialogHeaderTemplate"
[C]: in function `CreateFrame'
...erface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:877: in function <...erface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:867>
...erface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:950: in function <...erface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:904>
...erface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:1156: in function `Initialise'
...terface\AddOns\Kui_Nameplates_Core_Config\create.lua:5: in main chunk
[C]: in function `LoadAddOn'
Interface\AddOns\Kui_Nameplates_Core\hook.lua:184: in function <Interface\AddOns\Kui_Nameplates_Core\hook.lua:166>
Interface\AddOns\Kui_Nameplates_Core\hook.lua:206: in function `?'
Interface\FrameXML\ChatFrame.lua:4695: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4356: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4392: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: (*temporary) = "Frame"
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 CreateDropDown = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:197
 CreateCheckBox = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:115
 CreateSeparator = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:477
 CreateColourPicker = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:424
 CreateSlider = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:313
 callback = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:861
 CreateButton = <function> defined @Interface\AddOns\Kui_Nameplates_Core_Config\helpers.lua:70
 minmax = <table> {
 }
 size = <table> {
 }
}
(*temporary) = "DialogHeaderTemplate"
