### ISSUE TITLE
Ignoring out of date plugin: FelExplosives

### ISSUE THREAD

**Issue by Erythros** [kesava-wow/kuinameplates2#509]
I stopped playing end of 2019. Now I got back for SL, so I updated all my plugins and hit the game.
I'm constantly running into this error. However, there's no addon update available.

![image](https://user-images.githubusercontent.com/2624183/99802367-43c7c900-2b40-11eb-8ae4-afbf527fc2fa.png)

Here's the `/knp dump`

```
2.26.3e 2.5+c
enUS DEATHKNIGHT
{profile=Tank}
{auras_cd_offset_x=-5,auras_cd_offset_y=10,auras_cd_size=25,auras_count_offset_x=0,auras_count_offset_y=0,auras_icon_minus_size=14,auras_icon_normal_size=41,auras_offset=26,castbar_colour={1=0,2=0.749,3=0.298},castbar_height=22,castbar_name_vertical_offset=0,castbar_unin_colour={1=0.8,2=0,3=0},classpowers_enable=false,cvar_clamp_top=0.08,cvar_enable=true,cvar_max_distance=55,fade_avoid_mouseover=true,fade_non_target_alpha=0.7,font_face=PT Sans Narrow,font_size_normal=20,font_size_small=18,frame_height=17,frame_width=144,mouseover_glow=true,name_vertical_offset=4,powerbar_height=4,tankmode_other_colour={1=1,2=0,3=0.055},tankmode_trans_colour={1=1,2=0.502,3=1},target_arrows=true,target_arrows_size=32,threat_brackets=true}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, [ClassPowers], CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, TankMode, Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target
```

Any solutions?

**Comment by kesava-wow** [comment]
You have the old version of the explosives script from here: https://github.com/kesava-wow/kuinameplates-customs/ (https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.explosives.lua)
These scripts need to be updated manually; you would've already done this before, unless someone just gave it to you. Alternatively, disable Kui_Nameplates_Custom.

**Comment by Erythros** [comment]
@kesava-wow it's been a while since I last did this. Of course, you were correct and I solved the problem.

Quick question: how can I have 2 custom scripts active?

I currently have `custom.explosives.lua` renamed to `custom.lua`.  I'd like to also add `custom.target-scale.lua`, but by renaming this one to `custom.lua` I'll lose the explosive one...
