### ISSUE TITLE
improve auras timer text visibility

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#51]

**Comment by leobolin** [comment]
Here's what my timers/stacks look like if you are looking for some inspiration:

![screen shot 2016-07-30 at 07 06 34](https://cloud.githubusercontent.com/assets/9146240/17274258/77bb83ae-56d9-11e6-9350-72dbd8b53f15.png)

**Comment by pierre-weceipt** [comment]
An alternative would be to have the same shadow on the aura as you have in the bli² interface (on cooldowns for example).

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/301b32f926f824192e0b638da88c54cd86330e49

**Comment by kesava-wow** [comment]
in light of the above, moving to: https://github.com/kesava-wow/kuinameplates2/issues/287
