### ISSUE TITLE
Targeted enemies' nameplates turn small

### ISSUE THREAD

**Issue by HeneDev** [kesava-wow/kuinameplates2#511]
With the newest update, when you click an enemy, their nameplates turn small.
![issue](https://user-images.githubusercontent.com/44865736/100053822-81bb3a80-2e29-11eb-826d-fe8f02b0a16b.PNG)

**Comment by timoff32** [comment]
This is due to a new option to change the target size.  Go into "Interface > Kui Nameplates Core > Frame Sizes > and Uncheck "Target Size" OR adjust it to how you want your selected targets frame to change.
