### ISSUE TITLE
Request: Option to display full name, even if length exceeds healthbar width

### ISSUE THREAD

**Issue by Araiia** [kesava-wow/kuinameplates2#512]
Issue: As of the latest addon version, unit names are truncated with ellipses if the name pixels is wider than the healthbar. 

Feedback: This really negatively impacts readability on targets with long names. 

Request: I don't see any obvious way to change this display behavior. Please consider making this optional? Thank you!

**Comment by kesava-wow** [comment]
Type this in chat: `/knp set name_constrain_offset -100`
