### ISSUE TITLE
Nameplate widget container overlapping with unitname

### ISSUE THREAD

**Issue by Jezzaw56** [kesava-wow/kuinameplates2#513]
Objects that have quest widgets attached to them overlap with the nameplate. By default blizzard nameplates don't nameplates don't attach a name to these objects. An example of this is the cauldron in maldraxxus. You can see with KUI enabled the unit name is behind and overlapping the widget. In the image with KUI disabled you can see this object should not have a unitname.

![with kui](https://user-images.githubusercontent.com/75017219/100213878-292f8e80-2f4a-11eb-827d-5ba2302a6514.jpg)
![without kui](https://user-images.githubusercontent.com/75017219/100213888-2b91e880-2f4a-11eb-8846-1065d8e78712.jpg)

**Comment by kesava-wow** [comment]
I don't know that the game gives us any distinction between widgets that want to hide the healthbar and the normal widgets.

I'm really not particularly bothered by it at the moment, but I might end up exploring it in the future anyway.
