### ISSUE TITLE
No shield icon for uninterruptable spells

### ISSUE THREAD

**Issue by BlueAbsinthe** [kesava-wow/kuinameplates2#516]
2.27.1 2.5
enUS ROGUE
{profile=default}
{auras_icon_normal_size=35,auras_show_purge=false,castbar_height=7,classpowers_size=14,global_scale=1.1}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, ClassPowers, CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, TankMode, Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target

Hey.

I only use realese versions of kui, and the last 2 versions (2.27 and 2.27.1) not working properly for me. The shield icon is missing at the cast bar, and just don't know which spell is interrupable. It's happening on my rogue. I had to change back the previous good version that is 2.26.3e, which is perfecly working.

**Comment by kesava-wow** [comment]
It's back in the latest beta (but it's disabled by default).
