### ISSUE TITLE
Friendly nameplates colour stops working partway through name

### ISSUE THREAD

**Issue by jf1x** [kesava-wow/kuinameplates2#519]
Not sure how to reproduce, but I'm getting this issue randomly. Doesn't affect all friendly nameplates, and even plates of the same NPC ID but a different instance colour different amounts of letters.

![image](https://user-images.githubusercontent.com/277449/100800794-fcceb300-341e-11eb-8bc1-cd0063b49acb.png)

**Comment by kesava-wow** [comment]
The colour fills to represent their health. There's an option in the name only page.
