### ISSUE TITLE
Auras: invalid SetFont call

### ISSUE THREAD

**Issue by BlueNightSky** [kesava-wow/kuinameplates2#52]
254x Kui_Nameplates\elements/auras.lua:265: Usage: <unnamed>:SetFont("font", fontHeight [, flags])
[C]: in function `SetFont'
Kui_Nameplates\elements/auras.lua:265: in function <Kui_Nameplates\elements/auras.lua:245>
Kui_Nameplates\elements/auras.lua:363: in function `GetButton'
Kui_Nameplates\elements/auras.lua:381: in function `DisplayButton'
Kui_Nameplates\elements/auras.lua:346: in function `GetAuras'
Kui_Nameplates\elements/auras.lua:309: in function `Update'
Kui_Nameplates\elements/auras.lua:622: in function `func'
Kui_Nameplates\messages.lua:75: in function <Kui_Nameplates\messages.lua:40>

Locals:

**Comment by kesava-wow** [comment]
Which version? Have you modified the code at all? Have you tried changing the font setting?

**Comment by BlueNightSky** [comment]
2-8-beta-2, I am zhTW client.
Have you tried changing the font setting? 
YES! change to TW default font, support from LibSharedMedia-3.0.

**Comment by BlueNightSky** [comment]
Now I know why, i use the old Plugin addons: KuiNameplates Elite , sorry!

**Comment by kesava-wow** [comment]
I can reproduce this on certain classes (warrior, for example). Which makes no sense to me off the top of my head, but oh well.

Thanks.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/34e162a017ee4908122ebd63072ebf1dc3199f27
