### ISSUE TITLE
Bars beneath friendly players

### ISSUE THREAD

**Issue by ipotuz** [kesava-wow/kuinameplates2#526]
Hey,

Thanks for the great work. For some reason I have a bar displayed beneath the friendly players, I don't get what this bar is exactly as it seems to be health or mana according to the class.
Did anyone get to solve that problem?
I play classic on a PC, this bar does not show on the pets. Only on players, I asked to see the guild name but I have the bar instead.

![WoWScrnShot_121520_225358](https://user-images.githubusercontent.com/62054630/102278717-92436a00-3f2a-11eb-8c17-256ef60d1a15.jpg)

**Comment by kesava-wow** [comment]
That's the healthbar. You've unchecked the option "friendly players" under /knp > name-only (if checking that option doesn't fix it, post the output of `/knp dump`).Nameplates typically show a healthbar. KNP's default settings hide the bar and show only the name of friendly targets.
