### ISSUE TITLE
enhancement,  Debuffs (Auras) on the right side of the nameplate and totem icons

### ISSUE THREAD

**Issue by Galvanitsch** [kesava-wow/kuinameplates2#54]
Great addon!
Hey man, your nameplates addon is almost as good as docs nameplates / sqwnameplates (but they will not be updated for legion #sad) 
To be as good, i would love to have the debuff (aura) icons on the right side of the nameplate, (not on topleft/ topmiddl/topright, i mean really on the right side) because many pvp players use nameplate cooldowns and its getting messed up on top of the nameplates. 
One unique and awesome feature of those nameplate addons were the icons instead of the totem healthbars. For pvp players it is better to see the symbol of the enemys totem. 
Great Job so far !

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplatesextras/issues/11
https://github.com/kesava-wow/kuinameplates2/issues/58
