### ISSUE TITLE
Health bars are not displayed

### ISSUE THREAD

**Issue by FabGitdaZog** [kesava-wow/kuinameplates2#540]
The health bars are not showing up, despite seemingly all needed settings to be turned on.
I have attached the screenshots of settings and a how currently everything looks for me in game

![WoWScrnShot_013021_141110](https://user-images.githubusercontent.com/45933165/106356036-15672680-6305-11eb-9190-1b17348df44f.jpg)
![WoWScrnShot_013021_141121](https://user-images.githubusercontent.com/45933165/106356037-19934400-6305-11eb-871a-05b54c417cb0.jpg)

**Comment by kesava-wow** [comment]
That's knp's name-only mode. See /knp > name-only.
