### ISSUE TITLE
TBC  Compatability

### ISSUE THREAD

**Issue by projectmercy-0101** [kesava-wow/kuinameplates2#556]
Blizzard added a new WOW_PROJECT_ID  for TBC ( WOW_PROJECT_BURNING_CRUSADE_CLASSIC ) so neither the current classic or the retail version function. I was able to expand the kui.CLASSIC init statement to check for both and addon seemed to function as I expected. I know you don't merge PRs, but I just changed kui.lua 

`
--luacheck:globals WOW_PROJECT_ID WOW_PROJECT_CLASSIC WOW_PROJECT_BURNING_CRUSADE_CLASSIC
local CLASSIC = WOW_PROJECT_ID == WOW_PROJECT_CLASSIC or WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC
kui.CLASSIC = CLASSIC
`

**Comment by kesava-wow** [comment]
Thanks!
