### ISSUE TITLE
How do I change the brightness and opacity of the personal nameplate?

### ISSUE THREAD

**Issue by bunster** [kesava-wow/kuinameplates2#557]
It being too dim for me is really the main thing keeping me from using this addon.

**Comment by kesava-wow** [comment]
It's opacity is controlled by a cvar, /knp > cvars > self alpha. Brightness depends on your setup. If you have it class coloured, then, well, it's class coloured, but you might prefer the "bright" variant of the status bar texture. If you don't have it class coloured, the colour option is at the bottom of /knp > health bars > self.
