### ISSUE TITLE
Errors with new target and enemy nameonly

### ISSUE THREAD

**Issue by adrloza** [kesava-wow/kuinameplates2#57]
The new beta features are giving me a bunch of errors (on my warrior). With nameonly mode on target activated and targeting something, I get this error. Then it seems like the feature isn't working.

Message: ...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:277: attempt to index upvalue 'cpf' (a nil value)
Time: 08/04/16 09:53:13
Count: 7
Stack: ...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:277: in function <...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:258>
...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:361: in function `TargetUpdate'
Interface\AddOns\Kui_Nameplates_Core\create.lua:1280: in function `NameOnlyUpdateFunctions'
Interface\AddOns\Kui_Nameplates_Core\hook.lua:130: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:33: in function `DispatchMessage'
Interface\AddOns\Kui_Nameplates\elements/target.lua:9: in function <Interface\AddOns\Kui_Nameplates\elements/target.lua:7>
Interface\AddOns\Kui_Nameplates\elements/target.lua:32: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:81: in function <Interface\AddOns\Kui_Nameplates\messages.lua:44>
[C]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals: frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'cpf' (a nil value)"
on_target = nil
cpf = nil
FRAME_POINT = nil
ele = <table> {
 Enable = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:329
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:364
 Initialise = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:483
 Initialised = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:459
 PowerEvent = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:431
 priority = 0
 OnDisable = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:454
 __CALLBACKS = <table> {
 }
 callbacks = <table> {
 }
 element = true
 RuneUpdate = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:414
 OnEnable = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:443
 PowerInit = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:368
 TargetUpdate = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:360
 name = "ClassPowers"
 UpdateConfig = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:302
 Disable = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:338
}

When I targeting something else, or stop targeting anything, I get this error.

`Message: ...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:277: attempt to index upvalue 'cpf' (a nil value)
Time: 08/04/16 09:53:13
Count: 7
Stack: ...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:277: in function <...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:258>
...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:361: in function `TargetUpdate'
Interface\AddOns\Kui_Nameplates_Core\create.lua:1280: in function `NameOnlyUpdateFunctions'
Interface\AddOns\Kui_Nameplates_Core\hook.lua:142: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:33: in function `DispatchMessage'
Interface\AddOns\Kui_Nameplates\elements/target.lua:13: in function <Interface\AddOns\Kui_Nameplates\elements/target.lua:11>
Interface\AddOns\Kui_Nameplates\elements/target.lua:17: in function <Interface\AddOns\Kui_Nameplates\elements/target.lua:15>
Interface\AddOns\Kui_Nameplates\elements/target.lua:25: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:81: in function <Interface\AddOns\Kui_Nameplates\messages.lua:44>
[C]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals: frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'cpf' (a nil value)"
on_target = nil
cpf = nil
FRAME_POINT = nil
ele = <table> {
 Enable = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:329
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:364
 Initialise = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:483
 Initialised = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:459
 PowerEvent = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:431
 priority = 0
 OnDisable = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:454
 __CALLBACKS = <table> {
 }
 callbacks = <table> {
 }
 element = true
 RuneUpdate = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:414
 OnEnable = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:443
 PowerInit = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:368
 TargetUpdate = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:360
 name = "ClassPowers"
 UpdateConfig = <function> defined @Interface\AddOns\Kui_Nameplates\elements/classpowers.lua:302
 Disable = <function> defined @Interface\AddOns\Kui_Nameplates\messages.lua:338
}
`

In addition, another error I get is when I have the nameonly selected for enemies, but not for target. I get a health bar every other time I target an enemy. So I get one for the first time I target something, switching targets gives me no healthbar, and switching targets to a 3rd target gives me the health bar again.

`Message: ...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:281: attempt to index upvalue 'FRAME_POINT' (a nil value)
Time: 08/04/16 10:01:20
Count: 16
Stack: ...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:281: in function <...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:258>
...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:361: in function `TargetUpdate'
Interface\AddOns\Kui_Nameplates_Core\create.lua:1280: in function `NameOnlyUpdateFunctions'
Interface\AddOns\Kui_Nameplates_Core\hook.lua:105: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:33: in function `DispatchMessage'
...terface\AddOns\Kui_Nameplates\elements/healthbar.lua:66: in function `UpdateHealthColour'
...terface\AddOns\Kui_Nameplates\elements/healthbar.lua:96: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:79: in function <Interface\AddOns\Kui_Nameplates\messages.lua:44>

Locals: frame = KuiNamePlate1 {
 LevelText = <unnamed> {
 }
 Highlight = <unnamed> {
 }
 UpdateMainBars = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:333
 parent = NamePlate1 {
 }
 UpdateTargetArrows = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:680
 UpdateRaidIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:934
 UpdateFrameGlow = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:583
 bg = <unnamed> {
 }
 TargetGlow = <unnamed> {
 }
 NameText = <unnamed> {
 }
 state = <table> {
 }
 x = 4
 y = 13
 unit = "nameplate1"
 ShowCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:743
 NameOnlyGlow = <unnamed> {
 }
 RaidIcon = <unnamed> {
 }
 UpdateStateIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:901
 UpdateAuras = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1009
 UpdateFrameSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:290
 animated_bars = <table> {
 }
 SpellIcon = <unnamed> {
 }
 ThreatBrackets = <table> {
 }
 HealthText = <unnamed> {
 }
 StateIcon = <unnamed> {
 }
 handler = <table> {
 }
 CastBar = <unnamed> {
 }
 Auras = <table> {
 }
 UpdateCastbarSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:817
 0 = <userdata>
 SpellIconSetWidth = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:737
 UpdateCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:777
 PowerBar = <unnamed> {
 }
 SpellName = <unnamed> {
 }
 HideCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:769
 UpdateSpellNamePosition = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:814
 UpdatePowerBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:365
 SpellShield = <unnamed> {
 }
 UpdateNameTextPosition = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:436
 TargetArrows = <table> {
 }
 elements = <table> {
 }
 UpdateThreatBrackets = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1174
 UpdateLevelText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:451
 GuildText = <unnamed> {
 }
 CastBarUpdateFrame = <unnamed> {
 }
 UpdateHealthText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:496
 HealthBar = <unnamed> {
 }
 UpdateNameText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:393
 ThreatGlow = <table> {
 }
 cast_state = <table> {
 }
}
(*temporary) = nil
(*temporary) = "player"
(*temporary) = NamePlate1 {
 namePlateUnitToken = "nameplate1"
 driverFrame = NamePlateDriverFrame {
 }
 UnitFrame = NamePlate1UnitFrame {
 }
 ApplyOffsets = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:288
 OnRemoved = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:275
 kui = KuiNamePlate1 {
 }
 0 = <userdata>
 OnAdded = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:`

Another error I got was this one, although I have no idea how this happened or what its related to. 
`Message: ...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:281: attempt to index upvalue 'FRAME_POINT' (a nil value)
Time: 08/04/16 10:04:20
Count: 62
Stack: ...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:281: in function <...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:258>
...rface\AddOns\Kui_Nameplates\elements/classpowers.lua:361: in function `TargetUpdate'
Interface\AddOns\Kui_Nameplates_Core\create.lua:1280: in function `NameOnlyUpdateFunctions'
Interface\AddOns\Kui_Nameplates_Core\hook.lua:105: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:33: in function `DispatchMessage'
Interface\AddOns\Kui_Nameplates\plugins/execute.lua:83: in function `HealthColourChange'
Interface\AddOns\Kui_Nameplates\plugins/execute.lua:89: in function `func'
Interface\AddOns\Kui_Nameplates\messages.lua:79: in function <Interface\AddOns\Kui_Nameplates\messages.lua:44>

Locals: frame = KuiNamePlate1 {
 LevelText = <unnamed> {
 }
 Highlight = <unnamed> {
 }
 UpdateMainBars = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:333
 parent = NamePlate1 {
 }
 UpdateTargetArrows = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:680
 UpdateRaidIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:934
 UpdateFrameGlow = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:583
 bg = <unnamed> {
 }
 TargetGlow = <unnamed> {
 }
 NameText = <unnamed> {
 }
 UpdateHealthText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:496
 ThreatGlow = <table> {
 }
 isChatBubble = false
 state = <table> {
 }
 x = 4
 y = 13
 unit = "nameplate1"
 ShowCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:743
 NameOnlyGlow = <unnamed> {
 }
 RaidIcon = <unnamed> {
 }
 UpdateStateIcon = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:901
 UpdateAuras = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1009
 UpdateFrameSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:290
 animated_bars = <table> {
 }
 SpellIcon = <unnamed> {
 }
 ThreatBrackets = <table> {
 }
 HealthText = <unnamed> {
 }
 StateIcon = <unnamed> {
 }
 handler = <table> {
 }
 CastBar = <unnamed> {
 }
 Auras = <table> {
 }
 UpdateCastbarSize = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:817
 0 = <userdata>
 SpellIconSetWidth = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:737
 UpdateCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:777
 PowerBar = <unnamed> {
 }
 SpellName = <unnamed> {
 }
 HideCastBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:769
 UpdateSpellNamePosition = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:814
 UpdatePowerBar = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:365
 SpellShield = <unnamed> {
 }
 UpdateNameTextPosition = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:436
 TargetArrows = <table> {
 }
 elements = <table> {
 }
 UpdateThreatBrackets = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:1174
 UpdateLevelText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:451
 GuildText = <unnamed> {
 }
 CastBarUpdateFrame = <unnamed> {
 }
 fadeInfo = <table> {
 }
 HealthBar = <unnamed> {
 }
 UpdateNameText = <function> defined @Interface\AddOns\Kui_Nameplates_Core\create.lua:393
 cast_state = <table> {
 }
}
(*temporary) = nil
(*temporary) = "player"
(*temporary) = NamePlate1 {
 namePlateUnitToken = "nameplate1"
 driverFrame = NamePlateDriverFrame {
 }
 UnitFrame = NamePlate1UnitFrame {
 }
 ApplyOffsets = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:288
 OnRemoved = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:275
 kui = KuiNamePlate1 {
 }
 isChatBubble = false
 0 = <userdata>
 OnAdded = <function> defined @`

**Comment by kesava-wow** [comment]
Oh, thanks, forgot to try on a character with no class powers. Whoops.

**Comment by adrloza** [comment]
Sorry for the ugly formatting lol, and thanks for the help

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/0add21859340faa4f880c3b625e7c91b6f899057
