### ISSUE TITLE
Offtank threat color not working

### ISSUE THREAD

**Issue by randomite1** [kesava-wow/kuinameplates2#570]
I play as Feral spec, marked as main tank. The other tanks market as main tank aswell, but the color of their aggroed mobs does not change, still showing red for me.

**Comment by Ganbin** [comment]
Hi,

I have the exact same issue, in TBC, I don't know how to fix it.

**Comment by Stefen74** [comment]
... cool, I'm kinda glad that it's not just me having this issue, I thought I was missing something obvious. Mine is also being a druid tank, which seems to be a re-occurring pattern here?

**Comment by Luc0002** [comment]
I've done a lot of testing in game on this - doesn't work but plater/threatplates etc will work.
