### ISSUE TITLE
[Tank Threat] Health Bar color on enemies changes to white when DK applies Blood Plague

### ISSUE THREAD

**Issue by Michorov** [kesava-wow/kuinameplates2#595]
I have tank threat set to green color by default while tanking the mob.
As soon as I apply Blood Plague with Blood Boil the monster bar turns to white and I cannot see if I am tanking or not.
It causes a lot of problems with Death Knights easily losing threat.

I tried to black list Blood Plague and all threat colors works perfectly after that but I would like to track the plague timer.
Thanks

**Comment by Zynnlol454** [comment]
I agreed, we should have some option to disable the White color when Blood Plague is on the target

**Comment by Michorov** [comment]
After I played a bit with the settings I found out that the issue is related to https://www.curseforge.com/wow/addons/kuinameplates-target-helper within the Class Auras tab and can be disabled.

I am not sure if it was fixed after I created this ticket or it was there from the beginning but the issue is no longer occurring.

Closing this ticket as it's not related to the core addon.
