### ISSUE TITLE
The version doesn't work anymore.

### ISSUE THREAD

**Issue by Interfector-Da** [kesava-wow/kuinameplates2#596]
Hello.

Since the update of world of warcraft 9.2.5, Kui nameplates doesn't work et we have to desactivate it. Even if we activate it, it doesn't work, we go back to the classique nameplates of wow; because, at the connexion on the character list, it says that we have to desactivate it.

**Comment by Xylotox** [comment]
> 

"x:\World of Warcraft\_classic_\Interface\AddOns\Kui_Nameplates\lib\Kui\Kui.lua"

===>"local BURNING_CRUSADE = WOW_PROJECT_ID == **WOW_PROJECT_WRATH_CLASSIC**"

OK!

**Comment by kaminador** [comment]
Hi! I'm new to this, what am I supposed to do to make it run on Wrath Classic? I just add "local BURNING_CRUSADE = WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC" to the file? Thanks very much!

**Comment by Macumbatbc** [comment]
It seems to be updated on github
https://github.com/kesava-wow/kuinameplates2
