### ISSUE TITLE
Kui Nameplates and Kui Mount are not working 

### ISSUE THREAD

**Issue by Creepshow1168** [kesava-wow/kuinameplates2#611]
Not working at all with the new release .. Please fix we love your addon

**Comment by vaisest** [comment]
In the meantime for anyone testing the pre-patch, @rljohn's [fork seems to work fine](https://github.com/rljohn/kuinameplates2).

**Comment by Debugga-nb** [comment]
To our other issue submitters: dont forget to grab bugstack and buggrabber; so you can provide meaningful feedback to developers.


3x ...ddOns/totalRP3/Modules/NamePlates/NamePlates_Kui.lua:96: hooksecurefunc(): UpdateNameText is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/totalRP3/Modules/NamePlates/NamePlates_Kui.lua"]:96: in function <...ddOns/totalRP3/Modules/NamePlates/NamePlates_Kui.lua:85>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Kui_Nameplates/messages.lua"]:128: in function `DispatchMessage'
[string "@Interface/AddOns/Kui_Nameplates/nameplate.lua"]:90: in function `Create'
[string "@Interface/AddOns/Kui_Nameplates/hook.lua"]:64: in function `HookNameplate'
[string "@Interface/AddOns/Kui_Nameplates/addon.lua"]:87: in function `?'
[string "@Interface/AddOns/Kui_Nameplates/addon.lua"]:157: in function <Interface/AddOns/Kui_Nameplates/addon.lua:154>

**Comment by Sabawar** [comment]
> In the meantime for anyone testing the pre-patch, @rljohn's [fork seems to work fine](https://github.com/rljohn/kuinameplates2).



in this version everything works except dropdown menu
does anyone know how to fix it or how to contact @[rljohn](https://github.com/rljohn)


```
23x ...meplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua:119: Usage: self:SetWordWrap(wrap)
[string "=[C]"]: in function `SetWordWrap'
[string "@Interface/AddOns/Kui_Nameplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua"]:119: in function <...meplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua:109>
[string "@Interface/AddOns/Kui_Nameplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua"]:257: in function <...meplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua:256>
[string "@Interface/AddOns/Kui_Nameplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua"]:182: in function <...meplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua:152>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Kui_Nameplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua"]:40: in function <...meplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua:29>
[string "@Interface/AddOns/Kui_Nameplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua"]:295: in function <...meplates_Core_Config/lib/KuiDropdown/KuiDropdown.lua:291>

Locals:
(*temporary) = FontString {
 0 = <userdata>
}

```

**Comment by rljohn** [comment]
Thanks, I'll get that sorted tonight and open up a new pull request into the main addon. The function is just SetWordWrap(true) now instead of SetWordWrap (or vice-versa)

**Comment by Sunnyqt242** [comment]
@rljohn can you pls tell me how i get the addon work again? i replaced your lua in kui_nameplates addon.lua and kui_nameplates_core_config kuidropdown but its still not working :(

**Comment by Sabawar** [comment]
> Thanks, I'll get that sorted tonight and open up a new pull request into the main branch. Hopefully Kesava will get a chance to update soon. The function is just SetWordWrap(true) now instead of SetWordWrap (or vice-versa).
> 
> Edit: Resolved, pull request updated.

thx fot update

**Comment by Allakatter2** [comment]
> In the meantime for anyone testing the pre-patch, @rljohn's [fork seems to work fine](https://github.com/rljohn/kuinameplates2).
Yo, im pretty new to Github, how would I go about actually downloading this new fix? I can only see a bunch of new code but no download button.

**Comment by Debugga-nb** [comment]
@Allakatter2 I had to look it up cus i forgot about "zipball"; if you use the link below, it'll spit out a zip of @rljohn 's master branch.

https://github.com/rljohn/kuinameplates2/zipball/master

**Comment by Allakatter2** [comment]
> @Allakatter2 I had to look it up cus i forgot about "zipball"; if you use the link below, it'll spit out a zip of @rljohn 's master branch.
> 
> https://github.com/rljohn/kuinameplates2/zipball/master

That worked wonders! Thanks a lot!

**Comment by Allakatter2** [comment]
> In the meantime for anyone testing the pre-patch, @rljohn's [fork seems to work fine](https://github.com/rljohn/kuinameplates2).

It seems like Auras is currently not working on the target nameplate. I have Auras Enabled, but they are not showing.
Image on settings and a mob with a debuff for reference > https://imgur.com/a/9ygLbVJ

**Comment by al36awe** [comment]
thanks so much 

works

**Comment by Nevcairiel** [comment]
This was fixed in the latest alpha.
