### ISSUE TITLE
Problem with new 10.0 UI changes

### ISSUE THREAD

**Issue by phoenix7700** [kesava-wow/kuinameplates2#612]
Wasn't able to do /knp dump but Here's the BugSack Lua Error hope it helps.

2x Interface/AddOns/Kui_Nameplates_Core/config.lua:1035: attempt to index global 'InterfaceOptionsFrame' (a nil value)
[string "@Interface/AddOns/Kui_Nameplates_Core/config.lua"]:1035: in function `InitialiseConfig'
[string "@Interface/AddOns/Kui_Nameplates_Core/hook.lua"]:346: in function `Initialise'
[string "@Interface/AddOns/Kui_Nameplates/addon.lua"]:190: in function <Interface/AddOns/Kui_Nameplates/addon.lua:154>

Locals:
self = <table> {
 BAR_TEXTURE = "Kui_Media\t\bar"
 OnEnter = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:144
 Scale = <function> defined @Interface/AddOns/Kui_Nameplates_Core/config.lua:306
 CreateNameOnlyGlow = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2104
 AurasButton_SetFont = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1750
 LSMMediaRegistered = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:280
 NameOnlyUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2313
 CreateAuras = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1608
 LostTarget = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:129
 layout = true
 Create = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:22
 GainedTarget = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:125
 CreateHighlight = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:441
 QuestUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:154
 ShowNameUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2045
 InitialiseElements = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2322
 JUSTIFY_ASSOC = <table> {
 }
 HealthColourChange = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:92
 CreateThreatBrackets = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1975
 configChangedStateIcons = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1411
 CreateGuildText = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:829
 PowerTypeUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:97
 CreateQuestIcon = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2018
 InitialiseFadeRules = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:301
 SetAurasConfig = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1759
 SetLocals = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:273
 POINT_ASSOC = <table> {
 }
 configChangedTextOffset = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:308
 configChangedFontOption = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:322
 CreateAbsorbBar = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:552
 ExecuteUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:140
 CreateHealthBar = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:475
 HealthUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:87
 RaidIconUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:136
 CastBarHide = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:115
 ClassificationChanged = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:133
 configChangedTargetArrows = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:289
 Hide = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:83
 CreateFrameGlow = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:907
 CreateLevelText = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:740
 __MESSAGES = <table> {
 }
 CreateNameText = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:712
 FONT = "ShadowedUnitFrames\media\fonts\Myriad Condensed Web.ttf"
 profile = <table> {
 }
 configChangedAbsorb = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:519
 GlowColourChange = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:100
 config = <table> {
 }
 InitialiseConfig = <function> defined @Interface/AddOns/Kui_Nameplates_Core/config.lua:960
 Auras_PostDisplayAuraButton = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1681
 ConfigChanged = <function> defined @Interface/AddOns/Kui_Nameplates_Core/config.l

**Comment by Gurke258** [comment]
please update it :)

**Comment by richyvee** [comment]
I got the same thing i thiiink 

2x Interface/AddOns/Kui_Nameplates_Core/config.lua:1035: attempt to index global 'InterfaceOptionsFrame' (a nil value)
[string "@Interface/AddOns/Kui_Nameplates_Core/config.lua"]:1035: in function `InitialiseConfig'
[string "@Interface/AddOns/Kui_Nameplates_Core/hook.lua"]:346: in function `Initialise'
[string "@Interface/AddOns/Kui_Nameplates/addon.lua"]:190: in function <Interface/AddOns/Kui_Nameplates/addon.lua:154>

Locals:
self = <table> {
 BAR_TEXTURE = "Kui_Media\t\bar"
 OnEnter = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:144
 Scale = <function> defined @Interface/AddOns/Kui_Nameplates_Core/config.lua:306
 CreateNameOnlyGlow = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2104
 AurasButton_SetFont = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1750
 LSMMediaRegistered = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:280
 NameOnlyUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2313
 CreateAuras = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1608
 LostTarget = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:129
 layout = true
 Create = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:22
 GainedTarget = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:125
 CreateHighlight = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:441
 QuestUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:154
 ShowNameUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2045
 InitialiseElements = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2322
 JUSTIFY_ASSOC = <table> {
 }
 HealthColourChange = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:92
 CreateThreatBrackets = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1975
 configChangedStateIcons = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1411
 CreateGuildText = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:829
 PowerTypeUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:97
 CreateQuestIcon = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:2018
 InitialiseFadeRules = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:301
 SetAurasConfig = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1759
 SetLocals = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:273
 POINT_ASSOC = <table> {
 }
 configChangedTextOffset = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:308
 configChangedFontOption = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:322
 CreateAbsorbBar = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:552
 ExecuteUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:140
 CreateHealthBar = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:475
 HealthUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:87
 RaidIconUpdate = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:136
 CastBarHide = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:115
 ClassificationChanged = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:133
 configChangedTargetArrows = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:289
 Hide = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:83
 CreateFrameGlow = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:907
 CreateLevelText = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:740
 __MESSAGES = <table> {
 }
 CreateNameText = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:712
 FONT = "Kui_Media\f\roboto.ttf"
 profile = <table> {
 }
 configChangedAbsorb = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:519
 GlowColourChange = <function> defined @Interface/AddOns/Kui_Nameplates_Core/hook.lua:100
 config = <table> {
 }
 InitialiseConfig = <function> defined @Interface/AddOns/Kui_Nameplates_Core/config.lua:960
 Auras_PostDisplayAuraButton = <function> defined @Interface/AddOns/Kui_Nameplates_Core/create.lua:1681
 ConfigChanged = <function> defined @Interface/AddOns/Kui_Nameplates_Core/config.lua:927
 NameOnlyCombatUpdate = <f

**Comment by Nevcairiel** [comment]
This was fixed in the latest alpha.
