### ISSUE TITLE
Nameplates stopped working all of a sudden

### ISSUE THREAD

**Issue by ypagola** [kesava-wow/kuinameplates2#621]
Recently installed the addon and was working perfectly, after logging back in on the same day, nameplates disappeared and could no longer find the addon under the interface addons tab, as if it werent installed, default nameplates are enabled and wont show either, have also reinstalled the addon to no results. 

is there a known solution to this issue? Thanks in advance!

![image](https://user-images.githubusercontent.com/117707401/200482002-5d70c313-accf-450a-b5c7-78f8561059de.png)

**Comment by kesava-wow** [comment]
Oh, I suppose I broke the alpha on classic. Install the [previous alpha](https://www.curseforge.com/wow/addons/kuinameplates/files/3981875).

**Comment by crazybrad619** [comment]
Will you fix the updated one from today or should I install the previous one instead? Also, what was the recent update anyways?

Thanks!

**Comment by kesava-wow** [comment]
It was to fix the retail version for the pre-patch. My setup automatically made a release for the classic versions too, but I hadn't actually tested it there. The alphas are likely to be broken sometimes.

It'll be fixed, but you should just install the previous working version for now (I've archived the broken versions, so if you're using a download manager it shouldn't try to update to them again).

**Comment by Nevcairiel** [comment]
Classic should be fixed in the latest alpha

**Comment by crazybrad619** [comment]
Is there a way to show purgable buffs at all time on clases that dont have it? it used to back in TBC i thought but, on my lock i can't see buffs unless i have my felhound out or play my shaman.
