### ISSUE TITLE
Just updated using curseforge and now the addon is not working (WoW Classic WOTLK)

### ISSUE THREAD

**Issue by zeritox07** [kesava-wow/kuinameplates2#623]
Then tried running the addon alone and is not working either. Any way to fix it?
Oh and I also tried using the version from the website but seems its the same one.

**Comment by Stanzilla** [comment]
Which version exactly did you install?

**Comment by AgathiaKimiya** [comment]
Same thing here. The websites says it has been updated a few hours ago, but the only downloadable version is from 2021 for 9.0.5. I can see the files have been updated on git as well, but it seems like whatever Curse delivers is not up to date at all.

**Comment by zeritox07** [comment]
Seems i was using the latest alpha version, tried dowloading a previous version and now it's working fine for me.
