### ISSUE TITLE
Is this because of kui?

### ISSUE THREAD

**Issue by Zasz333** [kesava-wow/kuinameplates2#625]
For about two days now Ive been getting strange errors pointing at the default blizzard folders in the interface folder. I got those errors almost at random, cant find a pattern yet. Earlier I updated kui from here. Now Im getting this on login. Is this because of kui?

.e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:269: Usage: GetRaidTargetIndex(unit)
[string "=[C]"]: in function `GetRaidTargetIndex'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:269: in function `OnRaidTargetUpdate'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:146: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:136>
[string "=[C]"]: in function `OnNamePlateAdded'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:78: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:69>

Locals:
(*temporary) = nil

And this at the same time too:

StatusBar:GetLeft(): Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: StatusBar:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:572: in function `GetPreferredInsets'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:191: in function `UpdateInsetsForType'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:175: in function `ApplyFrameOptions'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:140: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:136>
[string "=[C]"]: in function `OnNamePlateAdded'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:78: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:69>

Locals:
(*temporary) = StatusBar {
 otherHealPrediction = Texture {
 }
 b = 0.447059
 myHealAbsorbLeftShadow = Texture {
 }
 border = Frame {
 }
 background = Texture {
 }
 overAbsorbGlow = Texture {
 }
 barTexture = Texture {
 }
 0 = <userdata>
 r = 0.666667
 totalAbsorb = Texture {
 }
 myHealPrediction = Texture {
 }
 g = 0.827451
 totalAbsorbOverlay = Texture {
 }
 myHealAbsorbRightShadow = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 myHealAbsorb = Texture {
 }
}

**Comment by Stanzilla** [comment]
Nope
