### ISSUE TITLE
DK runes don't show under the nameplates (WOTLK versions)

### ISSUE THREAD

**Issue by marcadrian-it** [kesava-wow/kuinameplates2#632]
Hey @kesava-wow 
On wotlk versions 2.28.0, 2.28.0-1, 2.28.0-2, 2.28.0-3 DK runes don't show at all. Other class power bars work just fine: on my rogue I see combo points correctly. Can you do something about it? I love the addon but hate that I can't play properly my DK :D Thanks

![WoWScrnShot_111922_222245](https://user-images.githubusercontent.com/22295674/202872126-5cd36969-d405-43d4-a35b-56d6a7842e03.jpg)

**Dump:**
`2.28.0-3-gcb6a0b0 2.5
enUS DEATHKNIGHT
{profile=default}
{}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, [ClassPowers], CastBar, Highlight, PowerBar, [AbsorbBar], Threat, Auras, Classification, Execute, TankMode, Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target`

**Comment by Drudchenko782** [comment]
Hi, I am having the same issue where DK runes don't show up on nameplate. Is there a version that works in WOTLK?
