### ISSUE TITLE
Personal Resource Display issue

### ISSUE THREAD

**Issue by beezy43** [kesava-wow/kuinameplates2#634]
i'm having issues with the personal resource display with my death knight runes, they are clipping into the healthbar/runic power when using the default class powers as shown here
![Screenshot (76)](https://user-images.githubusercontent.com/118648111/202885687-9cc021c8-14b5-4724-a744-8053868489dd.png)

and then if i try to ignore personal nameplate its causes the blizzard nameplate and the kui nameplate to both show
![Screenshot (78)](https://user-images.githubusercontent.com/118648111/202885803-523690c3-aa2b-46a6-842c-efde9a21f846.png)

any help appreciated thanks

**Comment by wowloverz** [comment]
![WoWScrnShot_110423_052508](https://github.com/kesava-wow/kuinameplates2/assets/149856578/2da1a433-8ade-481d-8018-54ab64adeb1f)

Hello, I have exactly the same problem. I'm starting again after 2 years and I see that not many people have the same problem, I don't understand why. But above all I haven't found any solution to the problem and it's horrible. I love KNM please need help
