### ISSUE TITLE
classpowers: brewmaster stagger

### ISSUE THREAD

**Issue by kesava-wow** [kesava-wow/kuinameplates2#64]

**Comment by kesava-wow** [comment]
The class powers module isn't really made with bars or multiple different powers in mind so... its a bit annoying.

**Comment by cothurn** [comment]
Is there a way to disable the kui class module and use the default one?

**Comment by kesava-wow** [comment]
No.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/b06a933f160667d3731c30ee20c45ef8ed84ddcc et al
