### ISSUE TITLE
Evoker empower casts not showing

### ISSUE THREAD

**Issue by mainlandsong** [kesava-wow/kuinameplates2#647]
I've been noticing in my arena games that Evoker empower casts (dream breath, spiritbloom) are not showing a cast bar under the nameplate.

**Comment by mainlandsong** [comment]
![image](https://user-images.githubusercontent.com/45954169/210602912-a1cf4b0b-b674-4176-a512-e9a95712b3d1.png)

**Comment by AbbasWadiwala** [comment]
Yeah I have noticed this as well.

**Comment by AbbasWadiwala** [comment]
I can see it in Quartz and in SArena, can't see it KNP

**Comment by ImLAKI** [comment]
Yeah, this one is really sad, should be fixed ASAP.

**Comment by crudos** [comment]
Bump, still an issue.

**Comment by VladPolovyi** [comment]
Still big issue for PVP

**Comment by Stanzilla** [comment]
Can you try the latest alpha?

**Comment by VladPolovyi** [comment]
I'll try tomorrow morning, thanks

**Comment by VladPolovyi** [comment]
Thanks, it works! Tested on personal bar and on duel
