### ISSUE TITLE
Plates disappearing when target is clicked!

### ISSUE THREAD

**Issue by Qpadder** [kesava-wow/kuinameplates2#65]
Plates are showing, but when I click the target they disappear.

**Comment by kesava-wow** [comment]
Do you have dynamiccam by any chance?

**Comment by Qpadder** [comment]
I do. I will try disabling it now :D

**Comment by kesava-wow** [comment]
I believe this is caused by a setting under one of the situations - probably npc interaction.

**Comment by Qpadder** [comment]
It seems to work a bit, but they still disappear.

**Comment by kesava-wow** [comment]
Well, i need more information then. What do you mean "disappear"? Do the default blizzard floating names appear? When you say click the target, does it also happen if you use tab targeting (not suggesting that as an alternative, just need to know more to narrow it down). Etc.

**Comment by Qpadder** [comment]
Blizzard floating names is not appearing.
I have three targets in front of me with plates showing, I target one and use a spell on him, the plates disappear. The same is with a killing blow. 
Sometimes if I use Blink when plates are showing, they disappear.
The same effect happens with tab targeting.

**Comment by kesava-wow** [comment]
OK, could you enable scripterrors (/console scriptErrors 1) for me and let me know if any pop up

**Comment by Qpadder** [comment]
/console scriptErrors 1 Does not seem to be doing anything. 
If I engage a target without the plates showing, they appear again.

**Comment by kesava-wow** [comment]
Okaaay, do you perchance have "combat action: hostile" set to "hide" in /knp > general?

**Comment by kesava-wow** [comment]
I'm not at home atm FYI so I'm just going through whatever I can.

**Comment by Qpadder** [comment]
Hostile is set to Show. I will try to make a video of the problem.

**Comment by Qpadder** [comment]
Hmmm, I put it to Do nothing and it's working fine now. :D
