### ISSUE TITLE
Names not showing up on classic after Ulduar patch.

### ISSUE THREAD

**Issue by Valkyriebound** [kesava-wow/kuinameplates2#651]
Hey, since the Ulduar patch, names don't show up and when clicking on players there's instead this white glow where the name would be.

![Untitled](https://user-images.githubusercontent.com/123032913/213315861-841a96c1-595d-4e75-b883-8cc986962ab5.jpg)

**Comment by Dinoburt** [comment]
Can confirm as well on this having same issue, health bars for me show up but no names.

**Comment by Stanzilla** [comment]
I cannot repro this atm, can you please post the output of /knp dump

**Comment by Dinoburt** [comment]
> 

2.27.3a 2.5
enUS PALADIN
{profile=default}
{frame_glow_threat=false,guild_text_players=true,tank_mode=false}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, [ClassPowers], CastBar, Highlight, PowerBar, [AbsorbBar], Threat, Auras, Classification, Execute, [TankMode], Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target

**Comment by Stanzilla** [comment]
> > 
> 
> 2.27.3a 2.5 enUS PALADIN {profile=default} {frame_glow_threat=false,guild_text_players=true,tank_mode=false} HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, [ClassPowers], CastBar, Highlight, PowerBar, [AbsorbBar], Threat, Auras, Classification, Execute, [TankMode], Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target

Your version is from 2021, you need to update

**Comment by Dinoburt** [comment]
> 
Interesting it always said up-to-date so I just assumed it was, grabbed the latest from the repo and will give that a go tomorrow, thanks for noticing the version issue

**Comment by Valkyriebound** [comment]
Thanks Stanzilla, just downloading the latest version fixed it to me. I really thought I already had, sorry for being dumb.
