### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KOOOOrda12** [kesava-wow/kuinameplates2#652]
![123](https://user-images.githubusercontent.com/123130325/213589292-37bd7fd3-70d9-4551-91dc-f0bfa2b94fc3.png)

**Comment by illutian** [comment]
Also getting this. 

17306x Kui_Nameplates/plugins/tankmode.lua:124: Usage: GetRaidRosterInfo(index)
[string "=[C]"]: in function `GetRaidRosterInfo'
[string "@Kui_Nameplates/plugins/tankmode.lua"]:124: in function `func'
[string "@Kui_Nameplates/messages.lua"]:163: in function <Kui_Nameplates/messages.lua:145>
[string "@Kui_Nameplates/messages.lua"]:208: in function <Kui_Nameplates/messages.lua:185>

Locals:


This was while in Heroic+ CoS and watching the NPCs kill the zombies and fleeing townsfolk as the group formed up.
