### ISSUE TITLE
Shaman's kick ID is incorrect. (kinda solved)

### ISSUE THREAD

**Issue by Judop3** [kesava-wow/kuinameplates2#653]
I was having problems displaying the shield icon and correct color on the castbar when I had the kick on cooldown. Messing arround a bit I discovered that the problem was on the kick ID, been 57994 the correct one.

Just look for GetSpellCooldown inside the create.lua file, and remplace the ID.

![2023-01-20 09_37_14-create lua — D__World of Warcraft__retail__Interface_AddOns_Kui_Nameplates_Core ](https://user-images.githubusercontent.com/85102937/213652051-933a7df5-7a71-46b5-887d-15f9ca4de86a.png)

**Comment by Stanzilla** [comment]
> I was having problems displaying the shield icon and correct color on the castbar when I had the kick on cooldown. Messing arround a bit I discovered that the problem was on the kick ID, been 57994 the correct one.
> 
> Just look for GetSpellCooldown inside the create.lua file, and remplace the ID.
> 
> ![2023-01-20 09_37_14-create lua — D__World of Warcraft__retail__Interface_AddOns_Kui_Nameplates_Core ](https://user-images.githubusercontent.com/85102937/213652051-933a7df5-7a71-46b5-887d-15f9ca4de86a.png)

not sure which version of the code you are looking at but that is not the current one
