### ISSUE TITLE
GetRaidRosterInfo error

### ISSUE THREAD

**Issue by Xevilmf** [kesava-wow/kuinameplates2#659]
Message: Interface/AddOns/Kui_Nameplates/plugins/tankmode.lua:124: Usage: GetRaidRosterInfo(index)
Time: Mon Apr 10 20:00:34 2023
Count: 6
Stack: Interface/AddOns/Kui_Nameplates/plugins/tankmode.lua:124: Usage: GetRaidRosterInfo(index)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetRaidRosterInfo'
[string "@Interface/AddOns/Kui_Nameplates/plugins/tankmode.lua"]:124: in function `func'
[string "@Interface/AddOns/Kui_Nameplates/messages.lua"]:163: in function <Interface/AddOns/Kui_Nameplates/messages.lua:145>
[string "@Interface/AddOns/Kui_Nameplates/messages.lua"]:208: in function <Interface/AddOns/Kui_Nameplates/messages.lua:185>

Moved from server A to B and this was an issue. I can turn off the force tankmode but love the threatmeter thing with it.

**Comment by Stanzilla** [comment]
Looks like you are using an outdated version
