### ISSUE TITLE
Essence power tracking missing

### ISSUE THREAD

**Issue by zeenk** [kesava-wow/kuinameplates2#664]
Tried to fix it myself by adding these lines and seem to work so far from my limited testing, maybe needs something more but works so far without any errors.

Kui_Nameplates\elements\classpowers.lua
Line 90: EVOKER     = { .4, 1, 7 },
Line 830: EVOKER     = Enum.PowerType.Essence,
Line 839: [Enum.PowerType.Essence]    = 'ESSENCE',
![2023-04-24_05-05-50](https://user-images.githubusercontent.com/68170439/233891402-b609dad8-465a-426d-aca2-6740946f185b.png)
![2023-04-24_05-06-12](https://user-images.githubusercontent.com/68170439/233891406-7e5b589e-1f08-4ea7-b555-eefc3b3e1a39.png)

**Comment by Stanzilla** [comment]
Thanks, added to the alpha

**Comment by zeenk** [comment]
👍 you can change the color if you want to, I tried to change it abit but still looks pretty similar to monks chi power but people maybe don't care about that :P

**Comment by Stanzilla** [comment]
> 👍 you can change the color if you want to, I tried to change it abit but still looks pretty similar to monks chi power but people maybe don't care about that :P

Yeah I just left it at that, seemed fine to me :D

**Comment by zeenk** [comment]
Oki ^^
