### ISSUE TITLE
Error in WOTLK

### ISSUE THREAD

**Issue by Xanpop** [kesava-wow/kuinameplates2#666]
This is on a Druid. Error occurs whenever I approach enemies. Also noticed that the targeted mob no longer stands out from mobs around it. Not sure how better to describe the issue or what other info would help. (Edited to add these details)

3x ...rfaceKui_Nameplates/elements/classpowers.lua:332: attempt to get length of field 'icons' (a nil value)
[string "@Kui_Nameplates/elements/classpowers.lua"]:332: in function <...rfaceKui_Nameplates/elements/classpowers.lua:316>
[string "@Kui_Nameplates/elements/classpowers.lua"]:534: in function `func'
[string "@Kui_Nameplates/messages.lua"]:128: in function `DispatchMessage'
[string "@Kui_Nameplates/elements/target.lua"]:9: in function <Kui_Nameplates/elements/target.lua:7>
[string "@Kui_Nameplates/elements/target.lua"]:37: in function `func'
[string "@Kui_Nameplates/messages.lua"]:128: in function `DispatchMessage'
[string "@Kui_Nameplates/nameplate.lua"]:75: in function `OnShow'
[string "@Kui_Nameplates/nameplate.lua"]:68: in function `OnUnitAdded'
[string "@Kui_Nameplates/addon.lua"]:115: in function `?'
[string "@Kui_Nameplates/addon.lua"]:157: in function <Kui_Nameplates/addon.lua:154>

Locals:
cur = 19026
(*temporary) = nil
(*temporary) = "player"
(*temporary) = nil
(*temporary) = true
(*temporary) = 19026
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of field 'icons' (a nil value)"
kui = <table> {
 table_to_string = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:73
 DebugPopup = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:525
 SHADOWLANDS = false
 Pluralise = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:367
 UnitLevel = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:267
 print = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:189
 string_to_table = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:112
 m = <table> {
 }
 frameFadeRemoveFrame = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:598
 utf8sub = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:398
 WRATH = true
 SetTextureToClass = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:222
 num = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:337
 GetClassColour = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:199
 frameIsFading = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:591
 FrameLockMixin = <table> {
 }
 CreateFontString = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:305
 CreateEightSlice = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:751
 frameFade = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:614
 UNIT_HEALTH = "UNIT_HEALTH_FREQUENT"
 GetUnitColour = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:240
 FormatTime = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:351
 CLASSIC = true
 ModifyFontFlags = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:291
 UnitIsPet = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:237
 Brighten = <function> defined @Kui_Nameplates/lib/Kui/Kui.lua:378
}
power_type = nil
power_mod = nil
cpf = Frame {
 0 = <userdata>
}
ICON_SPRITE = "interface/addons/kui_nameplates_core/media/combopoint"
power_display_partial = nil
highlight_at = nil
class = "DRUID"
ele = <table> {
 Paladin_WatchFiresOfJustice = <function> defined @Kui_Nameplates/elements/classpowers.lua:708
 UNIT_ABSORB_AMOUNT_CHANGED = <function> defined @Kui_Nameplates/elements/classpowers.lua:729
 Enable = <function> defined @Kui_Nameplates/messages.lua:496
 PLAYER_ENTERING_WORLD = <function> defined @Kui_Nameplates/elements/classpowers.lua:538
 Initialise = <function> defined @Kui_Nameplates/elements/classpowers.lua:789
 Initialised = <function> defined @Kui_Nameplates/elements/classpowers.lua:760
 PowerEvent = <function> defined @Kui_Nameplates/elements/classpowers.lua:695
 StaggerUpdate = <function> defined @Kui_Nameplates/elements/classpowers.lua:671
 __MESSAGES = <table> {
 }
 priority = 0
 UNIT_AURA = <function> defined @Kui_Nameplates/elements/classpowers.lua:720
 UNIT_POWER_FREQUENT = <function> defined @Kui_Nameplates/elements/classpowers.lua:726
 OnDisable = <function> defined @Kui_Nameplates/elements/classpowers.lua:754
 callbacks = <table> {
 }
 UPDATE_SHAPESHIFT_FORM = <function> defined @Kui_Nameplates/elements/classpowers.lua:705
 __CALLBACKS = <table> {
 }
 enabled = true
 UNIT_MAXHEALTH = <function> defined @Kui_Nameplates/elements/classpowers.lua:732
 enable_on_load = true
 element = true
 RuneUpdate = <function> defined @Kui_Nameplates/elements/classpowers.lua:636
 OnEnable = <function> defined @Kui_Nameplates/elements/classpowers.lua:736
 name = "ClassPowers"
 UNIT_MAXPOWER = <function> defined @Interf

**Comment by Stanzilla** [comment]
Please post more info. Which class were you on for example?

**Comment by Xanpop** [comment]
No error on my mage or rogue so I guess it's druid specific. Thanks for your help, it is much appreciated.

**Comment by amethystau** [comment]
Can also confirm errors on druid right after logging in and reloading in Dalaran (doesn't matter which spec).

Message: ...rface/AddOns/Kui_Nameplates/elements/classpowers.lua:558: attempt to call global 'GetSpecialization' (a nil value)
Time: Tue Apr 25 12:40:38 2023
Count: 1
Stack: ...rface/AddOns/Kui_Nameplates/elements/classpowers.lua:558: attempt to call global 'GetSpecialization' (a nil value)
[string "@Interface/AddOns/Kui_Nameplates/addon.lua"]:197: in function <Interface/AddOns/Kui_Nameplates/addon.lua:154>

Locals: self = Frame {
 NAME_PLATE_UNIT_REMOVED = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:117
 ui_print = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:59
 Nameplate = <table> {
 }
 DispatchMessage = <function> defined @Interface/AddOns/Kui_Nameplates/messages.lua:108
 uiscale = 0.650000
 Frames = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:62
 USE_BLIZZARD_PERSONAL = false
 NewElement = <function> defined @Interface/AddOns/Kui_Nameplates/messages.lua:564
 USE_BLIZZARD_POWERS = false
 NewPlugin = <function> defined @Interface/AddOns/Kui_Nameplates/messages.lua:527
 IGNORE_UISCALE = false
 plugins = <table> {
 }
 GetPlugin = <function> defined @Interface/AddOns/Kui_Nameplates/messages.lua:557
 layout = <table> {
 }
 NAME_PLATE_UNIT_ADDED = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:93
 MINOR = 5
 GetActiveNameplateForUnit = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:71
 NamePlateDriverFrame_AcquireUnitFrame = <function> defined @Interface/AddOns/Kui_Nameplates/hook.lua:21
 ClassPowersFrame = Frame {
 }
 Layout = <function> defined @Interface/AddOns/Kui_Nameplates/messages.lua:571
 GetNameplateForGuid = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:77
 PrintTrace = <function> defined @Interface/AddOns/Kui_Nameplates/messages.lua:88
 0 = <userdata>
 UI_SCALE_CHANGED = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:135
 NAME_PLATE_CREATED = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:86
 MAJOR = 2
 PLAYER_LEAVING_WORLD = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:126
 print = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:55
 DEBUG_IGNORE = <table> {
 }
 HookNameplate = <function> defined @Interface/AddOns/Kui_Nameplates/hook.lua:27
 GetNameplateForUnit = <function> defined @Interface/AddOns/Kui_Nameplates/addon.lua:65
}
event = "PLAYER_LOGIN"
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
}
(for control) = 6
_ = 6
plugin = <table> {
 Paladin_WatchFiresOfJustice = <function> defined @Interface/AddOns/Kui_Nameplates/elements/classpowers.lua:708
 UNIT_ABSORB_AMOUNT_CHANGED = <function> defined @Interface/AddOns/Kui_Nameplates/elements/classpowers.lua:729
 Enable = <function> defined @Interface/AddOns/Kui_Nameplates/messages.lua:496
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/Kui_Nameplates/elements/classpowers.lua:538
 Initialise = <function> defined @Interface/AddOns/Kui_Nameplates/elements/classpowers.lua:789
 Initialised = <function> defined @Interface/AddOns/Kui_Nameplates/elements/classpowers.lua:760
 PowerEvent = <function> defined @Interface/AddOns/Kui_Nameplates/elements/classpowers.lua:695
 StaggerUpdate = <function> defined @Interface/AddOns/Kui_Nameplates/elements/classpowers.lua:671
 __MESSAGES = <table> {
 }
 priority = 0
 UNIT_AURA = <function> defined @Interface/AddOns/Kui_Nameplates/elements/classpowers.lua:720
 UNIT_POWER_FREQUENT = <function> defined @Interface/AddOns/Kui_Nameplates/elements/classpowers.lua:726
 OnDisable = <function> defined @Interface/AddOns

**Comment by Stanzilla** [comment]
I pushed a fix
