### ISSUE TITLE
Since 10.1, Nameplates only working when targeting.

### ISSUE THREAD

**Issue by MernardStafford** [kesava-wow/kuinameplates2#671]
Nameplates not working on other players. If I target them, it works. If I don't target it shows the default name.

(Works while targeting)

https://imgur.com/a/uC8e4aB  

 (While not targeting)

https://imgur.com/a/oergaOZ

**Comment by MernardStafford** [comment]
Another example... Some NPCs work without targeting, but player names never work without targeting. 
https://imgur.com/a/o4Gb2kT

**Comment by Stanzilla** [comment]
That's a Blizzard bug, use `/run SetCVar("nameplatePlayerMaxDistance", 60)` as a workaround for now

**Comment by MernardStafford** [comment]
Awesome! That worked.. Is there a workaround for the NPC?

**Comment by Stanzilla** [comment]
Not really, sorry!

**Comment by MernardStafford** [comment]
Hey no worries! You are a life saver, it feels so wrong not to have Kui active! Thank you for the help

**Comment by Noppez** [comment]
thx Stanzilla, your workaround worked for me, I was losing my mind, everytime blizzard destroys my UI with updates :c

**Comment by Stanzilla** [comment]
Should be fixed by Blizzard now
