### ISSUE TITLE
Some casts bars are showing cast bar in different direction

### ISSUE THREAD

**Issue by VladPolovyi** [kesava-wow/kuinameplates2#673]
For example eye beam cast sometimes going different direction then sticks on target after cast is over. I can provide some videos later its will be needed.

**Comment by Stanzilla** [comment]
Video would be great, yeah

**Comment by VladPolovyi** [comment]
Here we go, so here dh got killed, but cast bar stays on target after that.
i remember it also happens to mw cast bar i think and maybe disc priest penence. some mobs too

https://www.youtube.com/watch?v=xDD5L-eqstI&ab_channel=VladPolovyi

**Comment by Stanzilla** [comment]
So you are saying that channeled spell castbars are moving from left to right instead of right to left?

**Comment by VladPolovyi** [comment]
Yes, but I cannot confirm if it happens every single time.
Happened after evoker cast bar changes update.

**Comment by Stanzilla** [comment]
Yeah could be https://github.com/kesava-wow/kuinameplates2/commit/2e6f476c15ee2311fc8cb18dfee0eef0e0cad782#diff-12299bedb60f93ff7fad84ba659dc835727d049a5cf064da6c7e2d6d0a962543R115

@kesava-wow thoughts?

**Comment by Stanzilla** [comment]
I pushed a new alpha, can you see if that fixes it?

**Comment by VladPolovyi** [comment]
Hey, didnt have much time to play today but i remembered i can test on personal castbar.
Here is DH eye beam behaviour. Couldn't reproduce mw casting or penance. But i bealive its still there sometimes.
Using latest version: Kui_Nameplates-2.29.5-1-gc4b74a6.zip

https://www.youtube.com/watch?v=VLIED0eJKXQ&ab_channel=VladPolovyi

**Comment by VladPolovyi** [comment]
Hey, it might be a fix

https://www.youtube.com/watch?v=uVqxvOo-64I&ab_channel=VladPolovyi

But tested on DH only tho.

Not sure if this make sense to you, i dont knowladge of the project code.
