### ISSUE TITLE
some unit have double nameplate and cast bar，and they stick together

### ISSUE THREAD

**Issue by Cecilhzy** [kesava-wow/kuinameplates2#674]
![image](https://user-images.githubusercontent.com/132649472/236400310-e973e5d3-3689-4a66-9500-854da89cd1cd.png)
here is the picture
red arrow towards two nameplates that stick together,but actually there is only one unit

**Comment by Stanzilla** [comment]
I pushed a new alpha, can you see if that fixes it?

**Comment by Cecilhzy** [comment]
> I pushed a new alpha, can you see if that fixes it? But in your case it looks like you have two nameplate addons installed?

yeah i have tried and it fixed already,ty for that.And im pretty sure that i have only one nameplate addon cause only particular unit has two nameplates.
