### ISSUE TITLE
Issue since 10.1.5

### ISSUE THREAD

**Issue by Sythr4l** [kesava-wow/kuinameplates2#680]
Addon does not load at all, with the following error:

1x Kui_Nameplates/plugins/guildtext.lua:55: attempt to index local 'source' (a nil value)
[string "@Kui_Nameplates/plugins/guildtext.lua"]:55: in function `FixPattern'
[string "@Kui_Nameplates/plugins/guildtext.lua"]:59: in function `Initialise'
[string "@Kui_Nameplates/addon.lua"]:178: in function <Kui_Nameplates/addon.lua:154>

Locals:
source = nil
(*temporary) = "^"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'source' (a nil value)"

**Comment by Skweril** [comment]
same

**Comment by Theonidus17** [comment]
same problem as well

**Comment by lucaswj** [comment]
Yep. She's borked.

**Comment by Dmeister406** [comment]
Same issue here.

**Comment by ttkyle** [comment]
Probably not the best way to fix it but I got them working so far by commenting out the code for the fixpattern fuctions in guildtext.lua


  --  local function FixPattern(source)
        --return "^"..source:gsub("%%.%$?s?",".+").."$"
    end
    --pattern = FixPattern(TOOLTIP_UNIT_LEVEL)
    --pattern_type = FixPattern(TOOLTIP_UNIT_LEVEL_TYPE)
    --pattern_class = FixPattern(TOOLTIP_UNIT_LEVEL_CLASS)
    --pattern_class_type = FixPattern(TOOLTIP_UNIT_LEVEL_CLASS_TYPE)

**Comment by 0xjc** [comment]
Not the addon author, but this should work as a quick fix. Replace the file `Kui_Nameplates\plugins\guildtext.lua`

[guildtext.lua.txt](https://github.com/kesava-wow/kuinameplates2/files/12021936/guildtext.lua.txt)

(you will have to change the extension back to `.lua`)

**Comment by Vtergo** [comment]
> 

THANK YOU

**Comment by Vtergo** [comment]
> Not the addon author, but this should work as a quick fix. Replace the file `Kui_Nameplates\plugins\guildtext.lua`
> 
> [guildtext.lua.txt](https://github.com/kesava-wow/kuinameplates2/files/12021936/guildtext.lua.txt)
> 
> (you will have to change the extension back to `.lua`)

THANK YOU!!!

**Comment by asutton03** [comment]
> Not the addon author, but this should work as a quick fix. Replace the file `Kui_Nameplates\plugins\guildtext.lua`
> 
> [guildtext.lua.txt](https://github.com/kesava-wow/kuinameplates2/files/12021936/guildtext.lua.txt)
> 
> (you will have to change the extension back to `.lua`)

Unfortunately, this fix didn't seem to work for me.
