### ISSUE TITLE
Ebon Might bar overlapping personal resource bar

### ISSUE THREAD

**Issue by bunster** [kesava-wow/kuinameplates2#683]
![image](https://github.com/kesava-wow/kuinameplates2/assets/51261394/18ed6b04-ca28-4dec-8029-20bb1ebaf952)

Like the image shows

**Comment by Norvelas** [comment]
commenting for when solution comes around

**Comment by Ao1kamy** [comment]
Yeah have the same issue sometimes also with brew default stagger bar also overlapping... Any solutions?

**Comment by Yakkers17** [comment]
I was able to duct tape fix this by making an addon with the following in its init code (or you could also add it to any existing addon):

ClassNameplateEbonMightBarFrame:UnregisterAllEvents()
ClassNameplateEbonMightBarFrame:HookScript("OnShow", ClassNameplateEbonMightBarFrame.Hide)
ClassNameplateEbonMightBarFrame:Hide()

**Comment by Norvelas** [comment]
> I was able to duct tape fix this by making an addon with the following in its init code (or you could also add it to any existing addon):
> 
> ClassNameplateEbonMightBarFrame:UnregisterAllEvents() ClassNameplateEbonMightBarFrame:HookScript("OnShow", ClassNameplateEbonMightBarFrame.Hide) ClassNameplateEbonMightBarFrame:Hide()

i'm guessing you used notepad and just inserted those lines and saved it right? where exactly did you place them?

**Comment by wowloverz** [comment]
Hello to you dear fellow player. If one of you or anyone else could explain where to put these lines of code. Or more generally, the procedure to follow to resolve this problem, in a little more detail. I will thank him for a long time in my mind.
