### ISSUE TITLE
Personal Resource issue

### ISSUE THREAD

**Issue by wowloverz** [kesava-wow/kuinameplates2#691]
![WoWScrnShot_110423_052508](https://github.com/kesava-wow/kuinameplates2/assets/149856578/190f5089-3e97-4469-a880-ac7394045f6d)

Hello, I have this problem. I'm starting again after 2 years and I see that not many people have the same problem, I don't understand why. But above all I haven't found any solution to the problem and it's horrible. I love KNM please need help

**Comment by wowloverz** [comment]
This is a bug, a dubbing of my Stagger as a Brewmaster Monk. I can remove the display of this resource but this copy, this double bar never disappears. Sometimes it disappears for 5 minutes randomly and it comes right back.

**Comment by wowloverz** [comment]
( to be honest I've been trying to use Platers for the last few hours. In reality there is no addon as beautiful as KNM. I try I try to find a glitch without any success )

**Comment by Easyaeta** [comment]
Just coming here to say I'm having the same issue. Just started recently and it's only on Brewmaster Monk

**Comment by Stanzilla** [comment]
Please post your settings from /knp dump, I'm not sure what the issue is that you guys are pointing out? That the stagger bar shows even though you disabled it?

**Comment by Easyaeta** [comment]
The stagger bar, regardless of setting uses the default blizzard bar and is positioned directly in the center of the knp personal resource bars no matter if you have it enabled or disabled. Also the knp custom stagger resource bar will never be used no matter what setting is chosen. Also switching specializations or typing /reload can cause all hell to break loose. Everything works as normal if you opt to ignore personal nameplate in the General tab though.

This only happens on brewmaster monk, windwalker works perfectly fine.
![bmmonk](https://github.com/kesava-wow/kuinameplates2/assets/150335602/99ad0b91-0e95-420e-8b02-40798083b1ec)
![wwmonk](https://github.com/kesava-wow/kuinameplates2/assets/150335602/647e672f-0a89-4f59-82cf-65a2fc815945)
![bmwwmonk](https://github.com/kesava-wow/kuinameplates2/assets/150335602/764067c7-6486-4100-a3aa-35aaa9f3a796)

First image is Brewmaster. The second is Windwalker. The third is switching from Brewmaster to Windwalker


Here are the settings from /knp dump

2.29.10 2.5
enUS MONK
{profile=default}
{auras_icon_normal_size=20,auras_offset=1,auras_show_all_self=true,castbar_colour={1=0.902,2=0.8,3=0.278},castbar_height=14,castbar_showpersonal=true,classpowers_on_target=false,classpowers_y=-3,clickthrough_friend=true,clickthrough_self=true,colour_player_class=true,cvar_enable=true,cvar_name_only=true,cvar_personal_show_target=true,cvar_show_friendly_npcs=true,execute_enabled=false,frame_height=24,frame_height_personal=14,frame_height_target=28,frame_width=140,frame_width_target=168,health_text=true,health_text_hostile_dmg=6,nameonly_combat_hostile=false,nameonly_damaged_enemies=false,nameonly_enemies=false,nameonly_neutral=true,powerbar_height=4,tankmode_tank_colour={1=0.835,2=0.031,3=0.02}}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, ClassPowers, CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, [Execute], TankMode, Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target

**Comment by wowloverz** [comment]
> Veuillez publier vos paramètres à partir de /knp dump, je ne suis pas sûr du problème que vous signalez ? Que la barre décalée s'affiche même si vous l'avez désactivée ?

2.29.10 2.5
frFR MONK
{profile=Boogiepop}
{auras_cd_offset_x=9,auras_cd_offset_y=-8,auras_cd_x=9,auras_cd_y=-5,auras_centre=false,auras_count_offset_x=4,auras_count_point=1,auras_count_x=1,auras_count_y=1,auras_icon_minus_size=20,auras_icon_normal_size=23,auras_icon_squareness=0.9,auras_offset=14,auras_purge_size=27,auras_show_all_self=true,bar_texture=Clean,bot_vertical_offset=-4,castbar_colour={1=0.902,2=0.494,3=0},castbar_detach=true,castbar_detach_height=10,castbar_detach_nameonly=true,castbar_detach_offset=10,castbar_detach_width=113,castbar_height=13,castbar_icon=false,castbar_name_vertical_offset=8,class_colour_enemy_names=true,classpowers_bar_height=0,classpowers_bar_width=0,classpowers_colour_inactive={1=0.114,2=0.118,3=0.114,4=0.81},classpowers_colour_monk={1=0,2=0.898,3=1},classpowers_on_friends=false,classpowers_size=21,classpowers_y=-7,colour_absorb={1=0.055,2=0,3=1,4=0.5},colour_player_class=true,cvar_enable=true,cvar_name_only=true,cvar_personal_show_always=true,execute_auto=false,execute_percent=15,fade_avoid_casting_interruptible=true,fade_conditional_alpha=0.4,fade_non_target_alpha=0.4,fade_speed=0.05,fade_untracked=true,font_size_normal=16,font_size_small=12,frame_glow_size_shadow=5,frame_glow_size_target=12,frame_height=12,frame_height_minus=8,frame_height_personal=18,frame_target_size=false,frame_width=113,frame_width_minus=59,frame_width_personal=118,frame_width_target=65,guild_text_players=true,health_text=true,health_text_hostile_dmg=2,ignore_uiscale=true,level_nameonly=true,level_text=true,mouseover_glow=true,mouseover_glow_colour={1=0,2=1,3=0.392,4=1},name_colour_npc_hostile={1=0.89,2=0.369,3=0.408},name_colour_white_in_bar_mode=false,name_vertical_offset=2,nameonly_combat_hostile_player=false,powerbar_height=4,quest_icon_point=1,quest_icon_size=44,quest_icon_x=-27,quest_icon_y=23,tankmode_other_colour={1=0.706,2=0,3=1},tankmode_tank_colour={1=0.502,2=0.486,3=1},tankmode_tank_glow_colour={1=0.145,2=0.902,3=0.863,4=0.6},tankmode_trans_colour={1=1,2=1,3=0},tankmode_trans_glow_colour={1=0.957,2=1,3=0,4=0.6},target_arrows=true,target_arrows_size=30,target_glow_colour={1=1,2=0,3=0.129,4=1}}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, ClassPowers, CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, TankMode, Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target

**Comment by wowloverz** [comment]
> Veuillez publier vos paramètres à partir de /knp dump, je ne suis pas du problème que vous signalez sûr ? Que la barre décalée s'affiche même si vous l'avez désactivée ?

Hello, thank you! Here is the /knp dump

In summary, it is strictly impossible for us to remove the display of this black stagger bar that you see appearing on my personal resource bar (life + energy). I think it's Blizzard's own stagger bar.

**Comment by Stanzilla** [comment]
If you uncheck this, it goes away, right? 
![image](https://github.com/kesava-wow/kuinameplates2/assets/75278/504ee6dd-204b-4159-8e2c-6b39bf3eab26)

**Comment by wowloverz** [comment]
Nop I already try, it doesn't work . It doesn't remove at all the black stagger bar that is superimposed that you saw in the photos.

**Comment by wowloverz** [comment]
> If you uncheck this, it goes away, right? ![image](https://user-images.githubusercontent.com/75278/282297783-504ee6dd-204b-4159-8e2c-6b39bf3eab26.png)


Nop I already try, it doesn't work . It doesn't remove at all the black stagger bar that is superimposed that you saw in the photos.

**Comment by Stanzilla** [comment]
> > If you uncheck this, it goes away, right? ![image](https://user-images.githubusercontent.com/75278/282297783-504ee6dd-204b-4159-8e2c-6b39bf3eab26.png)
> 
> Nop I already try, it doesn't work . It doesn't remove at all the black stagger bar that is superimposed that you saw in the photos.

try latest alpha

**Comment by wowloverz** [comment]
> > > If you uncheck this, it goes away, right? ![image](https://user-images.githubusercontent.com/75278/282297783-504ee6dd-204b-4159-8e2c-6b39bf3eab26.png)
> > 
> > 
> > Nop I already try, it doesn't work . It doesn't remove at all the black stagger bar that is superimposed that you saw in the photos.
> 
> try latest alpha

Okeyy I see . If you have a minute to spare, can you explain to me how I do it. Otherwise I would look, I thought I saw in the "Code" tab that there were new files particularly related to what you are telling me, I suppose it's there. But to import this into the in-game addon, I don't know where to start lol.

**Comment by Stanzilla** [comment]
> > > > If you uncheck this, it goes away, right? ![image](https://user-images.githubusercontent.com/75278/282297783-504ee6dd-204b-4159-8e2c-6b39bf3eab26.png)
> > > 
> > > 
> > > Nop I already try, it doesn't work . It doesn't remove at all the black stagger bar that is superimposed that you saw in the photos.
> > 
> > 
> > try latest alpha
> 
> Okeyy I see . If you have a minute to spare, can you explain to me how I do it. Otherwise I would look, I thought I saw in the "Code" tab that there were new files particularly related to what you are telling me, I suppose it's there. But to import this into the in-game addon, I don't know where to start lol.

Are you using CurseForge to update your addons? If yes, you can right-click an addon there and set the "release type" to "alpha".

**Comment by wowloverz** [comment]
> > > > > If you uncheck this, it goes away, right? ![image](https://user-images.githubusercontent.com/75278/282297783-504ee6dd-204b-4159-8e2c-6b39bf3eab26.png)
> > > > 
> > > > 
> > > > Nop I already try, it doesn't work . It doesn't remove at all the black stagger bar that is superimposed that you saw in the photos.
> > > 
> > > 
> > > try latest alpha
> > 
> > 
> > Okeyy I see . If you have a minute to spare, can you explain to me how I do it. Otherwise I would look, I thought I saw in the "Code" tab that there were new files particularly related to what you are telling me, I suppose it's there. But to import this into the in-game addon, I don't know where to start lol.
> 
> Are you using CurseForge to update your addons? If yes, you can right-click an addon there and set the "release type" to "alpha".

You are awesome thanks you so much lol I appreciate your help . This work perfectly now. Have a nice day !

**Comment by Easyaeta** [comment]
The issue still persists for me
