### ISSUE TITLE
Monk Brewmaster Stagger nil value?

### ISSUE THREAD

**Issue by phoenixoh7** [kesava-wow/kuinameplates2#695]
Blizzard must have changed something on how stagger is reported because I am getting this error on both this addon and my unit frames. 

Message: ...rface/AddOns/Kui_Nameplates/elements/classpowers.lua:699: attempt to compare nil with number
Time: Wed Nov 15 08:51:03 2023
Count: 124
Stack: ...rface/AddOns/Kui_Nameplates/elements/classpowers.lua:699: attempt to compare nil with number
[string "=[C]"]: ?
[string "@Interface/AddOns/Kui_Nameplates/elements/classpowers.lua"]:699: in function `StaggerUpdate'
[string "@Interface/AddOns/Kui_Nameplates/elements/classpowers.lua"]:748: in function `?'
[string "@Interface/AddOns/Kui_Nameplates/elements/classpowers.lua"]:797: in function <...rface/AddOns/Kui_Nameplates/elements/classpowers.lua:796>

Locals: (*temporary) = <function> defined =[C]:-1

2.29.10-2-gadbb215 2.5
enUS MONK
{profile=default}
{health_text=true}
HealthBar, CombatUpdate, NameText, LevelText, RaidIcon, ClassPowers, CastBar, Highlight, PowerBar, AbsorbBar, Threat, Auras, Classification, Execute, TankMode, Fading, GuildText, PlayerAnchor, [CombatToggle], ArenaID, BossMods, Quest, BarAnimation, Target

**Comment by Stanzilla** [comment]
Thank you, fixed!
