### ISSUE TITLE
Not sure if issue but... nameplate position helper is huge when using fstack

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates2#70]
I've been messing around with frame positioning in one of my addons so I had framestack on when I noticed something. Not sure if intended or not but I wanted to report it anyway

I think this image captures what I saw better than words:

![wowscrnshot_081316_175256](https://cloud.githubusercontent.com/assets/9342192/17646061/27dc15b4-617f-11e6-86fc-dac9a4788f56.jpg)

**Comment by kesava-wow** [comment]
Side-effect of a little hack to allow frames to be positioned on pixels without being delayed by a frame. You can tap ALT when in fstack to cycle through frames under your mouse.

**Comment by ceylina** [comment]
Yup, wasn't concerned about the size of that frame, just thought I would bring it up.
