### ISSUE TITLE
10.2.5 issue when changing colors for various settings

### ISSUE THREAD

**Issue by Sythr4l** [kesava-wow/kuinameplates2#702]
This error occurs when I attempt to change the color of a setting.

5x Kui_Nameplates_Core_Config/helpers.lua:421: attempt to call method 'SetColorRGB' (a nil value)
[string "@Kui_Nameplates_Core_Config/helpers.lua"]:421: in function <Kui_Nameplates_Core_Config/helpers.lua:410>

Locals:
self = KuiNameplatesCoreConfigtarget_glow_colourColourPicker {
 0 = <userdata>
 enabled = <function> defined @Kui_Nameplates_Core_Config/create.lua:70
 label = FontString {
 }
 env = "target_glow_colour"
 block = Frame {
 }
 Set = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:401
 Get = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:396
}
val = <table> {
 1 = 0
 2 = 0.772549
 3 = 1
 4 = 1
}
(*temporary) = nil
(*temporary) = ColorPickerFrame {
 0 = <userdata>
 GetColorRGB = <function> defined @FrameXML/ColorPickerFrame.lua:79
 DragBar = Frame {
 }
 OnKeyDown = <function> defined @FrameXML/ColorPickerFrame.lua:53
 cancelFunc = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:383
 previousValues = <table> {
 }
 SetupColorPickerAndShow = <function> defined @FrameXML/ColorPickerFrame.lua:62
 OnLoad = <function> defined @FrameXML/ColorPickerFrame.lua:3
 opacity = 0
 OnShow = <function> defined @FrameXML/ColorPickerFrame.lua:34
 GetPreviousValues = <function> defined @FrameXML/ColorPickerFrame.lua:91
 GetColorAlpha = <function> defined @FrameXML/ColorPickerFrame.lua:83
 hasOpacity = true
 GetExtraInfo = <function> defined @FrameXML/ColorPickerFrame.lua:87
 Header = Frame {
 }
 Footer = Frame {
 }
 func = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:383
 Border = Frame {
 }
 Content = Frame {
 }
 opacityFunc = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:383
}
(*temporary) = 0
(*temporary) = 0.772549
(*temporary) = 1
(*temporary) = "attempt to call method 'SetColorRGB' (a nil value)"
opt = KuiNameplatesCoreConfig {
 0 = <userdata>
 LayoutLoaded = <function> defined @Kui_Nameplates_Core_Config/main.lua:575
 CreateCheckBox = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:116
 CreatePopupPage = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:546
 Locale = <function> defined @Kui_Nameplates_Core_Config/main.lua:513
 TabList = KuiNameplatesCoreConfigTabList {
 }
 CreateConfigPage = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:529
 CreateButton = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:71
 pages = <table> {
 }
 ScrollFrame = KuiNameplatesCoreConfigPageScrollFrame {
 }
 CurrentPage_UpdateClipboardButton = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:1064
 PageBG = Frame {
 }
 GetLocale = <function> defined @Kui_Nameplates_Core_Config/main.lua:542
 ConfigChanged = <function> defined @Kui_Nameplates_Core_Config/main.lua:547
 profile = <table> {
 }
 name = "Kui |cff9966ffNameplates Core"
 LocaleLoaded = <function> defined @Kui_Nameplates_Core_Config/main.lua:523
 ClipboardButton = Button {
 }
 CurrentPage_Copy = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:1004
 CurrentPage_Name = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:999
 Initialise = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:1161
 CurrentPage_ClipboardButtonClick = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:1048
 CreateSlider = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:314
 CurrentPage_Paste = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:1021
 CurrentPage_CanPaste = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:1032
 CreateSeparator = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:478
 config = <table> {
 }
 active_page = KuiNameplatesCoreConfiggeneralPage {
 }
 CreateColourPicker = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:425
 CreateDropDown = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:1

**Comment by neowest1990** [comment]
[kui.zip](https://github.com/kesava-wow/kuinameplates2/files/14071962/kui.zip)
I fix this and add rogue anima charged combopoints indication on personal resource bar combopoints icons. Now has 2 more colors settings on personal resource settings for anima charged combopoints

**Comment by Stanzilla** [comment]
> [kui.zip](https://github.com/kesava-wow/kuinameplates2/files/14071962/kui.zip) I fix this and add rogue anima charged combopoints indication on personal resource bar combopoints icons. Now has 2 more colors settings on personal resource settings for anima charged combopoints

Can you make a pull request please?

**Comment by IrishMoxie** [comment]
I'm also getting this same error after installing the latest release.

`14x Kui_Nameplates_Core_Config/helpers.lua:421: attempt to call method 'SetColorRGB' (a nil value)
[string "@Kui_Nameplates_Core_Config/helpers.lua"]:421: in function <Kui_Nameplates_Core_Config/helpers.lua:410>

Locals:
self = KuiNameplatesCoreConfigcolour_neutralColourPicker {
 0 = <userdata>
 label = FontString {
 }
 env = "colour_neutral"
 block = Frame {
 }
 Set = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:401
 Get = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:396
}
val = <table> {
 1 = 1
 2 = 0.800000
 3 = 0
}
(*temporary) = nil
(*temporary) = ColorPickerFrame {
 0 = <userdata>
 DragBar = Frame {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 OnKeyDown = <function> defined @FrameXML/ColorPickerFrame.lua:53
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 swatchFunc = <function> defined @ElvUI/Core/General/Core.lua:62
 template = "Transparent"
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 hasOpacity = false
 GetExtraInfo = <function> defined @FrameXML/ColorPickerFrame.lua:87
 Header = Frame {
 }
 Footer = Frame {
 }
 previousValues = <table> {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 opacity = 1
 cancelFunc = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:383
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 PixelSnapDisabled = true
 GetColorRGB = <function> defined @FrameXML/ColorPickerFrame.lua:79
 func = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:383
 Center = Texture {
 }
 LeftEdge = Texture {
 }
 BottomEdge = Texture {
 }
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 backdropInfo = <table> {
 }
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 TopLeftCorner = Texture {
 }
 OnLoad = <function> defined @FrameXML/ColorPickerFrame.lua:3
 TopEdge = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 Border = Frame {
 }
 SetupColorPickerAndShow = <function> defined @FrameXML/ColorPickerFrame.lua:62
 GetPreviousValues = <function> defined @FrameXML/ColorPickerFrame.lua:91
 GetColorAlpha = <function> defined @FrameXML/ColorPickerFrame.lua:83
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 OnShow = <function> defined @FrameXML/ColorPickerFrame.lua:34
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 Content = Frame {
 }
 opacityFunc = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:383
}
(*temporary) = 1
(*temporary) = 0.800000
(*temporary) = 0
(*temporary) = "attempt to call method 'SetColorRGB' (a nil value)"
opt = KuiNameplatesCoreConfig {
 0 = <userdata>
 LayoutLoaded = <function> defined @Kui_Nameplates_Core_Config/main.lua:575
 CreateCheckBox = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:116
 CreatePopupPage = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:546
 Locale = <function> defined @Kui_Nameplates_Core_Config/main.lua:513
 TabList = KuiNameplatesCoreConfigTabList {
 }
 CreateConfigPage = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:529
 CreateButton = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:71
 pages = <table> {
 }
 ScrollFrame = KuiNameplatesCoreConfigPageScrollFrame {
 }
 CurrentPage_UpdateClipboardButton = <function> defined @Kui_Nameplates_Core_Config/helpers.lua:1064
 PageBG = `

**Comment by IrishMoxie** [comment]
I'm also still getting this error after updating to 2.9.11 (yesterday's alpha).

**Comment by Stanzilla** [comment]
> I'm also still getting this error after updating to 2.29.11 (yesterday's alpha).

retail or classic?

**Comment by IrishMoxie** [comment]
Retail. I just reinstalled 2.29.11-1-g48c446b, the same file, and it seems to be working fine now so I've no idea what was up.

**Comment by wUEZRs** [comment]
> Retail. I just reinstalled 2.29.11-1-g48c446b, the same file, and it seems to be working fine now so I've no idea what was up.

If anyone else has problems, "View" the addon in curseforge and install the Alpha version.
