### ISSUE TITLE
Cataclysm Classic?

### ISSUE THREAD

**Issue by ziadio** [kesava-wow/kuinameplates2#711]
Hello, KUI is no longer working for Cataclysm Classic, any updates on this? Thanks

**Comment by Stanzilla** [comment]
> Same question, update is not looking hard

Ah that is good to know. I recently merged a PR for Cata compat, can you test it and see if that fixes all the things you found that need changes?

**Comment by ziadio** [comment]
I have a raid tonight and I cant use anything but KUI!

**Comment by Litvan** [comment]
> > Same question, update is not looking hard
> 
> Ah that is good to know. I recently merged a PR for Cata compat, can you test it and see if that fixes all the things you found that need changes?

worked for me on a training dummy in SW
![image](https://github.com/kesava-wow/kuinameplates2/assets/15156240/65e9fd48-fbaf-4d3d-99e7-3c764bbdaf75)

**Comment by ziadio** [comment]
What fix?! Can you share the files?

**Comment by Stanzilla** [comment]
> Well, typical fix its add (or fix) info about new interface platform (for cataclysm), usualy its just changa interface number, but some addont have new files for cata special, il tryend do the same but it not work :(

Okay, thanks for the insight!
