### ISSUE TITLE
Texture License?

### ISSUE THREAD

**Issue by sBaildon** [kesava-wow/kuinameplates2#74]
Hey,

I was hoping to use your bar and shadowBorder textures in an addon pack I intend to release. I'm not using any of the Kui addons, just enquiring specifically about the textures.

Is this something you'd allow?

**Comment by kesava-wow** [comment]
Yes. Just call it "Kui status bar" if you're adding it to LibSharedMedia or something. Otherwise, put a readme.txt in the directory stating which files came from where.
