### ISSUE TITLE
Add option to show both current and percent health

### ISSUE THREAD

**Issue by kballard** [kesava-wow/kuinameplates2#79]
I really want to see both the current health and the percent at the same time.

I looked into implementing this myself, but it appears that the only way to add new health display options without breaking anybody who's customized their nameplates already is to add it after the "Blank" option, which is kinda weird. Is there any way to deal with inserting new options into the middle of the list?

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplatesextras/issues/13
