### ISSUE TITLE
Disable execute range for classes without an execute

### ISSUE THREAD

**Issue by kballard** [kesava-wow/kuinameplates2#80]
I have the default settings of "enable execute range" and "auto-detect range" both on. Having auto-detected executes for classes that have executes seems like a good idea. But when I'm playing a class that doesn't have an execute, I don't want there to be any execute range (after all, what's the point?). But I don't see any way to do this. Even if I disable "auto-detect range", set the manual range to zero, and re-enable "auto-detect range", it still shows the execute at 20%.

**Comment by kesava-wow** [comment]
The point in having execute range default to 20% is so you can use it to spot low health units, and it's used for the frame fading rules.
