### ISSUE TITLE
Secondary description aka vendor/spell names sometimes attaches to other NPCs

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates2#84]
I just started noticing this within the past few days.

I am running 2-11-2-1-gb0529bb but it was doing it since at least the previous release.

What happens is when you come in range of an NPC with a secondary text display and have name only for the name plates, it will often affix to another NPC that does not have any secondary title or description.

I just noticed it right before posting this where I was flying in one of the older zones and came up to an NPC with the "Fish Merchant" under their name. Now as I moved along a child NPC also had "Fish Merchant". I had seen this previously and just over looked it but this was obvious. 

This isn't something that happens all the time and it is very subtle but I want to raise an issue as I try and trace this down. Nothing is essentially corrupted, it is just that the secondary description below the name on NPCs sometimes jumps to other NPCs in range to draw the name only nameplate.

If you need anything from me or need further testing, please let me know. AS I find more I will comment on this ticket.

**Comment by kesava-wow** [comment]
Known but I haven't seen it very often. In this particular example were you targeting the fish merchant NPC or does it happen regardless?

Thanks.

**Comment by ceylina** [comment]
I interacted/targeted with this merchant then moved on and that is when I saw the title on the other NPC that should not have it.

It could be that this second NPC was out of the draw distance when I was interacting with the vendor.

**Comment by oleerik** [comment]
I'm very confused by this one myself. Not sure what is causing it but I don't think draw distance has anything to do with it.

I've also experienced a strange bug where red monsters look gray in kui. These might be related.

**Comment by kesava-wow** [comment]
I know what's causing it, don't worry about it. Grey is used when an enemy is tapped by the opposite faction.

**Comment by oleerik** [comment]
@kesava-wow Hm, that's weird. I've had it happening multiple times in dungeons even.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/commit/0f14dc4b41c21a70e71bf73cf45048d2978576f7
