### ISSUE TITLE
Show true level in battlegrounds

### ISSUE THREAD

**Issue by Icehawk15** [kesava-wow/kuinameplates2#86]
One of the recent minor updates in WOW 7.0 seems to have done something to the nameplates inside an instanced battleground. Previously the character levels would show as they are, for instance a level 23 would show as level 23, a level 26 as level 26 and so on. But now no matter what level the toon is, it appears as max level in that battleground. For instance a level 21 appears as a level 29. All toons in the say 20 - 29 bracket show up as 29.
I understand all are scaled to 29 stat wise, but previously Kui would distinguish between the levels inside the battleground.
Is it possible to get the level text to match the actual level of the toon rather than the max level. It helps so much to know the exact level on the nameplate.
Thanks in advance.

**Comment by kesava-wow** [comment]
I don't see why you'd need this. Everyone is scaled now.

**Comment by Icehawk15** [comment]
Hi Kesava. Thanks for your response. I understand that everyone is scaled stat wise but seeing on the health bars what level they really are helps as there is a difference in abilities between lvl say 40 and 49. In my case I know the abilities that higher level toons have so I will plan my attacks / counters accordingly. It used to pick the level and show it on the Kui Nameplate health bar but now it only shows the higher scaled level.
![wowscrnshot_090516_080145](https://cloud.githubusercontent.com/assets/21300111/18235441/6c9be1f4-734d-11e6-8d06-d871eb01dbd9.jpg)
I'll try and add in some screenshots, hope I'm doing it right. The picture above you will see everyone is showing as 29 on the healthbar, but in fact the target I'm looking at is lvl 23 and most others are level 20.
![wowscrnshot_073016_234925](https://cloud.githubusercontent.com/assets/21300111/18235459/ba3720d6-734d-11e6-8a48-df2776946d9d.jpg)
You will see on this older one how it used to show the real level.
It would be so handy in the bg to know exactly what level the toon is by looking at the healthbar. I really hope it's something that could be looked at. I love Kui but just recently something changed with scaling in the bg which it won't detect the true level.
For me it makes a big difference, but if it's not going to be updated I will accept that and move on.

**Comment by kesava-wow** [comment]
Abilities - that's a good point. I will probably make it give actual levels in BGs now that you mention it.

**Comment by Icehawk15** [comment]
Thanks so much Kesava. Hopefully it's something that can be done and I'm ever so thankful if you can do it.

Much appreciated :)

**Comment by kesava-wow** [comment]
Reopening for testing. Improved workflows, woo.

**Comment by Icehawk15** [comment]
I did a bg about an hour or so ago and it still seemed to be showing max level toons in the bg. The only update I had on Curse yesterday was for the kuispellconfig I believe. Not sure if I haven't received the full update notice or not from Curse, but it wasn't working as intended about an hour ago. Screenshot below of today's bg. Hopefully you are able to sort it out :)

Thanks in advance.
![wowscrnshot_090916_075814](https://cloud.githubusercontent.com/assets/21300111/18372601/79e3c6bc-7670-11e6-98c4-2c2da2fbdb35.jpg)

**Comment by kesava-wow** [comment]
It's not on the release or beta versions, only the alpha.

**Comment by Icehawk15** [comment]
Just wanted to stop in and say thanks for sorting this out. It's very much appreciated.

Thank you :)
