### ISSUE TITLE
Suramar City

### ISSUE THREAD

**Issue by Qpadder** [kesava-wow/kuinameplates2#87]
Hi, The plates are very high on the NPC in Suramar City and they cover over the symbol that tells if they can see your disguise. Anything that can be done to fix this ?

**Comment by kesava-wow** [comment]
This is a blizzard problem. I can't arbitrarily move nameplates without breaking the click box.

**Comment by kesava-wow** [comment]
You may enjoy this: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.detection-icon.lua

It adds an icon to the detectors in suramar. Read the readme on the main page of that repo for information on how to use it.
