### ISSUE TITLE
Icon for guild members

### ISSUE THREAD

**Issue by EiniStein** [kesava-wow/kuinameplates2#91]
Hello,

this is a feature request.

I would like the option to see an icon (or anything) on nameplates of other guild members. I used this with Tidyplates in the past and it really helps to notice other guildies being around the very same place (towns, quests, etc). Would likely make sense to automatically turn it off in groups/raids.

Thanks for all the work!

**Comment by benoitheylens** [comment]
Would be awesome (and if it was possible to dynamically take the guild tabard icon, would be awesome :p).
I picture a nice round small icon left to the names.

**Comment by kesava-wow** [comment]
I would probably put this in extras but it's simple enough. Now that ive updated the customs repo I'll put it in there before migrating to extras.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplatesextras/issues/15
