### ISSUE TITLE
Entering pet battle throws following error when "show player titles" is enabled

### ISSUE THREAD

**Issue by ceylina** [kesava-wow/kuinameplates2#95]
Version 2-13-beta-2-14-gb785341

This error only happens when you use name only text plates and have the new "Show player titles" checked in Name-only

`Kui_Nameplates_Core\create.lua:1545: bad argument #1 to 'strlen' (string expected, got nil)
[C]: ?
Kui_Nameplates_Core\create.lua:1545: in function `NameOnlySetNameTextToHealth'
Kui_Nameplates_Core\create.lua:485: in function `UpdateNameText'
Kui_Nameplates_Core\create.lua:1463: in function `NameOnlyUpdateFunctions'
Kui_Nameplates_Core\hook.lua:153: in function `func'
Kui_Nameplates\messages.lua:33: in function `DispatchMessage'
Kui_Nameplates\elements/target.lua:13: in function <Kui_Nameplates\elements/target.lua:11>
Kui_Nameplates\elements/target.lua:48: in function `func'
Kui_Nameplates\messages.lua:33: in function `DispatchMessage'
Kui_Nameplates\nameplate.lua:82: in function `OnHide'
Kui_Nameplates\addon.lua:78: in function `?'
Kui_Nameplates\addon.lua:112: in function <Kui_Nameplates\addon.lua:109>

Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"
`

**Comment by kesava-wow** [comment]
Thanks!
