### ISSUE TITLE
[Request] Guild Icon with names-only

### ISSUE THREAD

**Issue by benoitheylens** [kesava-wow/kuinameplates2#96]
#91 

Hi !

Don't know if it's intended or not but the guild icon does not show up with names-only.
My setup is to set names for friendly and non-aggressive characters and plates for enemies.

I would find awesome to have a nice round or rectangle icon (like you did with alliance and horde icon) on the left of the name displayed so we can see clearly and immediately a nice overview of how much guild members are in a certain area.

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplates2/issues/91

**Comment by kesava-wow** [comment]
https://github.com/kesava-wow/kuinameplatesextras/issues/15
