### ISSUE TITLE
All Enemy Cast Bars as Uninterruptible (only as Warlock)

### ISSUE THREAD

**Issue by remcycle** [kesava-wow/kuinameplates2#98]
![kui cast bars](https://cloud.githubusercontent.com/assets/22161311/18608856/98206a9c-7cc2-11e6-8adf-09d8eea7d8e4.jpg)

Edit: added a screenshot to give an example. The 2 spells being cast by those 2 enemies are usually interruptable.

It seems that only on my warlock do the enemy cast bars all show as uninterruptible. Is it because my interrupts come from my pet and not me as a player? 

For reference, it has been like this at least since the launch of legion, so not a new issue form a recent update. (Btw I love this addon, thank you for your work =D )

**Comment by kesava-wow** [comment]
Sorry for the delay on this one

**Comment by kesava-wow** [comment]
Can't reproduce this. It was/is very likely a blizzard thing anyway since I'm only refering to the API.

**Comment by remcycle** [comment]
Alright! Thanks for inquiring about it! Regardless, I love your addon! Keep up the great work. :D
