### ISSUE TITLE
[Feature Request] Larger nameplates for targeted unit

### ISSUE THREAD

**Issue by derickso** [kesava-wow/kuinameplates2#99]
Request ability to make the target nameplate larger in addition to the light/indicator

**Comment by Daeveren** [comment]
On the same topic, a similar option for having a bigger nameplate for the mobs that you aggro (if in a non-tank spec). Just switched from TidyPlates ThreatPlates, I love Kui so far, but I really miss this useful feature.

**Comment by kesava-wow** [comment]
delegated: https://github.com/kesava-wow/kuinameplates-customs/blob/master/custom.target-scale.lua
